### ISSUE TITLE
[Windows] Constantly prompting that a new version of a game is available

### ISSUE THREAD

**Issue by Arron17** [Heroic-Games-Launcher/HeroicGamesLauncher#761] opened 2021-12-02 22:24 UTC
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
After installing a game Heroic constantly shows that a new version is available. Can only replicate with a single game, while True: learn().

**Add Logs**
`PS C:\Users\Arron\appdata\local\programs\heroic> .\Heroic.exe --enable-logging
PS C:\Users\Arron\appdata\local\programs\heroic>
INFO: Trying to get user information
INFO: Trying to get user information
INFO: Trying to get user information
INFO: Registered protocol with OS.
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 1 game(s) to update
INFO: Trying to get user information
INFO: checking for heroic updates
INFO: Trying to get user information
INFO: Progress: 4f272a49a39742b795d63e1f483a7c7d undefined/undefinedMiB/undefined
INFO: finished updating
INFO: Progress: 4f272a49a39742b795d63e1f483a7c7d undefined/undefinedMiB/undefined
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 1 game(s) to update
INFO: Trying to get user information
INFO: Progress: 4f272a49a39742b795d63e1f483a7c7d undefined/undefinedMiB/undefined
INFO: finished updating
INFO: Progress: 4f272a49a39742b795d63e1f483a7c7d undefined/undefinedMiB/undefined
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 1 game(s) to update
INFO: Saving log file to C:\Users\Arron\AppData\Roaming\heroic\Crashpad/Thu Dec 02 2021.txt`

**To Reproduce**

1. Load up Heroic and select the "Updates" filter, it shows 1 update available
2. Click on "while True: learn()" Game.
3. Click the "Installed - New Version Available! (Click to Update) button.
![image](https://user-images.githubusercontent.com/87210034/144512438-26ad9809-ed69-4bb5-8ecd-bdd45d9cc0ad.png)

4. Toast Message comes up "Update Cancelled"
![image](https://user-images.githubusercontent.com/87210034/144512408-a0d99f1a-e5f0-4955-ac1d-1d3d8f9755ed.png)

**Expected behavior**
Heroic should not prompt that there is a New Version available if there isn't. And once a new version is installed it should stop prompting for updates.

**Desktop (please complete the following information):**

- OS: Windows 11 21H2
- Heroic Version: 1.11.0 Alpha & 1.10.3
- Game: while True: learn()
- Wine/Proton version: N/A
- Hardware specs (RAM, CPU, GPU): N/A

**Additional context**
Because this uses Legendary for the app downloads I tried to replicate the issue in that, however Legendary doesn't show there is an update available.

`PS F:\Downloads> .\legendary.exe list-installed --check-updates
[cli] INFO: Logging in to check for updates...
[Core] INFO: Trying to re-use existing login session...

Installed games:
 * Absolute Drift (App name: 19927295d6e3467887d4e830d8c85963 | Version: Win_202108051533 | 0.33 GiB)
 * while True: learn() (App name: 4f272a49a39742b795d63e1f483a7c7d | Version: 1.3.97.5144.35.win64 | 0.79 GiB)

Total: 2`

I tried a few other games but cannot replicate the issue with any other games.

**Comment by dragonDScript** [comment] 2021-12-04 14:36
Caused by #760

**Comment by flavioislima** [comment] 2021-12-05 12:10
@dragonDScript This is caused by the name of the game. We need to use that Regexp to clean the game name everywhere. It's probably broken on some Json file we use to cache the library or the list of games with update.
I'll install this game to find the issue.

So maybe make that regexp a function that can be used anywhere in the Backend, maybe on a utils or constants file.

**Comment by flavioislima** [comment] 2021-12-05 12:24
This is the line with the issue:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b3418e38f76a7182ad8b87a994f1018f34d7ee39/electron/legendary/library.ts#L228

we need to improve the logic to show if the game has updates or not.

**Comment by flavioislima** [comment] 2021-12-05 12:33
Fixed on Main branch.

**Comment by flavioislima** [comment] 2021-12-05 12:33
Thanks for posting the issue @Arron17

**Closed by flavioislima** 2021-12-05 12:33 UTC

**Comment by dragonDScript** [comment] 2021-12-05 13:28
How did you fix it?
