### ISSUE TITLE
Universal Binary macOS Support/ ARM64 build

### ISSUE THREAD

**Issue by reece394** [Heroic-Games-Launcher/HeroicGamesLauncher#861] opened 2022-01-02 20:07 UTC
**Is your feature request related to a problem? Please describe.**
Apple Silicon Support for Heroic would be good due to the increasing amount of new mac devices coming out with Apple chips. This would allow for M1 and M1 Pro/Max devices to run Heroic natively instead of relying on Rosetta 2 resulting in better battery life and improvements in responsiveness when using the application. 

**Describe the solution you'd like**
A universal binary can be built locally by adding --universal to the package.json of dist mac: 
`"dist-mac": "GH_TOKEN='${{ secrets.WORKFLOW_TOKEN }}' yarn build-electron && yarn build && electron-builder -c.extraMetadata.main=build/main.js --mac --universal"`
This however increases the file size from 343MB to 675MB so potentially a separate ARM64 build may be in order if this is not acceptable?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by flavioislima** [comment] 2022-01-02 21:06
Still, I guess heroic uses almost no cpu. The games are downloaded using legendary and when you play is the game that will eat your battery. So I don't know if this would make much of a difference tbh.

**Comment by reece394** [comment] 2022-01-02 22:32
There probably won't be much difference but would be good for future-proofing anyway for not that much extra effort particularly since legendary was updated for ARM support already in a previous pull request #682

**Comment by girivs82** [comment] 2022-01-20 12:14
FWIW, its trivial to generate arm64 dmg on the Mac from source just by following the building from source instructions in the  readme file.

1. Use Homebrew and install yarn and node (prerequisites for building from source)
2. git clone https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher.git
3. yarn
4. yarn dist-mac

The arm64 dmg will be in the Dist directory.

**Comment by LuigiFan25** [comment] 2022-06-12 00:32
Is there a place where users can contribute the arm64 builds for users who arent as tech savvy 
since for ppl who are tech savvy its relatively easy

**Comment by woj-tek** [comment] 2022-12-12 20:20
> Still, I guess heroic uses almost no cpu. The games are downloaded using legendary and when you play is the game that will eat your battery. So I don't know if this would make much of a difference tbh.

I think it would still make sense as it seems the UI seems to be quite unresponsive. I had issues with some non-ARM applications being slower for some reason (Apple's translation framework not working correctly?)

**Comment by flavioislima** [comment] 2022-12-12 23:38
I added a arm64 build since last release.
Need only to update the website since there only the x64 is being shown to download.

**Comment by woj-tek** [comment] 2022-12-13 00:11
You mean after 2.5.1? I'm looking at the release page (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.5.1) and only see  Heroic-2.5.1.dmg. I downloaded it but it still says "Intel"

**Comment by flavioislima** [comment] 2022-12-13 08:22
> You mean after 2.5.1? I'm looking at the release page (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.5.1) and only see  Heroic-2.5.1.dmg. I downloaded it but it still says "Intel"

Yes, there is a arm64.pkg. It's not dmg otherwise it would break the website.
I will try to fix the website this week so I can name it both dmg.

**Comment by flavioislima** [comment] 2022-12-13 13:32
Wasted my whole day on this matter just to discover that Apple forces the devs to Sign their Apps when building native ARM64 builds and we are not gonna do that any time soon since it is pretty expensive. More information here:
https://github.com/electron-userland/electron-builder/issues/5850

**Closed** 2022-12-13 13:32 UTC
Labels: feature request

**Comment by woj-tek** [comment] 2022-12-13 13:40
Thank you @flavioislima for taking the time. Apple's policy is quite annoying. I tried to peruse the thread and couldn't actually figure out what the problem is. I use quite a lot of apps that are not signed and they work fine(-ish) - I have to confirm them in file vault.

**Comment by flavioislima** [comment] 2022-12-15 13:59
Ok, some people confirm that the arm build worked after a command line, so we will distribute the arm package with this workaround until maybe Apple change this policy (probably never):

`xattr -d com.apple.quarantine | mdfind kMDItemCFBundleIdentifier = "*heroic"
