### ISSUE TITLE
Feature Request: Download Manager

### ISSUE THREAD

**Issue by EndlessEden** [Heroic-Games-Launcher/HeroicGamesLauncher#631] opened 2021-08-27 20:59 UTC
**Is your feature request related to a problem? Please describe.**
A lack of a Download Manager, means its impossible to tell what is currently downloading, what is currently queued and no way to manipulate the queue.

**Describe the solution you'd like**
A download management page, something similiar to what Steam offers would be ideal. With net/disk rate information, Queue list, pause/start option and list of failed/successfully installed games(recent)

**Comment by FunMLG** [comment] 2021-09-05 14:58
Love the idea ! I need it too

**Comment by aha999** [comment] 2021-09-20 10:01
I'm specially interested in the data flow, how much data the update process is consuming...

**Comment by flavioislima** [comment] 2022-02-10 16:58
just noticed that this is a duplicate of #457

**Closed by flavioislima** 2022-02-10 16:58 UTC
Labels: feature request
