### ISSUE TITLE
Windows 10, continuous spawning of cmd and powershell processes. (Also freezes windows because of continuous 100% load)

### ISSUE THREAD

**Issue by cronyakatsuki** [Heroic-Games-Launcher/HeroicGamesLauncher#561] opened 2021-07-25 16:15 UTC
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.

**Describe the bug**
When downloading any game Heroic start spawning more and more powershell and command prompt process that it can even got suc numbers as 400 and locks down the system under 100% cpu load until the game is downloaded.

**To Reproduce**

1. Install heroic on windows 10
2. Open task manager and heroic
3. Start downloading any game
4. Pray that your cpu won't overheat

**Expected behavior**
That it downloads the games without continuous spwaing of processes and locking down the system under load.

**Screenshots**
![Screenshot (14)](https://user-images.githubusercontent.com/64900606/126905879-fe018661-f7e4-4278-b08f-318bc9f5c942.png)
![Screenshot (15)](https://user-images.githubusercontent.com/64900606/126905887-87f1b579-8679-4bbc-b138-e0db24eb9e0f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version [e.g. 22]: 21H1 build 19043.1110
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU): 16 gb (usable 14) 2400 mhz speed dual channel, ryzen 5 3550h and gtx 1650 4gb

**Additional context**

**Comment by flavioislima** [comment] 2021-07-25 17:38
Are you trying to download several games at once? This might be the issue because for every game being downloaded, heroic will spawn the number of legendary process equal to the number of workers set on the general settings Max Workers.

Also, try this other version here, is a new windows test version, portable, that contains several bugfixes that will be on next release:
https://drive.google.com/file/d/1W4I9XIZTz6AhsKEsU8FWub7VPsY_MguH/view?usp=sharing

**Comment by cronyakatsuki** [comment] 2021-07-25 20:42
I only downloaded one game, and after seeing the issue I lowered the workers from 2 to 1 and it still happened.

**Comment by cronyakatsuki** [comment] 2021-07-25 20:46
Just tried the test version and it has the same problem as the regular version.

**Comment by cronyakatsuki** [comment] 2021-07-26 11:32
Note: Heroic spawns 4 legendary processes but continue to spawn powershell and cmd processes for all the time it is downloading anything.

**Comment by flavioislima** [comment] 2021-07-26 12:22
I could not reproduce it:
![image](https://user-images.githubusercontent.com/26871415/126987554-2ae4290e-0fed-42a5-8b2f-58d96655857e.png)
![image](https://user-images.githubusercontent.com/26871415/126987851-af8c28d5-2923-462b-81af-a30e83954ac8.png)

In my case I have max workers to MAX, so you can see I have several Legendary Processes but two only for powershell (one executing install and the other one getting the game progress)

**Comment by flavioislima** [comment] 2021-07-26 12:26
Here using only 2 Workers:
![image](https://user-images.githubusercontent.com/26871415/126988333-7346753b-3732-4e35-a841-7dd44cc60c35.png)

**Comment by cronyakatsuki** [comment] 2021-07-26 13:03
I recorded a video of the problem that I will send over on discord soon.

**Comment by cronyakatsuki** [comment] 2021-07-26 13:39
[video](https://drive.google.com/file/d/19rWgyhQV_TCDkGG7Vlp6TH5gHgRBdB2o/view?usp=sharing) link.

**Comment by cronyakatsuki** [comment] 2021-07-26 17:11
Possible fix for this could be to change the command used to start powershell from example: `powershell legendary install game` to `powershell -NoProfile legendary install game`.

I don't know if this could work or won't

**Comment by flavioislima** [comment] 2021-07-26 19:13
> Possible fix for this could be to change the command used to start powershell from example: `powershell legendary install game` to `powershell -NoProfile legendary install game`.
> 
> I don't know if this could work or won't

We can try but do you know what this flag does?
I can make a test exe tomorrow and send you the link.

**Comment by cronyakatsuki** [comment] 2021-07-26 20:34
It makes sure powershell loads without loading user configs.
That can make sure that user powershell config won't go around breaking things.

**Comment by SanokKule** [comment] 2021-09-20 15:38
![image](https://user-images.githubusercontent.com/24497821/134030769-67448327-aa7b-4019-8d4e-adcda155ca5b.png)
When will you fix this?

**Comment by flavioislima** [comment] 2021-10-09 19:40
That's great. I'll close the issue then.

**Closed by flavioislima** 2021-10-09 19:40 UTC
Labels: issue:investigating, bug:not-confirmed
