### ISSUE TITLE
Games try to launch in the language specified in the system instead of Heroic's app language setting

### ISSUE THREAD

**Issue by leillo1975** [Heroic-Games-Launcher/HeroicGamesLauncher#1432] opened 2022-06-03 23:23 UTC
### Describe the bug

When I launch, for example, Wolfenstein: The new Order, the game starts in English instead to do it on Spanish, as Heroic is configured. This is because my system language is Galician, and as that language is not in the game's language list, it defaults to English. Minority language users should be able to configure this. 

I configured my system on Spanish and now I can play the game on this language, but I prefer to use my OS on my native language.

### Add logs

Launch Command: DXVK_HUD=fps /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch a64dcf9b711a4a60a3c0b6f052dfc7da --wine /usr/bin/wine --wine-prefix /media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO

System Info:
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Ubuntu KERNEL: 5.15.0-33-generic ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 31.26 GiB Available: 28.48 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 VRAM: 8192MB DRIVER: 510.73.05 
PROTOCOL: x11

Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/media/COMP/WINEDRIVE/HEROIC",
	"defaultWinePrefix": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": true,
	"useGameMode": false,
	"userInfo": {
		"epicId": "1900a872a3e1475492dd721838e286ed",
		"name": "leo"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO",
	"wineVersion": {
		"bin": "/usr/bin/wine",
		"name": "Wine Default - wine-7.3 (Staging)"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"disableController": false,
	"egsLinkedPath": "",
	"maxRecentGames": 5,
	"maxSharpness": 2,
	"savesPath": "/media/COMP/WINEDRIVE/HEROIC/PREFIXES/WolfensteinTNO/drive_c/users/leo/Saved Games/MachineGames/Wolfenstein The New Order/base/savegame/1900a872a3e1475492dd721838e286ed/",
	"targetExe": ""
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching a64dcf9b711a4a60a3c0b6f052dfc7da...
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.7 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
00f8:fixme:heap:RtlSetHeapInformation 0000000002DB0000 0 000000000011F6E0 4 stub
00f8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00fc:fixme:heap:RtlSetHeapInformation 0000000000230000 0 000000000374FD58 4 stub
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
00fc:fixme:reg:RegQueryInfoKeyA security argument not supported.
0190:fixme:imm:ImeSetActiveContext (0x133d3610, 1): stub
0190:fixme:imm:ImmReleaseContext (000000000001008E, 00000000133D3610): stub
0080:fixme:imm:ImeSetActiveContext (0x55080, 0): stub
0080:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000055080): stub
00fc:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005B4 0): stub
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005C0 1): stub
00fc:fixme:thread:SetThreadIdealProcessor (00000000000005D0 2): stub
00fc:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
00fc:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
00fc:fixme:wbemprox:client_security_SetBlanket 0000000029A1FDE0, 000000000277D1A0, 10, 0, (null), 3, 3, 0000000000000000, 0
00fc:fixme:wbemprox:client_security_Release 0000000029A1FDE0
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0058:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0058:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
01f4:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01f4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00fc:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
0190:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet

### Steps to reproduce

1. Go to 'Wolfenstein: The new Order' game 
2. Click on Play
3. See the game on English

### Expected behavior

To play the game on Spanish, and have the possibility of configure this.

### System Information

- OS: Ubuntu 22.04
- Heroic Version : 2.3.7

**Comment by arielj** [comment] 2022-06-03 23:26
I think this means 2 features we can add:
- default the language of the game to heroic's language setting
- allow setting a specific language for each game

we can use lengendary's `--language` cli argument in both cases

**Comment by arielj** [comment] 2022-06-05 17:04
just notices this is a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1391, closing this one since the other is older

**Closed by arielj** 2022-06-05 17:04 UTC
