### ISSUE TITLE
Prison architect requires external launcher

### ISSUE THREAD

**Issue by lever1209** [Heroic-Games-Launcher/HeroicGamesLauncher#2134] opened 2022-12-04 02:56 UTC
### Describe the bug

it wont run with heroic, but will run with just legendary on the basic user wine prefix

### Add logs

```text
(22:47:51) INFO:    [Connection]:       Connectivity: check-online
(22:47:51) INFO:    [Connection]:       Pinging external endpoints
(22:47:51) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:47:51) INFO:    [Legendary]:        Legendary location: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/legendary
(22:47:51) INFO:    [Gog]:              GOGDL location: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:47:52) INFO:    [Connection]:       Connectivity: online
(22:47:52) INFO:    [Gog]:              Getting data about the user
(22:47:52) WARNING: [Backend]:          Failed to register protocol with OS.
(22:47:53) INFO:    [Gog]:              Running command: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(22:47:53) INFO:    [Gog]:              Saved user data to config
(22:47:53) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:47:54) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.3 Caesar Clown
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Arch KERNEL: 6.0.8-arch1-1 ARCH: x64
CPU: Intel Core™ i7-3770 @3.4 GOVERNOR: schedutil
RAM: Total: 17.53 GiB Available: 15.96 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1650 VRAM: 4096MB DRIVER: 520.56.06 
PROTOCOL: tty

(22:47:54) INFO:    [Backend]:          Checking for new Heroic Updates
(22:47:54) INFO:    [Frontend]:         Refreshing Library
(22:47:54) INFO:    [Legendary]:        Refreshing library...
(22:47:54) INFO:    [Legendary]:        Refreshing Epic Games...
(22:47:54) INFO:    [Legendary]:        Game list updated, got 206 games & DLCs
(22:47:54) INFO:    [Gog]:              Getting GOG library
(22:47:54) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/legendary list
(22:47:54) INFO:    [Gog]:              Number of library pages: 1
(22:47:55) INFO:    [Gog]:              Saved games data
(22:47:55) INFO:    [Winetricks]:       Downloaded Winetricks
(22:47:57) INFO:    [Backend]:          Launching Prison Architect (668ffa8fce0847ef9f1c005995cee6df)
(22:47:57) INFO:    [Backend]:          Preventing display from sleep
(22:47:58) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(22:47:58) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(22:47:59) INFO:    [Backend]:          Created/Updated Wineprefix at /mnt/terranova/u1/heroic-prefixes/Prison Architect
(22:47:59) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/legendary launch 668ffa8fce0847ef9f1c005995cee6df --json --offline
(22:48:00) INFO:    [Legendary]:        Launching Prison Architect: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/u1/.steam/steam STEAM_COMPAT_DATA_PATH="/mnt/terranova/u1/heroic-prefixes/Prison Architect" DXVK_HUD=fps PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-eurekaPublic PROTON_LOG_DIR=/home/u1 /tmp/.mount_HeroicRMmPGH/resources/app.asar.unpacked/build/bin/linux/legendary launch 668ffa8fce0847ef9f1c005995cee6df --language en --no-wine --wrapper "'/home/u1/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run"
(22:48:03) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(22:48:03) INFO:    [Frontend]:         Refreshing Library
(22:48:03) INFO:    [Legendary]:        Refreshing library...
(22:48:03) INFO:    [Legendary]:        Game list updated, got 206 games & DLCs
```

### Steps to reproduce

1. launch prison architect
2. fails to launch
3. launch with legendary with `legendary launch 668ffa8fce0847ef9f1c005995cee6df --offline`
4. paradox interactive launcher starts

### Expected behavior

game should run, but doesnt

### Screenshots

![image](https://user-images.githubusercontent.com/34011519/205471919-6c7ea91b-ae04-4118-a8be-fae8bea1a3d1.png)

### System Information

- arch linux
- heroic 2.5.0-beta.3

### Additional information

i think it should be given the same treatment as origin launcher games or at least looked into by someone who knows what to look for

**Comment by arielj** [comment] 2022-12-30 05:01
Which version of wine are you using when the launcher doesn't show up? I noticed that with Wine-GE-Proton the launcher DOES show up when launched from Heroic and with Proton-GE-Proton the launcher does NOT show up.

I think it's an issue with proton and not with Heroic since, at least for me, changing to Wine-GE makes the launcher start

**Comment by arielj** [comment] 2023-02-18 16:21
@lever1209 can you confirm if the launcher shows up when using Wine-GE instead of Proton?

**Comment by arielj** [comment] 2023-04-05 05:48
closing this since there's no answer for the last 3 months

**Closed by arielj** 2023-04-05 05:48 UTC

**Comment by joostruis** [comment] 2023-06-18 10:47
I can confirm the launcher works with Wine-GE. I had the same problems as @lever1209
