### ISSUE TITLE
Heroic Launcher store won't let me log in

### ISSUE THREAD

**Issue by AlonsoCagi** [Heroic-Games-Launcher/HeroicGamesLauncher#906] opened 2022-01-15 07:45 UTC
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

In the Store area of the launcher, trying to log in through my Epic account so I can claim free games and/or buy games, it shows an error if the Captcha is correct:

Incorrect response. Please refresh the page.

**To Reproduce**

1. Go to the Store section of the launcher.
2. Click on Sign in, choose Epic account.
3. Enter credentials and solve Captcha.
4. See error.

**Expected behavior**
Complete login to manage my Epic account from Heroic.

**Desktop (please complete the following information):**

- OS: Windows 10
- Heroic Version: Latest from Winget
- Hardware specs (RAM, CPU, GPU): i7 7700HQ, 16GB RAM, 1050ti

Any ideas?

**Comment by cspack77** [comment] 2022-01-15 20:56
Same issue here. I was able to login using the SID option as a workaround.

**Comment by StaringWhere** [comment] 2022-01-16 07:48
Same

**Comment by StaringWhere** [comment] 2022-01-16 08:07
I solved this problem by turning off the VPN. Hope this helps.

**Comment by flavioislima** [comment] 2022-01-16 11:25
> I solved this problem by turning off the VPN. Hope this helps.

So you were able to login with SID or using the epic login?

**Comment by StaringWhere** [comment] 2022-01-16 12:24
> > I solved this problem by turning off the VPN. Hope this helps.
> 
> So you were able to login with SID or using the epic login?

Both way works after turning off the VPN.

**Comment by cspack77** [comment] 2022-01-16 19:49
Tried with and without VPN, makes no difference for me.

**Comment by catalyst1987** [comment] 2022-01-16 22:57
I have the same issue.  I am using the launcher on Kubuntu.  Get "Incorrect response.  Please refresh the page." and then gives me an ID number.  I don't get prompted to do a captcha nor am I using a VPN.  Happens when trying to login with Epic Games account.  Haven't tried any other account methods.

**Comment by pholostan** [comment] 2022-01-17 21:45
I have this issue too, doesn't matter what I input as email or password, the hCaptcha always sends me back with the message "Incorrect response. Please refresh page." and an ID.

I can log into the store just fine in a web browser.

**Comment by Nocccer** [comment] 2022-01-17 21:47
There will be a fix in the next version. For me logging in with google worked. You can still logging in via sid for now.

**Comment by AlonsoCagi** [comment] 2022-01-18 04:23
I'm not sure if the title is too generic, but I meant as @pholostan says. There's no issue logging in via SID and sync the account with Heroic. The issue is that if I want to log in to the STORE section of Heroic via my Epic account, the embedded web browser won't let me do it even if the hCaptcha is correct. I'd like to add that if I click on the accessibility option of hCaptcha during this process, they close immediately. I checked with the debug option and it shows something to do with NoScript. I'm no programmer, but maybe that's the root of the problems?

**Comment by Maltavius** [comment] 2022-01-19 22:53
Installed on Arch today, 
The ordinary e-mail Epic login doesn't work, SID does.

**Comment by flavioislima** [comment] 2022-01-20 08:29
If you guys have time, test the version from our latest build that has the fix:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1705072468

**Comment by marhmm** [comment] 2022-01-20 17:44
The new version fixed the problem for me, thanks!

**Comment by qwertfisch** [comment] 2022-01-20 23:37
Trying to login with the SID does not work with either the latest build nor the current release 2.0.2. Heroic keeps redirecting me to „Login with Epic“ page. For security reasons I did not try to login there.

**Comment by Zorrototo** [comment] 2022-01-23 15:07
Trying your AppImage build, I don't have a Captcha error, it goes further, but after entering the 2FA code, I have an error popup https://i.imgur.com/EDkQAr2.jpg then when I click the OK button, it was hanging on Loading Library with the spinning icon, after a moment as it was not loading, I clicked on the left side on the Sign In menu link, the menu changed, I was logged in, I clicked Store, I was auto logged in the Store, and noticed I was also logged in the Heroic client (bottom left side with my user name).

I nuked every Heroic folder in my Home before trying this AppImage for info.

I tried to buy one of the Free Games, it worked (with the usual Device Not Supported message before buying it).

**Comment by derrod** [comment] 2022-01-23 15:56
That's a curious error, since it appears that the SID exchange in Legendary fails. But I'm not sure what would cause that. I cannot reproduce it either when logging in normally. I wonder if there's something that invalidates the SID obtained from the embedded browser or something.

**Comment by Zorrototo** [comment] 2022-01-23 16:11
I tried again, started the AppImage, logged out, then logged in with my Epic credentials, put the 2FA code, and it logged me in right away, loaded the library instantly this time, and then I got the error popup again, but it still seems to work properly.

https://i.imgur.com/G2Cienf.jpg

**Comment by flavioislima** [comment] 2022-01-23 16:28
> That's a curious error, since it appears that the SID exchange in Legendary fails. But I'm not sure what would cause that. I cannot reproduce it either when logging in normally. I wonder if there's something that invalidates the SID obtained from the embedded browser or similar.

Its happening because, for some reason, after the first login (that is successful), Heroic re-renders the State(since the user state was changed), but this is so fast that is making it heroic to call Legendary with the same SID again. So actually the error is from a second login trial.

so I need to figure it out how to do not cause a re-render of the GlobalState on Login. But for now I will just skip this error message dialog and keep it on console only.

**Comment by Zorrototo** [comment] 2022-01-23 16:33
Don't know if you saw but in this AppImage version, after closing Heroic, the tray icon doesn't close, and non of its menu item do anything (Close, Debut, Show, none work, I had to kill processes for it to vanish).

**Comment by derrod** [comment] 2022-01-24 08:32
Ah that would explain it, SIDs are one-time use only.

**Comment by Zorrototo** [comment] 2022-01-24 08:46
Looking forward to a new release to reinstall and continue to use it as an AUR package :+1:

**Comment by flavioislima** [comment] 2022-02-06 15:01
Fixed since v2.1

**Closed by flavioislima** 2022-02-06 15:01 UTC
Labels: issue:investigating

**Comment by gazhay** [comment] 2022-02-08 12:16
Just downloaded latest version today as heroic prompted me to.

Hitting this bug. Unable to login via epic login or sid.

**Comment by gazhay** [comment] 2022-02-08 12:29
Closing the appimage and relaunching worked.

**Comment by neod3v** [comment] 2022-09-01 09:46
i have the same issue in v2.4.1
```bash
$ heroic --enable-logging
(12:41:33) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
[14420:0901/124133.076349:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[14452:0901/124134.168742:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
(12:41:34) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:41:34) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:41:34) INFO:    [Backend]:         

Heroic Version: 2.4.1 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Artix KERNEL: 5.19.4-artix1-1 ARCH: x64
CPU: AMD Ryzen 5 5600H with Radeon Graphics @2.92 GOVERNOR: schedutil
RAM: Total: 7.12 GiB Available: 3.61 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3050 Laptop GPU VRAM: 3910MB DRIVER: 470.141.03 GPU1: Cezanne VRAM: 512MB DRIVER:  
PROTOCOL: x11

(12:41:34) INFO:    [Backend]:         User Not Found, removing it from Store
APPIMAGE env is not defined, current application is not an AppImage
(12:41:34) WARNING: [Backend]:         Protocol already registered.
[14420:0901/124134.279387:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[14420:0901/124134.279446:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[14420:0901/124134.279472:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(12:41:34) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(12:41:34) INFO:    [Backend]:         Checking for new Heroic Updates
(12:41:37) INFO:    [Backend]:         Downloaded Winetricks
[14420:0901/124150.156841:INFO:CONSOLE(2)] "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'is_installed')", source: file:///opt/Heroic/resources/app.asar/build/static/js/main.1f4de093.js (2)
[14676:0901/124158.452846:WARNING:media_session.cc(949)] RED codec red is missing an associated payload type.
[14676:0901/124231.536960:WARNING:media_session.cc(949)] RED codec red is missing an associated payload type.
[14420:0901/124235.089528:INFO:CONSOLE(1)] "Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' static-assets-prod.epicgames.com static-assets-prod.unrealengine.com". Either the 'unsafe-inline' keyword, a hash ('sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
", source: https://www.epicgames.com/id/api/redirect (1)
[14420:0901/124236.504237:INFO:CONSOLE(2)] "logging epic", source: file:///opt/Heroic/resources/app.asar/build/static/js/main.1f4de093.js (2)
(12:42:36) INFO:    [Legendary]:       Logging in with Legendary.
(12:42:36) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(12:42:38) INFO:    [Frontend]:        Refreshing Library
(12:42:38) INFO:    [Legendary]:       Refreshing library...
[14420:0901/124238.674144:INFO:CONSOLE(2)] "refreshing", source: file:///opt/Heroic/resources/app.asar/build/static/js/main.1f4de093.js (2)
(12:42:38) INFO:    [Frontend]:        No cache found, getting data from legendary...
(12:42:38) INFO:    [Legendary]:       Refreshing library...
```

**Comment by MatthewMSaucedo** [comment] 2022-11-09 01:07
Hitting this issue - neither standard login, nor SID login work. Relaunched and retried several times; login is as expected in Web Browser.

OS: Fedora 36
Heroic version: heroic-2.3.9-1.x86_64

**Comment by arielj** [comment] 2022-11-09 03:39
login is broken on versions older than 2.4.3, that's why it was not working and it worked after reinstall (you probably installed 2.4.3)

**Comment by ObscenityIB** [comment] 2025-03-21 04:04
This is happening for me too, even after trying the alternate method, which succeeds, I am still not logged in.
Not sure what this "SID" is that others are talking about, I see no such option.

**Comment by arielj** [comment] 2025-03-21 12:13
> Not sure what this "SID" is that others are talking about, I see no such option.

`SID` is an old thing that doesn't exist anymore, this thread if really old, from when `SID` was a thing, the current workflow uses the `code` for authentication

**Comment by hackadelic** [comment] 2025-03-31 18:58
I am able to get logged in but in the store for GOG, i get "Failed to challenge captcha, please try again later." not sure how to fix this, i the other parts seem to work but i cannot check out or claim anything anymore
