### ISSUE TITLE
Cannot login to epic games store

### ISSUE THREAD

**Issue by Mikaka27** [Heroic-Games-Launcher/HeroicGamesLauncher#3808] opened 2024-06-07 18:59 UTC
### Describe the bug

When opening epic games store section in heroic, I get a popup prompting me to login. After I click the popup, the window goes blank and nothing happens.

### Add logs

```text
(20:53:44) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:53:44) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(20:53:44) INFO:    [Connection]:       Connectivity: check-online
(20:53:44) INFO:    [Connection]:       Pinging external endpoints
(20:53:44) INFO:    [Gog]:              Checking for existing gog manifests
(20:53:45) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(20:53:45) WARNING: [Backend]:          Failed to register protocol with OS.
(20:53:45) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(20:53:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(20:53:45) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(20:53:45) INFO:    [Connection]:       Connectivity: online
(20:53:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:53:45) INFO:    [Backend]:          User Not Found, removing it from Store
(20:53:45) INFO:    [Gog]:              Checking if login is valid
(20:53:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:53:45) INFO:    [Backend]:          
System Information:
CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600K
Memory: 33.41 GB (used: 10.07 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Red Devil RX 6700 XT
    IDs: D=73df V=1002 SD=2409 SV=148c
    Driver: amdgpu
  GPU 1:
    Name: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770]
    IDs: D=a780 V=8086 SD=7d96 SV=1462
    Driver: i915
OS: Manjaro Linux 6.9.2-1-MANJARO (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(20:53:45) INFO:    [Frontend]:         Refreshing undefined Library
(20:53:45) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(20:53:45) INFO:    [Legendary]:        Refreshing library...
(20:53:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:53:45) INFO:    [Backend]:          Frontend Ready
(20:53:45) INFO:    [Backend]:          Checking for current version changelog
(20:53:45) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(20:53:45) INFO:    [Gog]:              Getting GOG library
(20:53:45) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:53:45) INFO:    [Gog]:              Saved username to config file
(20:53:46) INFO:    [Gog]:              Saved games data
(20:53:46) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(20:53:46) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mikaka/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(20:53:46) INFO:    [Gog]:              Found 0 game(s) to update
(20:53:47) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:53:47) INFO:    [Winetricks]:       Downloading Winetricks
(20:53:50) INFO:    [WineDownloader]:   Updating wine versions info
(20:53:50) INFO:    [WineDownloader]:   Fetching upstream information...
(20:53:50) INFO:    [WineDownloader]:   wine versions updated
(20:53:50) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I should be able to login.

### Screenshots

![obraz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9214100/b5c62f85-a437-4780-91aa-5195692a9f14)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]: Manjaro linux

**Comment by arielj** [comment] 2024-06-07 19:06
Duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3739

Use the `Manage Accounts` sidebar link until the next release

**Closed by arielj** 2024-06-07 19:06 UTC
Labels: bug:unconfirmed
