### ISSUE TITLE
vkd3d-proton installation fails

### ISSUE THREAD

**Issue by Leopard1907** [Heroic-Games-Launcher/HeroicGamesLauncher#1995] opened 2022-11-05 22:00 UTC
### Describe the bug

New vkd3d-proton (2.7) is not installable within heroic, toggling auto install vkd3d-proton ends up with this:

`(00:51:48) ERROR:   [DXVKInstaller]:   error when installing DXVK, please try launching the game again Error: Command failed: PATH=/home/asus/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin:$PATH WINEPREFIX='/home/asus/Games/Heroic/Prefixes/Control' bash /home/asus/.config/heroic/tools/vkd3d/vkd3d-proton-2.7.tar.xz/setup*.sh install --symlink
bash: /home/asus/.config/heroic/tools/vkd3d/vkd3d-proton-2.7.tar.xz/setup*.sh: No such file or directory
`

### Add logs

[heroic-2022-11-05T21_51_26.078Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9944768/heroic-2022-11-05T21_51_26.078Z.log)

### Steps to reproduce

1. Go to 'any installed game page'
2. Click on 'auto update vkd3d'
3. Notice nothing happens ( no prefix update/operation at all )

### Expected behavior

Being able to use it

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: heroic-games-launcher-bin 2.4.3-2 from AUR

**Comment by flavioislima** [comment] 2022-11-06 15:30
For me it works fine both on Kubuntu and SteamOS.
Maybe remove the tools folder from. config/heroic folder and restart heroic.

**Comment by Leopard1907** [comment] 2022-11-09 10:45
@flavioislima CommandMC also experiences the same issue. No, deleting tools dir doesn't help.

Changing downloaded vkd3d version directory name from `vkd3d-proton-2.7` to `vkd3d-proton-2.7.tar.xz` helps as it looks for .tar.xz for some reason.

**Comment by redromnon** [comment] 2022-11-11 12:19
> Changing downloaded vkd3d version directory name from vkd3d-proton-2.7 to vkd3d-proton-2.7.tar.xz helps as it looks for .tar.xz for some reason.

I can confirm this issue on my side too. Using Pop OS 22.04.

**Comment by flavioislima** [comment] 2022-11-14 10:30
This extraction issue was because the vkd3d on bottles repo changed the extension of the package, from .gz to .xz. Should be fixed by #2020 

Maybe we should start hosting our own packages to avoid these issues.

**Comment by xPakrikx** [comment] 2022-11-14 10:40
More work but looks like best solution.

**Comment by flavioislima** [comment] 2022-12-04 00:15
Fixed

**Closed by flavioislima** 2022-12-04 00:15 UTC
