### ISSUE TITLE
Unable to Install Extra Features After Initial Install

### ISSUE THREAD

**Issue by ZaxLofful** [Heroic-Games-Launcher/HeroicGamesLauncher#3090] opened 2023-09-28 02:08 UTC
### Describe the bug

After Fortnite is installed, you are unable to change/update the install options (such as DirectX12). It requires you to uninstall the game and reinstall everything to get the HD textures or the DirectX12 shaders.

I should be able to just right-click the game and install these extra features.

### Add logs

```text
(01:43:47) INFO:    [Legendary]:        Legendary location: C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary
(01:43:47) INFO:    [Gog]:              GOGDL location: C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\gogdl
(01:43:47) INFO:    [Connection]:       Connectivity: check-online
(01:43:47) INFO:    [Connection]:       Pinging external endpoints
(01:43:47) INFO:    [Nile]:             Refreshing library...
(01:43:47) INFO:    [Nile]:             Refreshing Amazon Games...
(01:43:47) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:43:48) INFO:    [Nile]:             Game list updated, got 0 games
(01:43:48) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2512.1"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(01:43:48) INFO:    [Legendary]:        installed.json updated, refreshing library
(01:43:48) WARNING: [Backend]:          Protocol already registered.
(01:43:48) ERROR:   [Backend]:          failed to update Error: ENOENT: no such file or directory, open 'C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app-update.yml'
(01:43:48) INFO:    [Connection]:       Connectivity: online
(01:43:48) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(01:43:49) INFO:    [Backend]:          Loading Screen Ready
(01:43:50) INFO:    [Nile]:             Saved user data to config file
(01:43:50) INFO:    [Backend]:          Checking for new Heroic Updates
(01:43:50) INFO:    [Frontend]:         Refreshing undefined Library
(01:43:50) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(01:43:50) INFO:    [Legendary]:        Refreshing library...
(01:43:50) INFO:    [Legendary]:        Refreshing Epic Games...
(01:43:50) INFO:    [Nile]:             Refreshing library...
(01:43:50) INFO:    [Nile]:             Refreshing Amazon Games...
(01:43:50) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:43:50) INFO:    [Nile]:             Game list updated, got 0 games
(01:43:50) INFO:    [Legendary]:        Game list updated, got 66 games & DLCs
(01:43:50) INFO:    [Backend]:          Frontend Ready
(01:43:50) INFO:    [Backend]:          VCRuntime is installed
(01:43:50) INFO:    [Backend]:          Checking for current version changelog
(01:43:50) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(01:43:50) INFO:    [Gog]:              Found 0 game(s) to update
(01:43:50) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(01:43:51) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(01:43:53) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary --version
(01:43:53) INFO:    [Gog]:              Running command: C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\<user>\AppData\Roaming\heroic\gog_store\auth.json --version
(01:43:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile --version
(01:43:54) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(01:43:54) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(01:43:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(01:43:54) INFO:    [Legendary]:        Getting more details with 'legendary info'
(01:43:54) INFO:    [Legendary]:        Found 0 games to update
(01:43:54) INFO:    [Nile]:             Looking for updates...
(01:43:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile list-updates --json
(01:43:54) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary info Fortnite --json --platform Windows
(01:43:54) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary info Fortnite --json --platform Windows
(01:43:55) INFO:    [Backend]:          Starting the Download Queue
(01:43:55) INFO:    [Legendary]:        Getting Info from Epic API
(01:43:57) INFO:    [Backend]:          
System Information:
CPU: 32x AMD Ryzen 9 3950X 16-Core Processor            
Memory: 137.34 GB (used: 7.95 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA102 [GeForce RTX 3080 12GB]
    IDs: D=220a V=10de SD=4877 SV=3842
    Driver: 537.42
  GPU 1:
    Name: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]
    IDs: D=1b06 V=10de SD=6390 SV=3842
    Driver: 537.42
OS: Microsoft Windows 10 Home 10.0.19045 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(01:43:57) INFO:    [Frontend]:         No cache found, getting data from nile...
(01:43:57) INFO:    [Nile]:             Refreshing library...
(01:43:57) INFO:    [Nile]:             Refreshing Amazon Games...
(01:43:57) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:43:57) INFO:    [Nile]:             Game list updated, got 0 games
(01:43:57) INFO:    [Legendary]:        Getting more details with 'legendary info'
(01:43:57) INFO:    [Legendary]:        Getting more details with 'legendary info'
(01:43:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary info Fortnite --json --platform Windows
(01:43:57) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary info Fortnite --json --platform Windows
(01:44:07) INFO:    [Backend]:          Launching Fortnite (Fortnite)
(01:44:07) INFO:    [Backend]:          Preventing display from sleep
(01:44:07) INFO:    [Backend]:          Preventing machine to sleep
(01:44:07) DEBUG:   [Legendary]:        Using cached install info
(01:44:07) INFO:    [Backend]:          Stopping Power Saver Blocker
(01:44:07) DEBUG:   [Legendary]:        Using cached install info
(01:44:07) DEBUG:   [Legendary]:        Using cached install info
(01:44:07) DEBUG:   [Legendary]:        Using cached install info
(01:44:07) INFO:    [Backend]:          Started Discord Rich Presence
(01:44:07) INFO:    [Legendary]:        Launching Fortnite: HEROIC_APP_NAME=Fortnite HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary launch Fortnite --language en
(01:44:11) INFO:    [Backend]:          Stopped Discord Rich Presence
(01:44:11) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(01:44:11) INFO:    [Frontend]:         Refreshing legendary Library
(01:44:11) INFO:    [Legendary]:        Refreshing library...
(01:44:11) INFO:    [Legendary]:        Refreshing Epic Games...
(01:44:11) INFO:    [Legendary]:        Game list updated, got 68 games & DLCs
(01:44:11) INFO:    [Frontend]:         No cache found, getting data from nile...
(01:44:11) INFO:    [Nile]:             Refreshing library...
(01:44:11) INFO:    [Nile]:             Refreshing Amazon Games...
(01:44:11) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:44:11) INFO:    [Nile]:             Game list updated, got 0 games
(01:44:11) DEBUG:   [Legendary]:        Using cached install info
(01:44:11) INFO:    [Frontend]:         Force Update
(01:44:11) DEBUG:   [Legendary]:        Using cached install info
(01:44:11) DEBUG:   [Legendary]:        Using cached install info
(01:44:11) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(01:44:38) INFO:    [Frontend]:         Refreshing undefined Library
(01:44:38) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(01:44:38) INFO:    [Legendary]:        Refreshing library...
(01:44:38) INFO:    [Legendary]:        Refreshing Epic Games...
(01:44:38) INFO:    [Nile]:             Refreshing library...
(01:44:38) INFO:    [Nile]:             Refreshing Amazon Games...
(01:44:38) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:44:39) INFO:    [Nile]:             Game list updated, got 0 games
(01:44:39) INFO:    [Legendary]:        Game list updated, got 68 games & DLCs
(01:44:39) INFO:    [Frontend]:         No cache found, getting data from nile...
(01:44:39) INFO:    [Nile]:             Refreshing library...
(01:44:39) INFO:    [Nile]:             Refreshing Amazon Games...
(01:44:39) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:44:39) INFO:    [Nile]:             Game list updated, got 0 games
(01:44:39) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(01:52:47) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary --version
(01:52:47) INFO:    [Gog]:              Running command: C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\<user>\AppData\Roaming\heroic\gog_store\auth.json --version
(01:52:48) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile --version
(01:52:48) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(01:52:54) INFO:    [Frontend]:         Refreshing undefined Library
(01:52:54) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(01:52:54) INFO:    [Legendary]:        Refreshing library...
(01:52:54) INFO:    [Legendary]:        Refreshing Epic Games...
(01:52:54) INFO:    [Nile]:             Refreshing library...
(01:52:54) INFO:    [Nile]:             Refreshing Amazon Games...
(01:52:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:52:54) INFO:    [Nile]:             Game list updated, got 0 games
(01:52:54) INFO:    [Legendary]:        Game list updated, got 68 games & DLCs
(01:52:54) INFO:    [Frontend]:         No cache found, getting data from nile...
(01:52:54) INFO:    [Nile]:             Refreshing library...
(01:52:54) INFO:    [Nile]:             Refreshing Amazon Games...
(01:52:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\nile_config C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\nile library sync
(01:52:54) INFO:    [Nile]:             Game list updated, got 0 games
(01:52:55) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\<user>\AppData\Roaming\heroic\legendaryConfig C:\Users\<user>\AppData\Local\Temp\2VKxOEiq76HtNhvDWqFz12OpuDE\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(01:52:59) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(01:52:59) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Fortnite
(01:52:59) DEBUG:   [Legendary]:        Using cached install info
(01:52:59) DEBUG:   [Legendary]:        Using cached install info
```

### Steps to reproduce

1. Install Fornite with default options
2. Right-click Fornite icon
3. No option to install additional features

### Expected behavior

Right-clicking should give a menu (maybe under settings) that allows the user to add the additional parts for Fortnite like HD Textures and DLC single player content.

### Heroic Version

Latest Stable

### System Information

Windows 10

### Additional information

This works on Epic Launcher

1. Right-click Fornite and select options
2. Change the extra features and languages whenever you want

**Comment by flavioislima** [comment] 2023-09-29 18:42
Sorry but this is not currently supported by Heroic or Legendary, we have feature requests to add that already so might be implemented in the future.

**Comment by ZaxLofful** [comment] 2023-10-02 05:33
I would be happy to help with this, can you point me to the place in the code I could start with this?

**Comment by arielj** [comment] 2023-11-04 15:27
Closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2694

Any conversation can be continued there

**Closed by arielj** 2023-11-04 15:27 UTC
Labels: bug:unconfirmed
