### ISSUE TITLE
Heroic will not launch - error bwrap: Can't make symlink at /home/user/Documents: File exists

### ISSUE THREAD

**Issue by navennn** [Heroic-Games-Launcher/HeroicGamesLauncher#2966] opened 2023-08-07 13:55 UTC
### Describe the bug

Hi
Since last update, heroic launcher doesn't launch

`user@pc:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl @@u %u @@
bwrap: Can't make symlink at /home/user/Documents: File exists`

I have a symlink from Documents to my nextcloud share. 

`user@pc:~$ ls -lh /home/user/Documents
lrwxrwxrwx 1 user user 20 Jul 14 19:51 /home/user/Documents -> Nextcloud/Documents/`

`flatpak list
Name                             Application ID                                      Version                Branch                Installation
Heroic Games Launcher            com.heroicgameslauncher.hgl                         v2.9.1                 stable                system
`

I've had this symlink for like a month and I ran Heroic successfully before. Is this even related? It seems to me that it's pointless for Heroic to create symlink for /home/user/Documents - it would exist on any other system as a directory already. 
Can I bypass this somehow?
Thanks!

### Add logs

```text
$ cat .var/app/com.heroicgameslauncher.hgl/config/heroic/logs/heroic-2023-08-07T13_29_30.569Z.log
(15:29:30) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:29:30) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:29:30) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:29:30) INFO:    [Connection]:       Connectivity: check-online
(15:29:30) INFO:    [Connection]:       Pinging external endpoints
(15:29:30) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(15:29:30) INFO:    [Connection]:       Connectivity: online
(15:29:30) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(15:29:31) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.2.0-26-generic ARCH: x64
CPU: Intel Gen Intel® Core™ i7-13700K @4.43 GOVERNOR: powersave
RAM: Total: 31.1 GiB Available: 23 GiB
GRAPHICS: GPU0: Device a780  VRAM: 256MB GPU1: Device 744c VRAM: 1MB 
PROTOCOL: wayland

(15:29:31) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "updated",
    "version": "4.10.2557.0"
  }
}
(15:29:31) INFO:    [Gog]:              Checking if login is valid
(15:29:31) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:29:31) WARNING: [Backend]:          Failed to register protocol with OS.
(15:29:31) INFO:    [Backend]:          Loading Screen Ready
(15:29:31) INFO:    [Frontend]:         Refreshing undefined Library
(15:29:31) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:29:31) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:29:31) INFO:    [Legendary]:        Refreshing library...
(15:29:31) INFO:    [Legendary]:        Refreshing Epic Games...
(15:29:31) INFO:    [Legendary]:        Game list updated, got 153 games & DLCs
(15:29:31) INFO:    [Gog]:              Getting GOG library
(15:29:31) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:29:31) INFO:    [Backend]:          Frontend Ready
(15:29:31) INFO:    [Backend]:          Checking for current version changelog
(15:29:31) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(15:29:31) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(15:29:31) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:29:32) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:29:33) INFO:    [Gog]:              Saved games data
(15:29:33) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:29:33) INFO:    [Gog]:              Found 0 game(s) to update
(15:29:33) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:29:33) INFO:    [Gog]:              Saved username to config file
(15:29:33) INFO:    [Winetricks]:       Downloading Winetricks
(15:29:35) INFO:    [Legendary]:        Found 0 games to update
(15:29:35) INFO:    [Frontend]:         Force Update
(15:29:36) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Run either from CLI or menu.
2. It won't launch, error can be seen in CLI, GUI does nothing and provides no error message.

### Expected behavior

GUI launches 

### Heroic Version

Latest Stable

### System Information

Kubuntu 23.03

**Comment by imLinguin** [comment] 2023-08-07 13:57
duplicate of #2944

**Closed by imLinguin** 2023-08-07 13:57 UTC
Labels: bug:unconfirmed
