### ISSUE TITLE
Legendary throws an error after logging into Epic account

### ISSUE THREAD

**Issue by HarGabt** [Heroic-Games-Launcher/HeroicGamesLauncher#2713] opened 2023-05-17 14:55 UTC
### Describe the bug

Legendary after logging in into Epic account throws an error that says `An error has occurred! Try to Logout and Login on your Epic account.`. Logging out and back in does not help.

<details>
  <summary>Error text</summary>

An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* A Total War Saga: TROY (App name: 11e598b192324994abce05bad4f81b50 | Version: 16581.2782747)
* Absolute Drift (App name: 19927295d6e3467887d4e830d8c85963 | Version: Win_202305111447)
* ABZU (App name: Curry | Version: 1.0)
* Alien: Isolation (App name: 8935bb3e1420443a9789fe01758039a5 | Version: 1.0RC5.284847.51533)
* Amnesia: The Dark Descent (App name: ece4c58603d04bcb97454be9a7492fa6 | Version: 1.5)
* Among Us (App name: 963137e4c29d4c79a81323b8fab03a40 | Version: 2830)
* Blair Witch (App name: 247a0f0f5803429eb3be2c06f3ea77ff | Version: BLAIR_WIN_SRC_20191209_1642)
* Borderlands 2 (App name: Dodo | Version: 2.0.2_BN347_CL2863302)
* Borderlands: The Pre-Sequel (App name: Turkey | Version: 2.0.2_BN160_CL2863302)
* Control (App name: Calluna | Version: 01.13)
* Crying Suns (App name: 18fafa2d70d64831ab500a9d65ba9ab8 | Version: 3.0.0.18-WIN64)
* Dead by Daylight (App name: Brill | Version: DBD_Live_EGS_Shipping_165_1191440_6.7.1.3)
* DOOM 64 (App name: 5b60142e120c4f2d88027595c21d4a04 | Version: 2124)
* Fall Guys (App name: 0a2d9f6403244d12969e11da6713137b | Version: EGS_3530)
* Fallout 3: Game of the Year Edition (App name: adeae8bbfc94427db57c7dfecce3f1d4 | Version: 1.11)
* Fortnite (App name: Fortnite | Version: ++Fortnite+Release-24.40-CL-25420516-Windows)
* Genshin Impact (App name: 41869934302e4b8cafac2d3c0e7c293d | Version: 69)
* Ghostbusters The Video Game Remastered (App name: Mint | Version: retail10)
* Grand Theft Auto V (App name: 9d2d0eb64d5c44529cece33fe2a46482 | Version: 1.0.2845.0_v1)
* HITMAN (App name: Barbet | Version: 4226454)
* HITMAN 3 (App name: Eider | Version: 6782587)
+ HITMAN 1 Complete First Season (App name: 4145c668a0c94f1db16de2cbfbc60309 | Version: 7)
+ HITMAN 1 GOTY Upgrade (App name: addd421d0f1d4573914f915a697054de | Version: 7)
* Hue (App name: Herring | Version: 1.0)
* Just Cause 4 (App name: Kakopo | Version: JC4_2226912_1830540)
* Killing Floor 2 (App name: Finch | Version: 484021-2023_03_01_04h58m30s)
* KillingFloor2Beta (App name: 3223ccf6ac9b4189bd4e144c047d33fb | Version: 493681-2023_05_04_21h47m20s)
* Lifeless Planet: Premier Edition (App name: 860a4feefe2a4f48905ae86c61d5db64 | Version: 1.0.0)
* Metro 2033 Redux (App name: Petunia | Version: 0.1.0.0)
* Metro Last Light Redux (App name: Speedwell | Version: 0.1.0.0)
* NBA 2K21 (App name: 639977eecfd2497c941b71af949b5067 | Version: 1.12.135040)
* Rage 2 (App name: ad3d0f08dd0841d8a1ba77d94ded4773 | Version: 1.8)
* Rocket League� (App name: Sugar | Version: BC2_Update42+419576)
* Saints Row The Third Remastered (App name: Loon | Version: SRTTR_20211028_epic_14th_patch)
* Shadow of the Tomb Raider: Definitive Edition (App name: 890d9cf396d04922a1559333df419fed | Version: TR11_16122022_489.0_1227353_740629_133157100100236396_)
* Shadowrun Hong Kong (App name: 41470cb5755440b8b55ec3f94351133a | Version: 1.0.0)
* Shadowrun Returns (App name: dc29cb42f32e4a17af1d68c715fa459c | Version: 1.0.0)
* Shadowrun: Dragonfall - Director�s Cut (App name: 5b41454974be4d5883056ba298e53675 | Version: 1.0.0)
* Sid Meier's Civilization VI (App name: Kinglet | Version: 1.0.12.899997c_nebraska_england_RTM_Kinglet)
+ Civilization VI : Aztec DLC (App name: KingletAztec | Version: 1.0.12.899997c_nebraska_england_RTM_KingletAztec)
* Sludge Life (App name: Morganite | Version: V201003)
* STAR WARS� Battlefront� II: Celebration Edition (App name: MtMassive | Version: None)
— This game has to be activated, installed, and launched via Origin, use "legendary launch --origin MtMassive" to activate and/or run the game.
* The Escapists 2 (App name: Fowl | Version: 0.24)
* Trackmania (App name: Pigeon | Version: 1.3)
— This game can be activated directly on your Ubisoft account and does not require legendary to install/run. Use "legendary activate --uplay" and follow the instructions.
* Train Sim World 2 (App name: dd75b5c168d546cc869582c0389f0a1d | Version: 1.0.182)
* Watch Dogs (App name: Jasper | Version: 1.0)
— This game can be activated directly on your Ubisoft account and does not require legendary to install/run. Use "legendary activate --uplay" and follow the instructions.

Orphaned DLCs:
- DLCs for 16268e7a56184fada899a673ab14260a:
+ Bakerloo Line (App name: 5d31a6c96b204613b17d690ca88cf9f9 | Version: 1.0.5)
+ Sand Patch Grade (App name: 098b530746fa4cfb8b11484bfdc18a2d | Version: 1.0.2)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 272, in list_games
File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 24: character maps to <undefined>
[14560] Failed to execute script 'cli' due to unhandled exception!

</details>

### Add logs

```text
(18:38:08) INFO:    [Legendary]:        Refreshing library...
(18:38:08) INFO:    [Connection]:       Connectivity: check-online
(18:38:08) INFO:    [Connection]:       Pinging external endpoints
(18:38:08) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(18:38:09) INFO:    [Legendary]:        Legendary location: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(18:38:09) INFO:    [Gog]:              GOGDL location: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(18:38:09) INFO:    [Gog]:              GOGDL location: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(18:38:09) WARNING: [Backend]:          Protocol already registered.
(18:38:09) INFO:    [Connection]:       Connectivity: online
(18:38:09) INFO:    [Backend]:          User Not Found, removing it from Store
(18:38:09) INFO:    [Gog]:              Checking if login is valid
(18:38:09) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json auth
(18:38:09) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json --version
(18:38:10) INFO:    [Backend]:          Loading Screen Ready
(18:38:10) INFO:    [Frontend]:         Refreshing Library
(18:38:10) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:38:10) INFO:    [Gog]:              Found 0 game(s) to update
(18:38:10) INFO:    [Backend]:          Frontend Ready
(18:38:10) INFO:    [Backend]:          VCRuntime is installed
(18:38:10) INFO:    [Frontend]:         No cache found, getting data from legendary...
(18:38:10) INFO:    [Legendary]:        Refreshing library...
(18:38:10) INFO:    [Backend]:          Checking for new Heroic Updates
(18:38:10) INFO:    [Backend]:          Checking for current version changelog
(18:38:10) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(18:38:10) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary cleanup
(18:38:10) INFO:    [Gog]:              Saved username to config file
(18:38:13) INFO:    [Backend]:          

Heroic Version: 2.7.1 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Майкрософт Windows 11 Домашняя для одного языка KERNEL: 10.0.22621 ARCH: x64
CPU: Intel Gen Intel® Core™ i9-11900KF @3.5 
RAM: Total: 31.9 GiB Available: 17.7 GiB
GRAPHICS: GPU0: AMD Radeon RX 6700 XT VRAM: 12272MB 


(18:38:15) INFO:    [Backend]:          Starting the Download Queue
(18:38:42) INFO:    [Legendary]:        Logging in: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --code <redacted>
(18:38:43) INFO:    [Frontend]:         Refreshing Library
(18:38:43) INFO:    [Legendary]:        Refreshing library...
(18:38:43) INFO:    [Legendary]:        Refreshing Epic Games...
(18:38:43) ERROR:   [Legendary]:        Failed to parse MtMassive.json
(18:38:43) INFO:    [Legendary]:        Game list updated, got 48 games & DLCs
(18:38:43) INFO:    [Frontend]:         No cache found, getting data from legendary...
(18:38:43) INFO:    [Legendary]:        Refreshing library...
(18:38:43) INFO:    [Legendary]:        Refreshing Epic Games...
(18:38:43) ERROR:   [Legendary]:        Failed to parse MtMassive.json
(18:38:43) INFO:    [Legendary]:        Game list updated, got 48 games & DLCs
(18:38:43) INFO:    [Frontend]:         Force Update
(18:38:44) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:38:44) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:38:48) INFO:    [Frontend]:         Refreshing Library
(18:38:48) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:38:48) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json auth
(18:38:48) INFO:    [Legendary]:        Refreshing library...
(18:38:48) INFO:    [Legendary]:        Refreshing Epic Games...
(18:38:48) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(18:38:49) INFO:    [Gog]:              Getting GOG library
(18:38:49) INFO:    [Gog]:              Number of library pages: 1
(18:38:49) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json auth
(18:38:50) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:38:50) INFO:    [Gog]:              Saved games data
(18:38:50) INFO:    [Frontend]:         Force Update
(18:38:50) INFO:    [Frontend]:         Refreshing Library
(18:38:50) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:38:50) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json auth
(18:38:50) INFO:    [Legendary]:        Refreshing library...
(18:38:50) INFO:    [Legendary]:        Refreshing Epic Games...
(18:38:50) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(18:38:50) INFO:    [Gog]:              Getting GOG library
(18:38:51) INFO:    [Gog]:              Number of library pages: 1
(18:38:51) INFO:    [Gog]:              Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\galoy\AppData\Roaming\heroic\gog_store\auth.json auth
(18:38:51) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:38:52) INFO:    [Gog]:              Saved games data
(18:39:13) INFO:    [Legendary]:        Logging out: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --delete
(18:39:13) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary cleanup
(18:39:13) INFO:    [Frontend]:         Refreshing Library
(18:39:13) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(18:39:13) INFO:    [Gog]:              Found 0 game(s) to update
(18:39:13) INFO:    [Frontend]:         No cache found, getting data from legendary...
(18:39:13) INFO:    [Legendary]:        Refreshing library...
(18:39:14) INFO:    [Backend]:          Checking for new Heroic Updates
(18:39:14) INFO:    [Backend]:          Checking for current version changelog
(18:39:49) INFO:    [Legendary]:        Logging in: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --code <redacted>
(18:39:50) INFO:    [Frontend]:         Refreshing Library
(18:39:50) INFO:    [Legendary]:        Refreshing library...
(18:39:50) INFO:    [Legendary]:        Refreshing Epic Games...
(18:39:50) ERROR:   [Legendary]:        Failed to parse MtMassive.json
(18:39:50) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(18:39:50) INFO:    [Frontend]:         No cache found, getting data from legendary...
(18:39:50) INFO:    [Legendary]:        Refreshing library...
(18:39:50) INFO:    [Legendary]:        Refreshing Epic Games...
(18:39:50) ERROR:   [Legendary]:        Failed to parse MtMassive.json
(18:39:50) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(18:39:50) INFO:    [Frontend]:         Force Update
(18:39:51) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(18:39:51) INFO:    [Legendary]:        Running command: C:\Users\galoy\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
```

### Steps to reproduce

1. Log into your Epic account
2. Apparently, have games that require DRM different from EGS (EA App (Origin), Ubisoft Connect (Uplay))
3. Wait around 5 seconds
4. Get error and see error

### Expected behavior

No error or an explanation how to work around it.

### Screenshots

![изображение](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/44652400/bcac9d22-a442-4449-85ce-5958b395572c)

### Heroic Version

Latest Stable

### System Information

- OS: Windows 11 Home Single Language

### Additional information

Using Heroic 2.7.1

**Comment by bergamin** [comment] 2023-05-28 02:39
The error I'm getting is similar, but not quite the same:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/14339291/87588b30-ac7a-49d7-8843-5c98f5f782b7)

Tried logging off and back on and still doesn't work

**Comment by arielj** [comment] 2023-05-28 04:22
> The error I'm getting is similar, but not quite the same:
> 
> ![image](https://user-images.githubusercontent.com/14339291/241471017-87588b30-ac7a-49d7-8843-5c98f5f782b7.png)
> 
> Tried logging off and back on and still doesn't work

you can ignore this error, it's a data issue on epic's servers, it should be fixed once epic fixes it on their end

it only prevents you from installing one of the fallout dlcs, other than that it has no other impact

**Comment by bergamin** [comment] 2023-05-28 16:13
@arielj, first time it happened, it prevented me from updating Genshin Impact and removed all Epic games from the list. Logged off and on again and then I was able to update it, even with the error and now I can play it.

From what you say, could this be caused by Fallout New Vegas that I added to my library recently? Has this issue been around for long? Even if it doesn't affect other games, this is kinda annoying. I hope they fix this soon...

**Comment by arielj** [comment] 2023-05-28 17:34
I don't when the problem started (a DLC was added to the epic database with an invalid value), it does start for most people because of the free new vegas game that includes that DLC

it affects the official launcher too so I imagine they'll fix it soon

**Comment by OnlyPlayy** [comment] 2023-05-29 20:55
I get this error litteraly every day on my steam deck. Whenever I want to run Epic game it asks me if I want to download it, where in Desktop mode im logged out from epic games and I have to log in again like tge day before, and like I will have to tommorow.

**Comment by Jolonte** [comment] 2023-06-18 18:30
Same here, furthermore logout and login doesn't work. One thing that works is try to play the game, get the error, reboot the computer, try to play again, get the same error but now I can login and play the game I want.

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/66970818/62461df4-2cdf-4073-95c9-55cda6e6d2b0)

**Comment by dmig** [comment] 2023-06-30 11:02
This is my error:
```
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* A Short Hike (App name: d6407c9e6fd54cb492b8c6635480d792 | Version: 1.9_v3_Windows)
* Adios (App name: 73c56a1f38a548b2852ce8608c5e436e | Version: 1.0.0.11)
* Alba - A Wildlife Adventure (App name: 8a0173bbe3ac48ac903f5bc7277e7b4e | Version: 1.2.4)
* Among the Sleep - Enhanced Edition (App name: aa78f7be2ee64193b6b6444c5fc50157 | Version: Windows.3.1.0.41_Win64_DLL_Fix)
* Ancient Enemy (App name: a96de508ac71471fa05e7c1c695e3b5d | Version: 1.03fix)
* Anodyne 2: Return to Dust (App name: Tanzanite | Version: Win_1.32)
* Assassins Creed Syndicate (App name: Albacore | Version: 1.54)
- This game can be activated directly on your Ubisoft account and does not require legendary to install/run. Use "legendary activate --uplay" and follow the instructions.
* Automachef (App name: 069a60f6b0514a5fbe81b38957c1ddfd | Version: 15)
* Aztez (App name: Grunt | Version: 1.2-aeeb6200374fc01a6a51c3006846a350febeb243.21-Win)
* Beyond Blue (App name: 3a0cae9455844390ad00505a704d641e | Version: 1.7.17766)
* Black Widow: Recharged (App name: a21fd90517bf428eb7c995a8c3261722 | Version: 5)
* Bloons TD 6 (App name: 7786b355a13b47a6b3915335117cd0b2 | Version: 37.3.6721)
* Borderlands 3 (App name: Catnip | Version: 1.0.23_CL_2860060_Borderlands_3)
* Breathedge (App name: 0a20ccd3f1b3464da750a4dbf8c80d7c | Version: 1.0.1.1)
* Brothers - A Tale of Two Sons (App name: Tamarind | Version: 1.1)
* Call of the Sea (App name: 6278dd278d714aeb88239a423fa0f8be | Version: 1.5.4.10)
* Carcassonne (App name: Thrush | Version: 1.10.2967-win)
* Centipede Recharged (App name: 8727e9d0693542bda60769dc2ce33c20 | Version: 4)
* Chess Ultra (App name: fc0b13b7b17b4a46933756fb2786cdc4 | Version: MWLocal_13)
* Cities Skylines (App name: bcbc03d8812a44c18f41cf7d5f849265 | Version: 1.17.1-f4-fixed)
* City of Gangsters (App name: 002b00085aeb49b1a3f3c42e3f918f2f | Version: 1.4.3.5)
* Control (App name: Calluna | Version: 01.13)
* Costume Quest 2 (App name: 82a78a4dd6ef4eaa892707791b705073 | Version: 1)
* Dark Deity (App name: e21be436768f4add87d4935a180b4932 | Version: 1.58)
* Darkwood (App name: 923130ebb546417b9d3115507f752d34 | Version: 1)
* Dead by Daylight (App name: Brill | Version: DBD_Live_EGS_Shipping_178_1262239_7.0.2.2)
* Death Stranding (App name: Boga | Version: 2742586.206.1)
* Death Stranding Content (App name: 5bf67f3153364181b54cb9e40ca7fa82 | Version: 1.01)
+ DEATH STRANDING DIGITAL SOUNDTRACK (App name: 84067e3ec8f149b2bbf2342d7a136065 | Version: 1.02)
+ HD Wallpaper (App name: f8bf1e29bbef480a9b28115ad0d644a0 | Version: 1.02)
+ SELECTIONS OF TITAN ART BOOK (App name: c311b22f878749449886949eeb588999 | Version: 1.01)
* Defense Grid: The Awakening (App name: a434dcb20f0d439b93aaa31dac9e3210 | Version: 1.263117)
* Dishonored - Definitive Edition (App name: d2da64bd4c4e422da4b1a88041492a3a | Version: 1.6)[cli] INFO: Logging in...[Core] INFO: Logging in...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in main
File "legendary/cli.py", line 239, in list_games
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 13: ordinal not in range(128)[135] Failed to execute script 'cli' due to unhandled exception!
```

Version 2.8.0 running on Stem Deck

**Comment by lucsoft** [comment] 2023-07-15 12:55
Getting the same error

**Comment by Visne** [comment] 2023-07-17 18:32
For me this only happened on the Flatpak version, after installing from the AUR it stopped happening.

**Comment by dmig** [comment] 2023-07-18 01:59
Good for you @Visne. The problem is: thousands of Steam Deck users have to use flatpak version.

**Comment by Visne** [comment] 2023-07-19 17:44
I wasn't implying that people should just install the normal version, but I was stating it because it might help fix the issue (and it could be a workaround for people that are able to install the normal version).

**Comment by DrDoorknob** [comment] 2023-07-27 12:04
Just saw this as well. If it helps at all, here is my complete library on there:

- shapez
- Tunche
- The Silent Age
- Evil Dead: The Game
- Darkest Dungeon®
- The Long Dark
- Pillars of Eternity - Definitive Edition
- Railway Empire
- Where The Water Tastes Like Wine
- Into the Breach
- Torchlight II
- Grand Theft Auto V: Premium Edition
- Paragon
- Shadow Complex Remastered
- Unreal Tournament

**Comment by dmig** [comment] 2023-07-27 12:06
Just updated to 2.9.0 -- started getting this error more often

**Comment by arielj** [comment] 2023-11-04 15:28
Can you check with Heroic 2.10.0? we updated Legendary

**Comment by HarGabt** [comment] 2023-11-04 17:04
@arielj Just installed 2.10.0 — haven't got such error, so far so good

**Comment by arielj** [comment] 2023-11-04 17:05
thanks, I'll close the issue then for now unless somebody else still has the problem

**Closed by arielj** 2023-11-04 17:05 UTC
Labels: issue:investigating

**Comment by Kisty** [comment] 2023-11-05 21:14
Getting same issue after updating to 2.10.0
