### ISSUE TITLE
Blank screen when launching Heroic

### ISSUE THREAD

**Issue by cracrayol** [Heroic-Games-Launcher/HeroicGamesLauncher#2604] opened 2023-04-06 09:03 UTC
### Describe the bug

Hi. After I've updated Heroic to 2.7.0, I've got, several times, a blank screen when launching Heroic (see steps to reproduce). Closing it and restart it fix the problem but reacts slowly during the first 30s. During this time, it's seems downloading the cover for my GOG Games (~300 games). Once downloaded, Heroic run smoothly.

Can you check this ? Thx.

### Add logs

```text
(10:41:57) INFO:    [Connection]:       Connectivity: check-online
(10:41:57) INFO:    [Connection]:       Pinging external endpoints
(10:41:57) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:41:58) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:41:58) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:41:58) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:41:58) WARNING: [Backend]:          Protocol already registered.
(10:41:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cracrayol/.config/heroic/gog_store/auth.json --version
(10:41:58) INFO:    [Connection]:       Connectivity: online
(10:41:58) INFO:    [Gog]:              Getting data about the user
(10:41:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/cracrayol/.config/heroic/gog_store/auth.json auth
(10:41:58) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:41:58) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: LinuxMint KERNEL: 5.19.0-38-generic ARCH: x64
CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
RAM: Total: 15.55 GiB Available: 11.98 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 525.89.02
PROTOCOL: x11

(10:41:58) INFO:    [Backend]:          Loading Screen Ready
(10:41:58) INFO:    [Backend]:          Checking for new Heroic Updates
(10:41:58) ERROR:   [Frontend]:         Error: G is not iterable
(10:41:58) INFO:    [Backend]:          Checking for current version changelog
(10:41:59) INFO:    [Gog]:              Saved user data to config
(10:42:00) INFO:    [Winetricks]:       Downloading Winetricks
```

### Steps to reproduce

1. Launch Heroic and close it.
2. Change the system date to d+1
3. Lauch Heroic
4. Empty screen

### Expected behavior

Having the library displayed each time I launch Heroic.

### Screenshots

![Capture d’écran du 2023-04-09 11-02-15](https://user-images.githubusercontent.com/18292463/230328980-5c0bd651-bcb7-4671-8677-a5c6333ebff5.png)

### Heroic Version

Latest Stable

### System Information

- OS: LinuxMint KERNEL: 5.19.0-38-generic ARCH: x64
- CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
- RAM: Total: 15.55 GiB Available: 11.98 GiB
- GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 525.89.02
- PROTOCOL: x11

**Comment by jdgleaver** [comment] 2023-04-06 13:08
I also experience this. Moreover, while Heroic is apparently 'hanging' with a black screen, it is constantly recreating the file `~/.config/heroic/store_cache/gog_api_info.json`. I checked this with strace and iotop, and while regenerating this file Heroic will write to disk at a rate of approximately 150MB/s (on a fast SDD), leading to total writes of 10s of gigabytes of data. To mitigate SSD wear I have moved the `~/.config/heroic/store_cache` directory to a tmpfs mount while Heroic is running...

**Comment by asmaloney** [comment] 2023-04-06 16:10
Just experienced this on macOS 12.6.4.

I didn't change the date as in the original steps to reproduce. I just started it and it gave me a blank window. Restarted it and it loaded fine.

I only have Epic - no GOG.

**Comment by Dandraghas** [comment] 2023-04-06 17:05
i Have same issue, and looks like this issue is somehow releated to:
 `(19:38:32) ERROR:   [Frontend]:         Error: G is not iterable`

i have very small gog library but very big in epic games. and everything releated to frontend just doesn't work. nothing is happening just blank screen.

this issue happens randomly, without changing time, rebooting, etc.

**Comment by Gamertech** [comment] 2023-04-07 00:34
Same issue after updating to 2.7.0 flatpak on Fedora.

First launch of Heroic results in a blank window and disk usage. Closing and reloading results in only the Epic library being shown for ~10 seconds before GoG shows up. After that, it works as normal.

**Comment by Nocccer** [comment] 2023-04-07 12:32
If someone can reproduce it, toggle the debug button in the tray icon.
In the chrome inspect tool select console and paste the output here.

**Comment by CoolPenguin27** [comment] 2023-04-09 02:54
Can confirm this happens to me on Kubuntu (22.10, Flatpak). I also don't use gog.
![Screenshot_20230409_195012](https://user-images.githubusercontent.com/108895116/230751619-9dec14c5-c07a-4240-b4a1-a83660188e18.png)

**Comment by mihalycsaba** [comment] 2023-04-14 20:41
> If someone can reproduce it, toggle the debug button in the tray icon. In the chrome inspect tool select console and paste the output here.
> 
```
index.2d952428.js:835 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at R7.componentDidMount (index.2d952428.js:835:32635)
index.2d952428.js:41 TypeError: G is not iterable
    at App.7a7ff29b.js:200:39917
    at Object.useMemo (index.2d952428.js:39:25876)
    at pe.useMemo (index.2d952428.js:9:6208)
    at App.7a7ff29b.js:200:39702
    at nd (index.2d952428.js:39:19536)
    at Fc (index.2d952428.js:41:3159)
    at s0 (index.2d952428.js:41:2365)
    at oh (index.2d952428.js:41:1898)
    at P0 (index.2d952428.js:41:47662)
    at E0 (index.2d952428.js:41:40015)
Dc @ index.2d952428.js:41
index.2d952428.js:41 Uncaught TypeError: G is not iterable
    at App.7a7ff29b.js:200:39917
    at Object.useMemo (index.2d952428.js:39:25876)
    at pe.useMemo (index.2d952428.js:9:6208)
    at App.7a7ff29b.js:200:39702
    at nd (index.2d952428.js:39:19536)
    at Fc (index.2d952428.js:41:3159)
    at s0 (index.2d952428.js:41:2365)
    at oh (index.2d952428.js:41:1898)
    at P0 (index.2d952428.js:41:47662)
    at E0 (index.2d952428.js:41:40015)
```

**Comment by Nocccer** [comment] 2023-04-16 16:39
I might fixed it. I only was able to reproduce this for flatpak build so it was harder to debugging this.
Here is a flatpak build if you wanna test by yourself: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/12268843956/artifacts/649663121

**Comment by bjwest** [comment] 2023-04-16 19:11
Thank you @Nocccer, that fixed the problem for me.

**Comment by stuart-bowyer** [comment] 2023-04-18 13:59
I can confirm this also on my Steam Deck, I guess its similar to my other bug #2632

**Comment by Mundball** [comment] 2023-04-21 13:04
On Debian 11 with deb package i have the same issue, only GOG.
Issue is on every start, reload does solve the problem, very anoying.

`index.2d952428.js:835 refreshing
index.2d952428.js:41 TypeError: F is not iterable
    at App.7a7ff29b.js:200:39922
    at Object.useMemo (index.2d952428.js:39:25876)
    at pe.useMemo (index.2d952428.js:9:6208)
    at App.7a7ff29b.js:200:39702
    at nd (index.2d952428.js:39:19536)
    at Fc (index.2d952428.js:41:3159)
    at s0 (index.2d952428.js:41:2365)
    at oh (index.2d952428.js:41:1898)
    at P0 (index.2d952428.js:41:47662)
    at E0 (index.2d952428.js:41:40015)
Dc @ index.2d952428.js:41
index.2d952428.js:41 Uncaught TypeError: F is not iterable
    at App.7a7ff29b.js:200:39922
    at Object.useMemo (index.2d952428.js:39:25876)
    at pe.useMemo (index.2d952428.js:9:6208)
    at App.7a7ff29b.js:200:39702
    at nd (index.2d952428.js:39:19536)
    at Fc (index.2d952428.js:41:3159)
    at s0 (index.2d952428.js:41:2365)
    at oh (index.2d952428.js:41:1898)
    at P0 (index.2d952428.js:41:47662)
    at E0 (index.2d952428.js:41:40015)`

**Comment by Alvarden15** [comment] 2023-04-23 17:39
Windows 10 user. Can confirm this happens to me too. First time starting it shows blank. Only when i close it and open again shows the library again.
![Heroic_jIOh1XOjIH](https://user-images.githubusercontent.com/31715989/233855646-b8ddd9c0-21f5-4f15-b574-6c7860bfb977.png)

**Comment by freecoderai01** [comment] 2023-04-26 12:21
I can confirm it is happening on Arch using [this build](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.7.0/heroic-2.7.0.pacman)
Using only epicgames.
```
(13:58:16) INFO:    [Backend]:          Loading Screen Ready
(13:58:16) INFO:    [Backend]:          Checking for new Heroic Updates
(13:58:16) ERROR:   [Frontend]:         [Error: G is not iterable]
(13:58:16) INFO:    [Backend]:          Checking for current version changelog
```

**Comment by saepurusass** [comment] 2023-04-27 08:02
I can confirm it too, Running Debian,  heroic_2.7.0_amd64.deb package.  
I have only epic account (71 games).  No gog account/games, so probably not gog account related issue.  

Every day I start my computer, the first launch is blank screen.  
Close heroic and start it again, and it works without any issues I have noticed.  

Just logging off and on again does not trigger it for me.  
Just restarting computer does not trigger it for me.  
It might be related to time passed since last start (or close time). It if exceeds some time, it triggers.  
It's bit pain to debug if you have only one shot to try it and then have to wait quite while before it happens again.  

Random guess: Could it be something so simple as expired cookie handled bad?

**Comment by Gamertech** [comment] 2023-04-27 22:41
No point guessing. This issue has already been fixed by Nocccer in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2612

It's just waiting for review and merging.

**Closed** 2023-04-28 07:24 UTC
Labels: bug:confirmed

**Comment by XxKingBadxX** [comment] 2026-02-23 23:51
Im had the same issue, GOG game on Heroic launcher, black screen hang at launch.

Resolution: changed launch setting from wine to proton GE, disable UMU (advanced tab) and use dx11 not 12!
had to do all 3 for mine to work, have fun guys!
