### ISSUE TITLE
Games with fsync and esync enabled do not launch under 2.14

### ISSUE THREAD

**Issue by sjp760** [Heroic-Games-Launcher/HeroicGamesLauncher#3670] opened 2024-04-02 02:43 UTC
### Describe the bug

If I launch a game under 2.14 using proton experimental bleeding-edge, I need to disable fsync and esync in order to get it to work. If I run the game using the "run exe using prefix option" in the settings the game works as intended, even with fsync and esync enabled. No wineserver processes are running at all

### Add logs

```text
======================
Proton: 1711988843 experimental-bleeding-edge-9.0-88661-20240401-pfa9684-w253576-d855b27-v21008d
SteamGameId: heroic-Fallout New Vegas
Command: ['/home/user/Games/Heroic/Prefixes/default/Fallout New Vegas Ultimate Edition/pfx/drive_c/Modding/MO2/ModOrganizer.exe']
Options: {'forcelgadd', 'disablenvapi'}
depot: 0.20240321.82093
pressure-vessel: 0.20240321.0 scout
scripts: 0.20240321.0
sniper: 0.20240321.82093 sniper 0.20240321.82093
Kernel: Linux 6.8.1-1-default #1 SMP PREEMPT_DYNAMIC Tue Mar 19 07:32:20 UTC 2024 (d922afa) x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
System WINEDLLOVERRIDES: winemenubuilder.exe=d
Effective WINEDLLOVERRIDES: winemenubuilder.exe=d
System WINEDEBUG: timestamp
Effective WINEDEBUG: timestamp
======================
  0.000:011c:err:fsync:fsync_init Failed to open fsync shared memory file; make sure no stale wineserver instances are running without WINEFSYNC.
```

### Steps to reproduce

Double check that fsync and esync is enabled and then launch the game using proton.

### Expected behavior

The game should run normally with fsync and esync on.

### Heroic Version

Latest Stable

### System Information

CPU: 12x AMD Ryzen 5 5600 6-Core Processor
Memory: 16.67 GB (used: 5.86 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate]
    IDs: D=2504 V=10de SD=3656 SV=3842
    Driver: nvidia
OS: openSUSE Tumbleweed 6.8.1-1-default (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.0 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

**Comment by duderand** [comment] 2024-04-02 21:13
I encountered a similar issue but with the default proton 8.x, the game would not start. After finding this issue I disabled fsync and esync and the game then started as before.

**Comment by LordChaos73** [comment] 2024-04-02 21:55
What DE are you using? Did you also notice performance degradation?

**Comment by jorgicio** [comment] 2024-04-02 23:13
The same, games are only working if esync and disable are disabled when using Proton.
I don't have this issue when using Wine.

**Comment by CountMurphy** [comment] 2024-04-03 01:18
Same issue here. Running XFCE in Arch Linux. Disabling esync and fsync does get the game to launch, but the performance is so bad its unplayable (5-10fps where I was getting 60 before). Downgraded to 2.13 and everything is running smooth again.

**Comment by Emurikku** [comment] 2024-04-03 07:04
Hi, 

Confirmed on Steam Deck with "Raji".
And I get audio stutter too.

**Comment by kaniggl** [comment] 2024-04-03 11:37
have/had the same issue, when upgrading heroic flatpack from 2.13 to 2.14 on nobara linux.
fixed it with downgrade to 2.13.

**Comment by stuart-bowyer** [comment] 2024-04-03 19:00
Same issue here on the Deck, when I disabled esync and fsync then the game launched. Using Valves Proton 8 and seems to only occur with GOG games for me

**Comment by mikilopez** [comment] 2024-04-03 20:24
Same here.

Yesterday I was playing a game (Islets, from Epic Store), no issues. Today I updated to 2.14, and the game doesn't run.
If I disable Fsync and ESync, the game runs again. Haven't experienced any performance issue, but the game is quite light for my hardware.

System: Manjaro Mate 1.26.2 (kernel 6.6.19), using Proton-8.25-GE.
Ryzen 5 7600 with RX 580.

**Comment by korewaChino** [comment] 2024-04-04 09:37
Can confirm. Reproducible on Flatpak

**Comment by GitUp1234** [comment] 2024-04-04 20:30
Same here, but so far only when trying to launch Risen from GOG with Proton (e.g. Proton 8.0 or Proton-GE-latest). After switching to Wine-GE-Proton8-25 game launches with no issue. Also doesn't affect games from Epic store (e.g. Batman Arkham City or Fallout New Vegas launch with no issue).
Heroic 2.14.0 "Flame Emperor Sabo" installed as Flatpak
Linux Mint 21.2, Cinnamon 5.8.4
Kernel 6.5.0-26-generic
Ryzen 5 5600 
Radeon RX 6600

**Comment by scroll44** [comment] 2024-04-05 07:02
For me the game is Dishonored 2 from Epic. I use heroic.rpm.

**Comment by stuart-bowyer** [comment] 2024-04-06 05:21
So I can confirm that going back to 2.13 fixes the issue. I used the following guide on my Deck https://www.linuxfordevices.com/tutorials/linux/downgrade-flatpak-packages

This not a fun bug for sure

**Comment by flavioislima** [comment] 2024-04-06 13:04
Just released a new version, this issue should be fixed now.

If it won't, please reopen the issue.

Thanks

**Closed by flavioislima** 2024-04-06 13:04 UTC
Labels: bug:unconfirmed

**Comment by jorgicio** [comment] 2024-04-06 19:04
Just tried here and it looks like the issue is fixed. Thank you!
