### ISSUE TITLE
desktop and start menu shortcuts not created (kde plasma)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1588] opened 2022-07-17 15:29 UTC
### Describe the bug

I enabled the options to create a start menu shortcut and desktop shortcut automatically, but they are not created (same thing for the steam shortcut)

### Add logs

```
(11:20:49) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:20:50) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary
(11:20:50) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:20:50) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.12-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 4700U with Radeon Graphics @2 GOVERNOR: schedutil
RAM: Total: 15 GiB Available: 7.43 GiB
GRAPHICS: GPU0: gfx90c:xnack- VRAM: 512MB DRIVER:  
PROTOCOL: wayland

(11:20:50) INFO:    [Gog]:             Getting data about the user
(11:20:50) INFO:    [Gog]:             Refreshing access_token
(11:20:51) WARNING: [Backend]:         Protocol already registered.
(11:20:51) INFO:    [Gog]:             Token refreshed successfully
(11:20:51) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(11:20:52) INFO:    [Gog]:             Saved user data to config
(11:20:52) INFO:    [Frontend]:        Refreshing Library
(11:20:52) INFO:    [Legendary]:       Refreshing library...
(11:20:52) INFO:    [Legendary]:       Refreshing Epic Games...
(11:20:52) INFO:    [Gog]:             Getting GOG library
(11:20:53) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary list
(11:20:53) INFO:    [Gog]:             Number of library pages: 1
(11:20:53) INFO:    [Gog]:             Saved games data
(11:20:53) INFO:    [Legendary]:       Updating game list
(11:20:53) INFO:    [Legendary]:       Game List Updated
(11:20:54) INFO:    [Legendary]:       Checking for game updates.
(11:20:54) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:20:54) INFO:    [Backend]:         Downloaded Winetricks
(11:20:54) INFO:    [Legendary]:       Found 0 game(s) to update
(11:20:55) INFO:    [Gog]:             Found 0 game(s) to update
(11:21:09) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:21:09) INFO:    [Gog]:             Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(11:21:09) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise
(11:21:09) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise
(11:21:09) WARNING: [Legendary]:       EOS Overlay is not installed in default location, permission issues might arise
(11:21:12) INFO:    [Legendary]:       Updating EOS Overlay information: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary status
(11:21:24) INFO:    [Backend]:         Writing config for Heroic
(11:21:24) INFO:    [Backend]:         {
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "addDesktopShortcuts": true,
  "addStartMenuShortcuts": true,
  "autoInstallDxvk": true,
  "autoInstallVkd3d": true,
  "preferSystemLibs": false,
  "customWinePaths": [
    "/home/etaash/Documents/GitHub/wine-valorant/build64/wine"
  ],
  "defaultInstallPath": "/home/etaash/Games/Heroic",
  "defaultSteamPath": "/home/etaash/.steam/steam",
  "defaultWinePrefix": "/home/etaash/Games/Heroic/Prefixes",
  "disableController": false,
  "discordRPC": true,
  "egsLinkedPath": "",
  "enableEsync": true,
  "exitToTray": true,
  "maxRecentGames": 5,
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "showMangohud": true,
  "showUnrealMarket": false,
  "useGameMode": false,
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/etaash/.wine",
  "wineVersion": {
    "bin": "/usr/sbin/wine",
    "name": "Wine Default - wine-7.7 (Staging)",
    "type": "wine",
    "wineserver": "/usr/sbin/wineserver",
    "wineboot": "/usr/sbin/wineboot"
  },
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(11:21:28) DEBUG:   [Legendary]:       Using cached install info
(11:21:28) DEBUG:   [Legendary]:       Using cached install info
(11:21:30) INFO:    [Backend]:         Writing config for Peony
(11:21:30) INFO:    [Backend]:         {
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": true,
  "enableEsync": false,
  "enableFsync": true,
  "maxSharpness": 2,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "savesPath": "",
  "showFps": false,
  "showMangohud": true,
  "targetExe": "",
  "useGameMode": false,
  "useSteamRuntime": false,
  "language": "",
  "winePrefix": "/home/etaash/Games/Heroic/Prefixes/TheEscapists",
  "wineCrossoverBottle": "Heroic"
}
(11:21:30) DEBUG:   [Legendary]:       Using cached install info
(11:21:30) INFO:    [Legendary]:       Installing Peony: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary install Peony --platform Windows --base-path /home/etaash/Games/Heroic --skip-dlcs --skip-sdl -y
(11:21:30) DEBUG:   [Legendary]:       Logging to file "/home/etaash/.config/heroic/GamesConfig/Peony.log"
(11:21:31) INFO:    [Legendary]:       Progress for Peony: 0%/0.00MiB/00:00:00
(11:21:32) INFO:    [Legendary]:       Progress for Peony: 22.69%/41.06MiB/00:00:01
(11:21:33) INFO:    [Legendary]:       Progress for Peony: 47.68%/86.29MiB/00:00:01
(11:21:34) INFO:    [Legendary]:       Progress for Peony: 73.84%/133.64MiB/00:00:00
(11:21:35) INFO:    [Legendary]:       Progress for Peony: 99.51%/180.10MiB/00:00:00
(11:21:36) INFO:    [Legendary]:       Progress for Peony: 100%/180.98MiB/00:00:00
(11:21:37) INFO:    [Legendary]:       Installed game list updated
(11:21:37) INFO:    [Legendary]:       Installed game list updated
(11:21:37) INFO:    [Backend]:         finished installing
(11:21:37) INFO:    [Backend]:         operation interrupted
(11:21:38) INFO:    [Frontend]:        Refreshing Library
(11:21:38) INFO:    [Legendary]:       Refreshing library...
(11:21:38) INFO:    [Legendary]:       Updating game list
(11:21:38) INFO:    [Legendary]:       Game List Updated
(11:21:38) INFO:    [Legendary]:       Checking for game updates.
(11:21:38) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:21:39) INFO:    [Legendary]:       Found 0 game(s) to update
(11:25:38) INFO:    [Legendary]:       Uninstalling Peony: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary uninstall Peony -y
(11:25:39) INFO:    [Legendary]:       Installed game list updated
(11:25:39) INFO:    [Legendary]:       Installed game list updated
(11:25:39) INFO:    [Backend]:         Desktop shortcut removed
(11:25:39) INFO:    [Backend]:         Applications shortcut removed
(11:25:39) INFO:    [Shortcuts]:       The Escapists was successfully removed from Steam.
(11:25:39) INFO:    [Backend]:         Removing prefix /home/etaash/Games/Heroic/Prefixes/TheEscapists
(11:25:39) INFO:    [Backend]:         finished uninstalling
(11:25:39) INFO:    [Frontend]:        Refreshing Library
(11:25:39) INFO:    [Legendary]:       Refreshing library...
(11:25:39) INFO:    [Legendary]:       Updating game list
(11:25:39) INFO:    [Legendary]:       Game List Updated
(11:25:39) INFO:    [Legendary]:       Checking for game updates.
(11:25:39) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicYNw03K/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:25:40) INFO:    [Legendary]:       Found 0 game(s) to update

```

### Steps to reproduce

1. enable option to create start menu and desktop shortcuts
2. install a game
3. no shortcuts anywhere

### Expected behavior

a desktop, application, and steam shortcut should be created

### System Information

- OS arch linux
- Heroic Version: latest beta from pr #1587

**Comment by flavioislima** [comment] 2022-07-17 15:30
You are using the AppImage? I am not sure Shortcuts will work on AppImages.

**Comment by Nocccer** [comment] 2022-07-17 15:31
> You are using the AppImage? I am not sure Shortcuts will work on AppImages.

It will work if i refactor it. Add none steam game also works with AppImage.

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 15:32
> You are using the AppImage? I am not sure Shortcuts will work on AppImages.

yeah I was using the app image

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 15:43
> > You are using the AppImage? I am not sure Shortcuts will work on AppImages.
> 
> It will work if i refactor it. Add none steam game also works with AppImage.

add non steam game does not work with the app image for me

**Comment by Nocccer** [comment] 2022-07-17 15:45
> add non steam game does not work with the app image for me

The Escapist is not working on Linux, so it is more a issue with the game rather then the functionality of heroic.
Before you use the add shortcut and add to steam buttons, make sure the game runs from heroic directly!

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 15:48
> > add non steam game does not work with the app image for me
> 
> The Escapist is not working on Linux, so it is more a issue with the game rather than the functionality of heroic. Before you use the add shortcut and add to steam buttons, make sure the game runs from heroic directly!

oh I didn't know that (I'll try a different game), the game does launch though, it just crashes on the main menu for some reason

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 15:57
still not working after using a different game and running it

**Comment by Nocccer** [comment] 2022-07-17 15:58
> still not working after using a different game and running it

What does the log say? General Logs and Game Logs?

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 15:59
had to relaunch heroic because it didn't refresh something properly, so the log is split
[heroic-2022-07-17T15_20_48.950Z.log](https://github.co
[heroic-2022-07-17T15_50_17.582Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128015/heroic-2022-07-17T15_50_17.582Z.log)
m/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128014/heroic-2022-07-17T15_20_48.950Z.log)

**Comment by Nocccer** [comment] 2022-07-17 16:04
> had to relaunch heroic because it didn't refresh something properly, so the log is split [heroic-2022-07-17T15_20_48.950Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128016/heroic-2022-07-17T15_20_48.950Z.log) [heroic-2022-07-17T15_50_17.582Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128017/heroic-2022-07-17T15_50_17.582Z.log)

Try out wine-ge from our wine -manager. Also you need to check game logs. General logs look fine.

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 16:07
with wine ge
[Flounder-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128024/Flounder-lastPlay.log)

**Comment by Nocccer** [comment] 2022-07-17 16:13
> with wine ge [Flounder-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128024/Flounder-lastPlay.log)

Can't help here. Head over to our discord server and ask in linux channel for help.
I will close the ticket because it is not a bug in heroic. It is a problem to get a game running.

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 16:16
> > with wine ge [Flounder-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128024/Flounder-lastPlay.log)
> 
> Can't help here. Head over to our discord server and ask in linux channel for help. I will close the ticket because it is not a bug in heroic. It is a problem to get a game running.

the game works fine though?

**Comment by Nocccer** [comment] 2022-07-17 16:18
> > > with wine ge [Flounder-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128024/Flounder-lastPlay.log)
> > 
> > 
> > Can't help here. Head over to our discord server and ask in linux channel for help. I will close the ticket because it is not a bug in heroic. It is a problem to get a game running.
> 
> the game works fine though? it's an issue in litterally any game I install too, so its a bug in heroic

Can you provide a game log and general log if you run it trough steam?

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 16:20
> > > > with wine ge [Flounder-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9128024/Flounder-lastPlay.log)
> > > 
> > > 
> > > Can't help here. Head over to our discord server and ask in linux channel for help. I will close the ticket because it is not a bug in heroic. It is a problem to get a game running.
> > 
> > 
> > the game works fine though? it's an issue in litterally any game I install too, so its a bug in heroic
> 
> Can you provide a game log and general log if you run it trough steam?

that's the issue, it's not showing up on steam :/

**Comment by Nocccer** [comment] 2022-07-17 16:21
> that's the issue, it's not showing up on steam :/

Did you restarted steam? It is needed, else the steam never will show up. Steam only reads the shortcuts.vdf on startup.

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 16:56
> > that's the issue, it's not showing up on steam :/
> 
> Did you restarted steam? It is needed, else the game never will show up in steam. Steam only reads the shortcuts.vdf on startup.

yes I restarted it 4 times already lol

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 17:05
is it possible to re open this issue, because it's a heroic bug

**Comment by Nocccer** [comment] 2022-07-17 20:18
Yes but i need general logs.
If you add the game to steam you get a error message or a success message, that it was added to steam. I need that for a first guess. Also do you have multiple steam path? You can see what is the default in the general settings, advanced or others. Can't remember correctly imo.

**Comment by Etaash-mathamsetty** [comment] 2022-07-17 22:26
my steam path (I only have one version of steam installed)
`/home/etaash/.steam/steam`
I don't get any message that the game was added to steam or not, how do I manually add it?

**Comment by Nocccer** [comment] 2022-07-18 03:23
So you pressed the add to steam button on the gamepage > tools section? Btw this button is only present if you build the beta by yourselfs or downlaoded the latest appimage build from heroic actions. It is not available in the current beta or stable release.

**Comment by Etaash-mathamsetty** [comment] 2022-07-18 10:53
> So you pressed the add to steam button on the gamepage > tools section? Btw this button is only present if you build the beta branch by yourselfs or downlaoded the latest appimage build from heroic actions. It is not available in the current beta or stable release.
> 
> From the log i don't see any message from `[shortcuts]`

I built it myself with some patches applied to fix dualsense support and the patches from the pr I mentioned above, and I can't find this option, could you send a picture?

**Comment by Nocccer** [comment] 2022-07-18 11:25
> > So you pressed the add to steam button on the gamepage > tools section? Btw this button is only present if you build the beta branch by yourselfs or downlaoded the latest appimage build from heroic actions. It is not available in the current beta or stable release.
> > 
> > From the log i don't see any message from `[shortcuts]`
> 
> I built it myself with some patches applied to fix dualsense support and the patches from the pr I mentioned above, and I can't find this option, could you send a picture?
> edit: nvm found it
> edit: it works
> edit: desktop shortcut works, but no application shortcut

Yes the shortcuts are a little broken and i will refactor the backend soon.

**Comment by Etaash-mathamsetty** [comment] 2022-07-22 20:35
I tried this again with trackmaina and it seems to work fine, but since it needs a refactor anyway, I will leave this open

**Comment by arielj** [comment] 2022-10-19 04:02
This will be fixed in the next release, this PR is already merged https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1903

**Closed** 2022-10-19 16:09 UTC
