### ISSUE TITLE
[gog] WINEPREFIX is not set at all on macOS

### ISSUE THREAD

**Issue by NyaomiDEV** [Heroic-Games-Launcher/HeroicGamesLauncher#3084] opened 2023-09-26 23:56 UTC
### Describe the bug

While using macOS Sonoma with Game Porting Toolkit, I noticed that the wineprefix is the default ~/.wine, even if Heroic thinks it's not. This, obviously, is not noticeable if I run only a game, but it can be a problem really fast if I have multiple.

I don't know if this only applies to GOG games though.

I worked around it by explicitly setting the WINEPREFIX environment variable per-game.

### Add logs

```text
(01:20:02) INFO:    [Gog]:              Launching Cyberpunk 2077: HEROIC_APP_NAME=1423049311 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/naomi/Library/Application Support/heroic/gog_store/auth.json" launch "/Users/naomi/Games/Heroic/Cyberpunk 2077" --override-exe "/Users/naomi/Games/Heroic/Cyberpunk 2077/setup_redlauncher.exe" 1423049311 --wine /usr/local/Cellar/game-porting-toolkit/1.0.4/bin/wine64 --platform windows
```

### Steps to reproduce

1. Launch a (gog?) game with Game Porting Toolkit enabled.
2. See that the prefix Heroic meant to create is an empty folder.
3. See that ~/.wine now exists.

### Expected behavior

I'd expect every game to have its own wineprefix.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: macOS 14 Sonoma Final Release
- MacBook Pro 2021, M1 Pro

**Comment by arielj** [comment] 2023-10-01 23:16
Closing this as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3026

**Closed by arielj** 2023-10-01 23:16 UTC
Labels: bug:unconfirmed
