### ISSUE TITLE
Heroic 2.7.0 shows empty GOG and Epic libraries in offline mode, refuses to launch games

### ISSUE THREAD

**Issue by flytrapdev** [Heroic-Games-Launcher/HeroicGamesLauncher#2645] opened 2023-04-23 09:07 UTC
### Describe the bug

I'm using the Flatpak version of Heroic 2.7.0 on my Steam Deck.

After using the Steam Deck offline for a while, Heroic would not display any game in my GOG library.
The same thing happened to my Epic library shortly after.

Because of this, Steam shortcuts would no longer launch any game via Heroic.

I've heard of a "play offline" option in the game settings that would solve this issue, but it seems strange to me that Heroic would "forget" about my libraries when used offline, especially since all of the library json files (gog_store/library.json, gog_store/installed.json etc.) are still present in Heroic's config folder.

A workaround is to connect the Steam Deck to the internet and refresh both libraries, but this requires an internet connection.

This is related to issue #2606 

### Add logs

```text
(10:29:46) INFO:    [Connection]:       Connectivity: offline
(10:29:46) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:29:47) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:29:47) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:29:47) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:29:47) WARNING: [Backend]:          Failed to register protocol with OS.
(10:29:47) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(10:29:47) INFO:    [Backend]:          Loading Screen Ready
(10:29:47) INFO:    [Frontend]:         Refreshing Library
(10:29:47) INFO:    [Legendary]:        Refreshing library...
(10:29:47) INFO:    [Legendary]:        Found 0 games to update
(10:29:47) INFO:    [Backend]:          Frontend Ready
(10:29:47) INFO:    [Frontend]:         No cache found, getting data from legendary...
(10:29:47) INFO:    [Legendary]:        Refreshing library...
(10:29:47) INFO:    [Backend]:          Checking for current version changelog
(10:29:47) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(10:29:48) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @3.05 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 12.47 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(10:29:49) WARNING: [DXVKInstaller]:    App offline, skipping possible DXVK update.
(10:29:51) INFO:    [Connection]:       Connectivity: online
(10:29:51) INFO:    [Gog]:              Getting data about the user
(10:29:51) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:29:51) WARNING: [Backend]:          Failed download of AreWeAntiCheatYet data: Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com
(10:29:51) ERROR:   [Gog]:              No credentials, can't get user data
(10:29:52) INFO:    [Backend]:          Starting the Download Queue
(10:30:46) INFO:    [Frontend]:         Refreshing Library
(10:30:46) INFO:    [Legendary]:        Refreshing library...
(10:30:46) INFO:    [Legendary]:        Refreshing Epic Games...
(10:30:46) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(10:30:46) INFO:    [Legendary]:        Game list updated, got 37 games & DLCs
(10:30:46) ERROR:   [Backend]:          Failed to get epic service status with Error: getaddrinfo EAI_AGAIN status.epicgames.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
(10:30:46) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:30:46) INFO:    [Frontend]:         No cache found, getting data from legendary...
(10:30:46) INFO:    [Legendary]:        Refreshing library...
(10:30:46) INFO:    [Legendary]:        Game list updated, got 37 games & DLCs
(10:30:46) INFO:    [Frontend]:         Force Update
(10:32:31) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:32:31) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
```

### Steps to reproduce

1. Log on GOG and/or Epic in Heroic
2. Load appropriate libraries, install a few games and add shortcuts to Steam
3. Disable Wi-Fi on the Steam Deck
4. Reboot the Steam Deck

### Expected behavior

Steam game shortcuts should launch the appropriate game, and Heroic should still display GOG and Epic libraries.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: SteamOS 3.4.6

**Comment by arielj** [comment] 2023-04-23 12:46
I can confirm this, after a few days of being offline all the games disappeared. When I got internet connection back the games appeared without having to re-login so it was not an issue of credentials.

I think we are clearing the list of games at some point thinking the login is invalid when we shouldn't check that because we are offline

**Comment by blackmodjo** [comment] 2023-04-27 07:08
Same here, and even if you stay online the games list will disapear

**Comment by flavioislima** [comment] 2023-05-03 09:15
Fixed on 2.7.1

**Closed by flavioislima** 2023-05-03 09:15 UTC

**Comment by tmysik** [comment] 2024-04-09 08:07
This issue is back, version `2.14.1 Hotfix #1`.

**Comment by tmysik** [comment] 2024-04-09 08:31
Hmm, weird. Once I was back online, the games appeared again, and now they are present even if I am offline.

**Comment by Taranchul** [comment] 2025-08-15 11:36
Same here with Heroic 2.18.1 installed via Flatpak on Kubuntu 24.04. Without internet my library was empty (it has only GOG games), with internet again it was filled like before without having to do anything else.
