### ISSUE TITLE
EOS Overlay install does nothing 

### ISSUE THREAD

**Issue by Roccoriu** [Heroic-Games-Launcher/HeroicGamesLauncher#2935] opened 2023-07-30 02:03 UTC
### Describe the bug

Trying to install the EOS overlay doesn't do anything. I tried both the flatpak and the deb package, neither works. 

### Add logs

```text
(03:48:20) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:48:20) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(03:48:20) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(03:48:20) INFO:    [Connection]:       Connectivity: check-online

(03:48:20) INFO:    [Connection]:       Pinging external endpoints

(03:48:20) INFO:    [Backend]:          DRM module staus {

  "oimompecagnajdejgnnjijobebaeigek": {

    "name": "Widevine Content Decryption Module",

    "status": "new",

    "version": "4.10.2557.0"

  }

}

(03:48:20) WARNING: [Backend]:          Protocol already registered.

(03:48:20) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:48:20) INFO:    [Connection]:       Connectivity: online

(03:48:20) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present

(03:48:20) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(03:48:20) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:48:20) INFO:    [Backend]:          Loading Screen Ready

(03:48:20) INFO:    [Frontend]:         Refreshing undefined Library

(03:48:20) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(03:48:20) INFO:    [Legendary]:        Refreshing library...

(03:48:20) INFO:    [Legendary]:        Refreshing Epic Games...

(03:48:20) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs

(03:48:20) INFO:    [Backend]:          Frontend Ready

(03:48:20) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(03:48:20) INFO:    [Gog]:              Found 0 game(s) to update

(03:48:20) INFO:    [Backend]:          Checking for new Heroic Updates

(03:48:20) INFO:    [Backend]:          Checking for current version changelog

(03:48:20) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock

Legendary Version:  0.20.32 Dark Energy (hotfix #6)

GOGdl Version: 0.7.3

Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1

Chrome Version: 112.0.5615.204

NodeJS Version: 18.14.0

OS: Pop KERNEL: 6.2.6-76060206-generic ARCH: x64

CPU: AMD Ryzen 9 7950X 16-Core Processor @5.09 GOVERNOR: performance

RAM: Total: 61.95 GiB Available: 46.89 GiB

GRAPHICS: GPU0: Navi 21 [Radeon RX 6900 XT] VRAM: 1MB GPU1: Device 164e VRAM: 512MB 

PROTOCOL: x11

(03:48:20) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(03:48:20) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(03:48:21) INFO:    [Legendary]:        Found 0 games to update

(03:48:22) INFO:    [Winetricks]:       Downloading Winetricks

(03:48:24) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:48:24) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:48:24) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:48:25) INFO:    [Backend]:          Starting the Download Queue

(03:48:26) INFO:    [Legendary]:        Getting EOS Overlay install size: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/riu/.config/heroic/tools/eos_overlay

(03:48:26) INFO:    [Backend]:          Preventing machine to sleep

(03:48:27) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/riu/.config/heroic/tools/eos_overlay"

(03:48:58) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:48:58) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:48:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:49:19) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:49:19) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:49:19) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:51:29) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:51:29) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:51:29) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:52:39) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:52:39) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:52:39) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version

(03:53:35) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(03:53:35) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/riu/.config/heroic/gog_store/auth.json --version

(03:53:35) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/riu/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

### Steps to reproduce

1. Go to Settings
2. Go to Advanced
3. Click install on the EOS overlay. Nothing will happen

### Expected behavior

The EOS overlay should be installed as expected

### Screenshots

![Screenshot from 2023-07-30 03-58-18](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/25778176/2bc8c796-8f3c-45dc-9be3-d3376c60f341)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Pop!_OS 22.04 LTS x86_64
- Kernel:  6.2.6-76060206-generic
- CPU: AMD Ryzen 9 7950X
- GPU: AMD ATI Radeon RX 6900 XT
- DE: GNOME 42.5
- Windowing System: X11 (wayland was also tried)
- Heroic version: 2.9.1 (both .deb and flatpak were tried)

**Comment by arielj** [comment] 2023-07-30 04:27
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2916

you can use the workaround explained in that issue until we release a new version

**Closed by arielj** 2023-07-30 04:27 UTC
Labels: bug:unconfirmed
