### ISSUE TITLE
[only tested with cyberpunk] Static pop any time a sound effect plays 

### ISSUE THREAD

**Issue by Rain-Gayming** [Heroic-Games-Launcher/HeroicGamesLauncher#3866] opened 2024-07-16 21:57 UTC
### Describe the bug

When ever a sound effect plays theres a static-y pop sound on top of it, its really noticable when fighting, talking or driving.

### Add logs

```text
No log for this i dont think but:

(22:56:24) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:56:24) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:56:24) INFO:    [Connection]:       Connectivity: check-online
(22:56:24) INFO:    [Connection]:       Pinging external endpoints
(22:56:24) INFO:    [Gog]:              Checking for existing gog manifests
(22:56:24) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(22:56:25) WARNING: [Backend]:          Failed to register protocol with OS.
(22:56:25) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:56:25) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(22:56:25) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(22:56:25) INFO:    [Backend]:          Frontend Ready
(22:56:25) INFO:    [Backend]:          
System Information:
CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Memory: 33.6 GB (used: 9.99 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S]
    IDs: D=73ef V=1002 SD=5026 SV=1462
    Driver: amdgpu
OS: EndeavourOS 6.9.9-arch1-1 (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(22:56:25) INFO:    [Connection]:       Connectivity: online
(22:56:25) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rain/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:56:25) INFO:    [Backend]:          User Not Found, removing it from Store
(22:56:25) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:56:25) INFO:    [Backend]:          Checking for current version changelog
(22:56:26) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:56:27) INFO:    [Winetricks]:       Downloading Winetricks
(22:56:29) INFO:    [WineDownloader]:   Updating wine versions info
(22:56:29) INFO:    [WineDownloader]:   Fetching upstream information...
(22:56:30) INFO:    [Backend]:          Starting the Download Queue
(22:56:30) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Go into game
2. go onto a bike or car
3. drive around
4. static popping

### Expected behavior

No static pop

### Heroic Version

Latest Stable

### System Information

- OS: EndevourOS
- GPU: 6650XT 8Gb
- CPU: I5-9400f
- Ram: 32gb DDR4-2666mhz

**Comment by arielj** [comment] 2024-07-16 22:19
I doubt this is an issue with heroic itself

I recommend testing the same thing with lutris for example, if you have the same problem then it's something else like a system configuration and that should be asked in discord

**Comment by Rain-Gayming** [comment] 2024-07-17 09:12
It worked fine when I was launching the game via steam but then Proton decided to stop working so I used this,
I did try launching via lutris but it crashed on launch.

**Comment by Rain-Gayming** [comment] 2024-07-17 15:13
update????
Restarting my pc fixed it...
no clue what hte issue was

**Comment by CommandMC** [comment] 2024-07-22 01:05
Closing this for now. In case the issue returns, please do join our Discord and ask there. This issue tracker tracks issues within Heroic, not game-specific ones (anything caused by software other than Heroic, in this case Wine/PulseAudio/Pipewire)

**Closed by CommandMC** 2024-07-22 01:05 UTC
Labels: bug:unconfirmed
