### ISSUE TITLE
No progress is shown when installing game after switching view

### ISSUE THREAD

**Issue by davidM-tugraz** [Heroic-Games-Launcher/HeroicGamesLauncher#1462] opened 2022-06-12 16:31 UTC
### Describe the bug

When downloading a game the progress dissappears when switching to another tab (e.g. Tools, System Requirements, Library, etc.) and then switching back to the game.

Using the latest version from flathub: v2.3.7

### Add logs

(18:16:55) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:16:57) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:16:57) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:16:57) INFO:    [Backend]:         

Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.17.13-300.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i7-10610U @1.8 GOVERNOR: powersave
RAM: Total: 30.61 GiB Available: 26.68 GiB
GRAPHICS: GPU0: UHD Graphics  VRAM: 256MB DRIVER:  
PROTOCOL: wayland

(18:16:57) WARNING: [Backend]:         Failed to register protocol with OS.
(18:16:58) INFO:    [Frontend]:        Refreshing Library
(18:16:58) INFO:    [Legendary]:       Refreshing library...
(18:16:58) INFO:    [Legendary]:       Refreshing Epic Games...
(18:16:58) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:16:59) INFO:    [Legendary]:       Updating game list
(18:16:59) INFO:    [Legendary]:       Game List Updated
(18:17:00) INFO:    [Backend]:         Downloaded Winetricks
(18:17:00) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:17:00) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:17:01) INFO:    [Legendary]:       Found 0 game(s) to update
(18:17:01) INFO:    [Gog]:             Found 0 game(s) to update
(18:17:19) INFO:    [Frontend]:        Refreshing wine downloader releases
(18:17:19) INFO:    [WineDownloader]:  Updating wine versions info
(18:17:19) INFO:    [WineDownloader]:  Fetching upstream information...
(18:17:21) INFO:    [WineDownloader]:  wine versions updated
(18:18:10) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:18:10) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(18:18:46) INFO:    [Gog]:             Logging using GOG credentials
(18:18:47) INFO:    [Gog]:             Login Successful
(18:18:47) INFO:    [Gog]:             Getting data about the user
(18:18:47) INFO:    [Gog]:             Saved user data to config
(18:18:47) INFO:    [Frontend]:        Refreshing Library
(18:18:47) INFO:    [Gog]:             Getting GOG library
(18:18:47) INFO:    [Gog]:             Number of library pages: 1
(18:18:59) INFO:    [Gog]:             Saved games data
(18:19:03) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:03) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:05) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:05) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:05) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:05) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:05) WARNING: [Backend]:         default is not writable
(18:19:35) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:35) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:19:35) INFO:    [Gog]:             Installing 1423049311 with: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1423049311 --platform windows --path=/media/games/Heroic --token <redacted> --skip-dlcs --lang=en-US
(18:19:35) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1423049311 --platform windows --path=/media/games/Heroic --token <redacted> --skip-dlcs --lang=en-US
(18:19:35) DEBUG:   [Gog]:             Logging to file "/home/david/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(18:19:38) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/12:23:02
(18:19:39) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/07:54:03
(18:19:40) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/07:54:04
(18:19:41) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/06:55:05
(18:19:42) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/06:19:06
(18:19:43) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/07:56:07
(18:19:44) INFO:    [Backend]:         Progress for 1423049311: 0%/0.29MiB/11:49:08
(18:19:45) INFO:    [Backend]:         Progress for 1423049311: 0.03%/18.97MiB/14:15:09
(18:19:46) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/16:48:10
(18:19:47) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/19:18:11
(18:19:48) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/21:59:12
(18:19:49) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/23:48:13
(18:19:50) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/28:28:14
(18:19:51) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/29:38:15
(18:19:52) INFO:    [Backend]:         Progress for 1423049311: 0.12%/78.53MiB/32:24:16
(18:19:54) INFO:    [Backend]:         Progress for 1423049311: 0.14%/86.46MiB/37:24:18
(18:19:55) INFO:    [Backend]:         Progress for 1423049311: 0.16%/104.99MiB/36:00:19
(18:19:56) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/38:11:20
(18:19:57) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/41:26:21
(18:19:58) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/43:37:22
(18:19:59) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/45:43:23
(18:20:00) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/48:37:24
(18:20:01) INFO:    [Backend]:         Progress for 1423049311: 0.24%/154.81MiB/50:36:25
(18:20:02) INFO:    [Backend]:         Progress for 1423049311: 0.26%/163.15MiB/52:24:26
(18:20:03) INFO:    [Backend]:         Progress for 1423049311: 0.26%/163.15MiB/54:35:27
(18:20:04) INFO:    [Backend]:         Progress for 1423049311: 0.27%/172.28MiB/56:35:28
(18:20:05) INFO:    [Backend]:         Progress for 1423049311: 0.29%/181.73MiB/59:29:29
(18:20:06) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/62:28:30
(18:20:07) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/65:22:31
(18:20:08) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/71:06:32
(18:20:09) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/72:08:33
(18:20:10) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/73:25:34
(18:20:11) INFO:    [Backend]:         Progress for 1423049311: 0.36%/231.17MiB/72:52:35
(18:20:12) INFO:    [Backend]:         Progress for 1423049311: 0.38%/241.00MiB/75:23:36
(18:20:13) INFO:    [Backend]:         Progress for 1423049311: 0.38%/241.00MiB/73:35:37
(18:20:14) INFO:    [Backend]:         Progress for 1423049311: 0.41%/260.02MiB/79:23:38
(18:20:15) INFO:    [Backend]:         Progress for 1423049311: 0.42%/269.04MiB/79:40:39
(18:20:16) INFO:    [Backend]:         Progress for 1423049311: 0.48%/308.93MiB/84:11:40
(18:20:18) INFO:    [Backend]:         Progress for 1423049311: 0.48%/308.93MiB/90:27:42
(18:20:19) INFO:    [Backend]:         Progress for 1423049311: 0.48%/308.93MiB/90:20:43
(18:20:20) INFO:    [Backend]:         Progress for 1423049311: 0.48%/308.93MiB/95:09:44
(18:20:21) INFO:    [Backend]:         Progress for 1423049311: 0.48%/308.93MiB/97:10:45
(18:20:23) INFO:    [Backend]:         Progress for 1423049311: 0.52%/328.36MiB/97:12:47
(18:20:36) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(18:20:36) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows

### Steps to reproduce

1. Go to Library
2. Click on a game you want to install
3. Install it
4. Switch to another view (e.g. Settings)
5. Switch back to Library, the game you're installing
6. No progress is shown anymore, only "installing"

### Expected behavior

Showing the progress, speed, etc.

### Screenshots

![Bildschirmfoto vom 2022-06-12 18-23-24](https://user-images.githubusercontent.com/56354350/173243265-2df9ee2e-56df-4303-9534-fcf2a312a52d.png)

### System Information

- OS: Fedora 36
- Heroic Version: flatpak v2.3.7

**Comment by laytan** [comment] 2022-06-17 12:05
I have the same issue on SteamOS, heroic flatpack v2.3.9.

I believe it has something to do with the log file location. When I go to settings -> logs the log file it is tailing is .../.config/heroic/logs/.....log but I found a log file at .../.config/heroic/GamesConfig/.....log where the progress is updated consistently.

**Comment by Nocccer** [comment] 2022-06-17 12:15
Can confirm that this happens also on version 2.3.9. Will check if it is only gogdl related or also occurs with legendary.

**Comment by arielj** [comment] 2022-06-17 22:08
I couldn't reproduce the issue, tried with both GOG and Legendary, is that happening for you always? or in some specific cases?

**Comment by Nocccer** [comment] 2022-06-18 13:59
On the steam deck it always happens with gog games only. Legendary works great. Actually what happens is that the backend stops logging. Game will be downloaded still , but somehow the child_process.stdout.on breaks.

**Comment by davidM-tugraz** [comment] 2022-06-18 14:41
Happens all the time with GOG games on Fedora 36 and flatpak, haven't tried with Epic games. I have downloaded "Pillars of Eternity" yesterday via the rpm version of Heroic and there the progress was displayed from start till finish.

**Comment by gbdrbob** [comment] 2022-07-03 11:12
I had slightly different symptoms with this bug. When I switch the view away and back it was frozen on 6% downloaded, giving the impression downloading had stalled. Pausing and restarting the download got it to update with the correct download percentage. 

This is on a Steam Deck with the latest flatpak version

[heroic-2022-07-03T10_04_55.776Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9034598/heroic-2022-07-03T10_04_55.776Z.log)

I made [a screen recording](https://www.youtube.com/watch?v=-uqyP6H_U-w) of the bug happening, if that's at all helpful

**Comment by flavioislima** [comment] 2022-09-30 10:59
Fixed on 2.4.3

**Closed by flavioislima** 2022-09-30 10:59 UTC
