### ISSUE TITLE
After turning on "play offline" option, games don't see existing save files 

### ISSUE THREAD

**Issue by L0WR1D3Rz** [Heroic-Games-Launcher/HeroicGamesLauncher#1398] opened 2022-05-28 19:42 UTC
### Describe the bug

On steam deck : As per title After turning on "play offline" option, games don't see existing save files. If I untick it, games see the save files again. E. G. Alien isolation / blasphemous from epic games have this issue as every other single player game I tried. These games don't require online connection for save files on my PC. 

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/AlienIsolation /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 8935bb3e1420443a9789fe01758039a5 --offline --no-wine --wrapper "'/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton' run"

System Info:

  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
  CPU: AMD Custom APU 0405 @1.94 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 12.59 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": true,
	"otherOptions": "",
	"savesPath": "/home/deck/Games/Heroic/Prefixes/AlienIsolation/pfx/drive_c/users/steamuser/Local Settings/Application Data/The Creative Assembly/Alien Isolation/",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/AlienIsolation",
	"wineVersion": {
		"bin": "/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"useSteamRuntime": false
}

Error Log:
[Core] WARNING: Could not determine locale, falling back to en-US
[cli] INFO: Launching 8935bb3e1420443a9789fe01758039a5...
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
WARNING: radv is not a conformant Vulkan implementation, testing use only.

### Steps to reproduce

1. Go to one of the above mentioned games 
2. Click on play (without ticking play offline) and start a game until a save file is created 
3. Exit game tick play offline in game settings/other
4. Restart the game and try to load the save file (none will be found)
5. Exit game, untick play offline and retry (save file will be back) 

### Expected behavior

I expect when I play offline to still be able to continue my save file 

### System Information

- OS [e. g. "Ubuntu"]: steam deck latest steam os version as of may 28th
- Heroic Version [e. g. 2.1.1]: latest version as of may 28th

**Comment by flavioislima** [comment] 2022-05-28 19:44
When you launch the game and then go to the game logs there is nothing there?
We need at least the Launch command to see if the offline flag is being passed.

**Comment by L0WR1D3Rz** [comment] 2022-05-28 19:50
Ah sorry I thought whether it showed an error log but I get no errors. I'll get the log tomorrow morning and add it

**Comment by imLinguin** [comment] 2022-05-28 20:01
Also can you send how the saves directory is structured? It might help.

**Comment by L0WR1D3Rz** [comment] 2022-05-29 02:29
Hi ImLinguin. I'm not sure I understand the question. Can you give me an example? What do you mean how they are structured?

**Comment by L0WR1D3Rz** [comment] 2022-05-29 05:45
> When you launch the game and then go to the game logs there is nothing there? We need at least the Launch command to see if the offline flag is being passed.

I just added the log from within alien isolation settings/logs, to the original bug report. Let me know if that's what you were looking for

**Comment by imLinguin** [comment] 2022-05-29 07:06
I mean what files and directories, save directory contains. I suspect the path might depend on epic user id.

**Comment by L0WR1D3Rz** [comment] 2022-05-29 07:08
Here I took a picture within the directly I posted earlier. Is this ok? 
![IMG_20220529_090751](https://user-images.githubusercontent.com/106449726/170856562-da1fd043-367c-4181-a5c8-b5c53fe9f1c7.jpg)

**Comment by L0WR1D3Rz** [comment] 2022-05-30 08:17
> I mean what files and directories, save directory contains. I suspect the path might depend on epic user id.

Hi goodmorning. Just checking in, is the image/log ok? Fulfilling the requests you had? Also were you able to recreate the issue from your side?

**Comment by L0WR1D3Rz** [comment] 2022-06-05 07:03
> Everything is clear, but still I have no idea why this happens. I'll try to reproduce issue when I have more time.

Thanks. Just wanted to let you know that I updated today and the issue persists with the latest version of heroic launcher. When play offline is ticked it won't see the save files

**Comment by GamerGoat112** [comment] 2022-08-25 21:26
Has this been fixed?

**Comment by L0WR1D3Rz** [comment] 2022-08-26 04:37
No

**Comment by arielj** [comment] 2023-08-12 18:31
I think this is not a bug in Heroic but how those games work. Saves seems to be user-dependent, so when playing offline the there's no logged user and the saves are not used by the game.

Similar thing happens with Bioshock Infinite.

I don't think there's anything we can do, seems to be just how those games work internally.

**Comment by arielj** [comment] 2023-08-12 18:40
For Alien Isolation, this is also how the game works, also in steam https://steamcommunity.com/app/214490/discussions/0/611696927908022435/

**Comment by arielj** [comment] 2023-08-12 18:45
For blasphemous, it also seems to be a game issue, not a heroic issue, check https://www.reddit.com/r/Blasphemous/comments/lp5ux1/just_lost_my_progress_somehow/


I'm going to close this issue since the games reported are known to have issues when playing offline, and it's NOT Heroic's fault.

**Closed by arielj** 2023-08-12 18:45 UTC
Labels: issue:investigating
