### ISSUE TITLE
Cannot log in to epic games store

### ISSUE THREAD

**Issue by Zanomi** [Heroic-Games-Launcher/HeroicGamesLauncher#3726] opened 2024-04-27 21:45 UTC
### Describe the bug

After clicking log in a blank screen persists

### Add logs

```text
(22:36:36) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:36:36) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:36:36) INFO:    [Connection]:       Connectivity: check-online
(22:36:36) INFO:    [Connection]:       Pinging external endpoints
(22:36:36) INFO:    [Gog]:              Checking for existing gog manifests
(22:36:36) INFO:    [Connection]:       Connectivity: online
(22:36:36) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:36:36) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:36:36) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(22:36:36) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(22:36:37) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0932
Memory: 15.53 GB (used: 4.13 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405]
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: OLED) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(22:36:40) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "updated",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(22:36:40) INFO:    [Backend]:          User Not Found, removing it from Store
(22:36:40) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(22:36:40) WARNING: [Backend]:          Failed to register protocol with OS.
(22:36:40) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:36:41) INFO:    [Backend]:          Frontend Ready
(22:36:41) INFO:    [Backend]:          Checking for current version changelog
(22:36:41) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(22:36:41) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(22:36:41) INFO:    [Frontend]:         Refreshing undefined Library
(22:36:41) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:36:41) INFO:    [Legendary]:        Refreshing library...
(22:36:43) INFO:    [Winetricks]:       Downloading Winetricks
(22:36:43) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.12
(22:36:43) INFO:    [DXVKInstaller]:    Updating dxvk-nvapi to: dxvk-nvapi-v0.7.0
(22:36:43) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.3.1
(22:36:45) INFO:    [WineDownloader]:   Updating wine versions info
(22:36:45) INFO:    [WineDownloader]:   Fetching upstream information...
(22:36:46) INFO:    [Backend]:          Starting the Download Queue
(22:36:46) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.12/vkd3d-proton-2.12.tar.xz
(22:36:46) INFO:    [DXVKInstaller]:    Downloaded vkd3d, extracting...
(22:36:46) INFO:    [Backend]:          Extracting /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/vkd3d/vkd3d-proton-2.12.tar.xz to /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/vkd3d/vkd3d-proton-2.12 using native tar
(22:36:47) INFO:    [DXVKInstaller]:    vkd3d updated!
(22:36:47) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/jp7677/dxvk-nvapi/releases/download/v0.7.0/dxvk-nvapi-v0.7.0.tar.gz
(22:36:47) INFO:    [DXVKInstaller]:    Downloaded dxvk-nvapi, extracting...
(22:36:47) INFO:    [Backend]:          Extracting /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.7.0.tar.gz to /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.7.0 using native tar
(22:36:47) INFO:    [DXVKInstaller]:    dxvk-nvapi updated!
(22:36:47) INFO:    [WineDownloader]:   wine versions updated
(22:36:48) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3.1/dxvk-2.3.1.tar.gz
(22:36:48) INFO:    [DXVKInstaller]:    Downloaded dxvk, extracting...
(22:36:48) INFO:    [Backend]:          Extracting /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk/dxvk-2.3.1.tar.gz to /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk/dxvk-2.3.1 using native tar
(22:36:48) INFO:    [DXVKInstaller]:    dxvk updated!
```

### Steps to reproduce

1. Go to stores
2. Click on epic
3. Click log in

### Expected behavior

Can log in

### Screenshots

![PXL_20240427_214051699](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/136493913/efd078b4-b816-429f-aa78-be1e610c63e7)

### Heroic Version

Latest Stable

### System Information

- steamOs

**Comment by arielj** [comment] 2024-04-28 01:57
duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3682

use the Manage Accounts option in the sidebar until the next release

**Closed by arielj** 2024-04-28 01:57 UTC
Labels: bug:unconfirmed
