### ISSUE TITLE
Can't login to Epic

### ISSUE THREAD

**Issue by ZephaniahNoah** [Heroic-Games-Launcher/HeroicGamesLauncher#3739] opened 2024-05-07 07:52 UTC
### Describe the bug

I just updated from 2.13 to 2.14.1 and noticed that none of my Epic games are listed. So I clicked on "Stores" then "Epic Store" and a login prompt appeared. It said, "You are NOT logged in" and there is a login button. When I click the log in button it goes to a blank page and nothing happens.

### Add logs

```text
(21:46:05) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:46:05) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:46:05) INFO:    [Connection]:       Connectivity: check-online
(21:46:05) INFO:    [Connection]:       Pinging external endpoints
(21:46:05) INFO:    [Gog]:              Checking for existing gog manifests
(21:46:05) INFO:    [Nile]:             Refreshing library...
(21:46:05) INFO:    [Nile]:             Refreshing Amazon Games...
(21:46:05) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(21:46:05) INFO:    [Nile]:             Game list updated, got 15 games
(21:46:05) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(21:46:05) WARNING: [Backend]:          Failed to register protocol with OS.
(21:46:05) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:46:05) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json --version
(21:46:05) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(21:46:06) INFO:    [Connection]:       Connectivity: online
(21:46:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json auth
(21:46:06) INFO:    [Backend]:          User Not Found, removing it from Store
(21:46:06) INFO:    [Gog]:              Checking if login is valid
(21:46:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json auth
(21:46:06) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Memory: 16.71 GB (used: 2.85 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GM204 [GeForce GTX 970]
    IDs: D=13c2 V=10de SD=2974 SV=3842
    Driver: nvidia
OS: Ubuntu 24.04 LTS (Noble Numbat) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(21:46:06) INFO:    [Nile]:             Saved user data to config file
(21:46:06) INFO:    [Frontend]:         Refreshing undefined Library
(21:46:06) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:46:06) INFO:    [Legendary]:        Refreshing library...
(21:46:06) INFO:    [Nile]:             Refreshing library...
(21:46:06) INFO:    [Nile]:             Refreshing Amazon Games...
(21:46:06) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(21:46:06) INFO:    [Nile]:             Game list updated, got 15 games
(21:46:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json auth
(21:46:06) INFO:    [Backend]:          Frontend Ready
(21:46:06) INFO:    [Gog]:              Getting GOG library
(21:46:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json auth
(21:46:06) INFO:    [Backend]:          Checking for new Heroic Updates
(21:46:06) INFO:    [Backend]:          Checking for current version changelog
(21:46:06) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:46:07) INFO:    [Gog]:              Saved username to config file
(21:46:08) INFO:    [Winetricks]:       Downloading Winetricks
(21:46:08) INFO:    [Gog]:              Saved games data
(21:46:08) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:46:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zephaniahnoah/.config/heroic/gog_store/auth.json auth
(21:46:09) INFO:    [Gog]:              Found 0 game(s) to update
(21:46:09) INFO:    [Nile]:             Looking for updates...
(21:46:09) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/zephaniahnoah/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(21:46:10) INFO:    [WineDownloader]:   Updating wine versions info
(21:46:10) INFO:    [WineDownloader]:   Fetching upstream information...
(21:46:11) INFO:    [Backend]:          Starting the Download Queue
(21:46:12) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Click on Stores
2. Click on Epic Store
3. Click on LOG IN

### Expected behavior

Normal login process

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/14168013/a09b779a-cce3-45fb-9711-94f0f6c39673)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/14168013/dceb6f03-bd88-429a-a47d-a672855e74e1)

### Heroic Version

2.14.1

### System Information

- OS Xubuntu 24.04

**Comment by CommandMC** [comment] 2024-05-07 20:33
Duplicate of #3682

**Closed by CommandMC** 2024-05-07 20:33 UTC
Labels: bug:unconfirmed

**Comment by ZephaniahNoah** [comment] 2024-05-07 21:00
Ah. I didn't search for similar issues long enough. My bad
