### ISSUE TITLE
Heroic won't open

### ISSUE THREAD

**Issue by Izz21** [Heroic-Games-Launcher/HeroicGamesLauncher#398] opened 2021-06-01 10:58 UTC
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.

**Describe the bug**
Heroic won't load up after I enter the sid code.

**To Reproduce**

1. Launch Heroic through terminal
2. Error code shows up.

**Expected behavior**

**Screenshots**
I don't have a screenshot but this is the error code:

Failed to register protocol with OS.
Error occurred in handler for 'login': Error: Command failed: /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid 9d9a02c88dc94e72b4ba1bdc1c5461ad
[7034] Error loading Python lib '/tmp/_MEIBEOHg1/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIBEOHg1/libpython3.8.so.1.0)

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: '/opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid 9d9a02c88dc94e72b4ba1bdc1c5461ad',
  stdout: '',
  stderr: "[7034] Error loading Python lib '/tmp/_MEIBEOHg1/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIBEOHg1/libpython3.8.so.1.0)\n"
}

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 16.04
- Game: Heroic
- Wine/Proton version: 5.0.3
- Hardware specs (RAM, CPU, GPU): 32-bit, 64-bit

**Additional context**

**Comment by adityaruplaha** [comment] 2021-06-01 11:49
Duplicate of #392.

Ubuntu 16.04 ships with Python 3.5, you need atleast 3.8 for using Legendary. Thus, you need Python 3.8+ for Heroic too.

**Comment by adityaruplaha** [comment] 2021-06-01 11:52
Nevermind, this is not a Python issue. Try updating `glibc`.

**Closed** 2021-06-02 13:46 UTC
Labels: support:open
