### ISSUE TITLE
Unable to install Heroic Launcher on Fedora 40

### ISSUE THREAD

**Issue by securerootd** [Heroic-Games-Launcher/HeroicGamesLauncher#3964] opened 2024-08-17 19:36 UTC
### Describe the bug

Official download of Heroic Launcher rpm 2.15.1 is not installable on Fedora 40 and having a conflict with bittwarden

### Add logs

```text
sudo dnf update ./heroic-2.15.1.x86_64.rpm 
Last metadata expiration check: 0:19:08 ago on Sunday 18 August 2024 12:42:32 AM.
Dependencies resolved.
============================================================================================================================================
 Package                        Architecture                   Version                           Repository                            Size
============================================================================================================================================
Upgrading:
 heroic                         x86_64                         2.15.1-1                          @commandline                         107 M

Transaction Summary
============================================================================================================================================
Upgrade  1 Package

Total size: 107 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/01/4cf96203aed6b44b362f930a85553ebe5ba70c from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/31/18e8c152e4ef215bc843fbb3ab9281877f7ada from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/64/cecce815e950bd7e1303f2930efef7b804cdae from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/87/003aa4689d6ea1fd547c9c771e443afdb6d9a2 from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/a8/bead032b728141d97788324d6540887ae9caf2 from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/e0/d994ca1d7810114cf0e469ea499412d46e017f from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
  file /usr/lib/.build-id/f4/f4df1c78477202a87b3207a0488cd9196e3ed7 from install of heroic-2.15.1-1.x86_64 conflicts with file from package bitwarden-2024.7.1-1.x86_64
```

### Steps to reproduce

1. Download https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.15.1/heroic-2.15.1.x86_64.rpm
2. Try to install
3. See error

### Expected behavior

1. Download https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.15.1/heroic-2.15.1.x86_64.rpm
2. Try to install
3. Install successful

### Heroic Version

Latest Stable

### System Information

$ -> cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde

**Comment by imLinguin** [comment] 2024-08-17 19:37
Duplicate of #3950

**Closed by imLinguin** 2024-08-17 19:37 UTC
Labels: bug:unconfirmed
