### ISSUE TITLE
Heroic goes blank after few seconds

### ISSUE THREAD

**Issue by firefinchdev** [Heroic-Games-Launcher/HeroicGamesLauncher#681] opened 2021-10-08 14:01 UTC
**Describe the bug**
When I open Heroic, the screen is fine, but goes blank after few seconds.
This happens when I installed Rocket league in Heroic.
I removed config files to reset Heroic, and started Heroic again. Now, since Rocket league is not installed, Heroic is working fine.
Then I installed Rocket league again, and restarted Heroic. Issue reappears.

**To Reproduce**

1. Install Heroic
2. Authenticate account and download Rocket league (or maybe some other game?)
3. Restart Heroic
4. Heroic goes blank after few seconds.

**Screenshots**

<img width="1648" alt="Screenshot 2021-10-08 at 7 08 30 PM" src="https://user-images.githubusercontent.com/26357501/136569941-aacd9e21-95d2-4087-9c94-dda94351bd36.png">

<img width="1648" alt="Screenshot 2021-10-08 at 7 30 28 PM" src="https://user-images.githubusercontent.com/26357501/136570400-519d33da-b424-4c45-ad4b-fb776e890f1d.png">

<img width="1648" alt="Screenshot 2021-10-08 at 7 30 47 PM" src="https://user-images.githubusercontent.com/26357501/136570430-2910a90d-5a83-4904-938c-d157ab48fa22.png">

**Desktop (please complete the following information):**

- OS: macOS (MacBook Pro (16-inch, 2019) Intel i7 16Gb DDR4)
- Version Big Sur 11.6
- Game: Rocket League
- Wine/Proton version: Crossover 20 wine
- Hardware specs (RAM, CPU, GPU): MacBook Pro (16-inch, 2019) Intel i7 16Gb DDR4

**Comment by flavioislima** [comment] 2021-10-13 06:46
Ah @klayveR, your issue is with python encoding, you can see on the error. I think there is some issue that I linked on our troubleshooting guide on how to fix this.

**Comment by flavioislima** [comment] 2021-10-13 06:48
Here, check the latest comments. 
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issue

**Comment by firefinchdev** [comment] 2021-10-13 06:57
> Here, check the latest comments. 
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issue 

I think you posted the wrong link

**Comment by flavioislima** [comment] 2021-10-13 08:23
Yes, I was on the phone so it was missing the issue number,

**Comment by firefinchdev** [comment] 2021-10-13 14:32
> @firefinchdev on your side, 1.10.2 fixed it?

Just tested...nope it is not fixed
Facing same problem..
Screen blank after few seconds..

**Comment by flavioislima** [comment] 2021-10-13 21:50
> > @firefinchdev on your side, 1.10.2 fixed it?
> 
> Just tested...nope it is not fixed Facing same problem.. Screen blank after few seconds..

It seems that legendary command to check for updates doesn't work on mac m1 for some reason. I cannot reproduce it on a Intel mac. Heres what I'll do: I'll add an option to not check for games update on start.
Heroic will still warn you if a game needs update whenever you click play.
I'll try to release this new setting during the weekend and then you can try it.

**Comment by flavioislima** [comment] 2021-10-17 22:11
Finally fixed on latest release, @firefinchdev check again when you have the time.

**Closed as completed** 2021-10-24 09:50 UTC
Labels: issue:investigating
