### ISSUE TITLE
Games fails (D-Bus error) to launch when Steam Runtime is enabled

### ISSUE THREAD

**Issue by trinukso** [Heroic-Games-Launcher/HeroicGamesLauncher#2790] opened 2023-06-09 17:42 UTC
### Describe the bug

Tested games: HUNTDOWN and Amnesia: A Machine For Pigs (native games).

### Add logs

```text
Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": true,
	"useSteamRuntime": true,
	"language": "",
	"wineVersion": {
		"bin": "/home/vicen/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-43/bin/wine",
		"name": "Wine - Wine-GE-Proton7-43",
		"type": "wine",
		"lib": "/home/vicen/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-43/lib64",
		"lib32": "/home/vicen/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-43/lib",
		"wineserver": "/home/vicen/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-43/bin/wineserver",
		"wineboot": "/home/vicen/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-43/bin/wineboot"
	},
	"winePrefix": "/home/vicen/Games/Heroic/Prefixes/HUNTDOWN",
	"wineCrossoverBottle": ""
}

Game launched at: Fri Jun 09 2023 19:40:41 GMT+0200 (hora de verano de Europa central)

System Info:
Heroic Version: 2.8.0 Nico Robin
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.2

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 6.3.6-zen1-1-zen ARCH: x64
CPU: Intel Core™ i5-10400F @2.9 GOVERNOR: powersave
RAM: Total: 31.2 GiB Available: 28.01 GiB
GRAPHICS: GPU0: TU106 [GeForce RTX 2060 12GB]  VRAM: 32MB 
PROTOCOL: wayland

Launch Command: /app/bin/gamemoderun /home/vicen/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch /home/vicen/Games/Heroic/HUNTDOWN 2094700167 --platform linux

Game Log:
gamemodeauto: 
dbus[513]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[510]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

### Steps to reproduce

Install both Steam and Heroic from flatpak
Install any native game
Enable in settings the game to use Steam Runtime
Try to launch the game

### Expected behavior

The games works

### Heroic Version

Latest Stable

### System Information

Flatpak from flathub

**Comment by arielj** [comment] 2023-07-29 15:56
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2931

**Closed by arielj** 2023-07-29 15:56 UTC
Labels: issue:investigating, bug:unconfirmed
