### ISSUE TITLE
GTA 5 on MAC

### ISSUE THREAD

**Issue by southchester** [Heroic-Games-Launcher/HeroicGamesLauncher#3644] opened 2024-03-24 07:15 UTC
### Describe the bug

The problem is that I have configured heroic, crossover 24.0.1, but when launching GTA 5, the rockstar game launcher opens and nothing happens further
<img width="1440" alt="Screenshot 2024-03-24 at 10 13 16" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/164725272/fbd1b085-c07d-477d-a031-c78d137e9dc7">

### Add logs

```text
dont have
```

### Steps to reproduce

1. Go to '.H
<img width="1440" alt="Screenshot 2024-03-24 at 10 13 18" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/164725272/267ed8c2-9617-45f3-a6fc-0e82cb227786">
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

s

### Heroic Version

Latest Stable

### System Information

Mac OS 14

**Comment by sshrmr** [comment] 2024-04-09 14:27
Same here. Downgraded to 2.13.0 and all good

**Comment by youngsamoice** [comment] 2024-04-09 21:28
> Same here. Downgraded to 2.13.0 and all good

how can I downgrade the Heroic version?

**Comment by udance4ever** [comment] 2024-12-06 23:57
> > Same here. Downgraded to 2.13.0 and all good
> 
> how can I downgrade the Heroic version?

the direct answer to your question is to download the older release here: 
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases

scroll down until you see 2.13 and download the dmg.

that said, unfortunately it didn't work for me.  my desktop looks exactly as the poster @southchester  - I have Heroic 2.13.0 showing that is is "Playing" and the Rockstar Games Launcher (aka. SocialClubHelper.exe) is up and Heroic never launches the title.

I've been chatting with CrossOver support and I also have BattlEye turned off as well.

no dice.

I'm on a 2020 M1 MacBookPro 16GB (macOS Sequoia 15.1.1) and CrossOver 24.0.5

Heroic devs: I've confirmed this bug :)

if there is any other information that is helpful, please let us all know so we can all be heroes again ⚡️

**Comment by arielj** [comment] 2024-12-07 01:13
check on discord, there's a lot of threads about GTA V on mac and game issues shouldn't be reported here but in the `#-support` area of discord, check https://discord.com/channels/812703221789097985/1309869030785417246/1310361918292234260 for example and there are many macos-specific threads

I'm closing this issue since github issues are for bugs with the launcher and this is a game compatibility issue

**Closed by arielj** 2024-12-07 01:13 UTC
Labels: bug:unconfirmed
