### ISSUE TITLE
Hijacking all 'CTRL' button actions from other open windows on debian

### ISSUE THREAD

**Issue by Mundball** [Heroic-Games-Launcher/HeroicGamesLauncher#2702] opened 2023-05-13 15:40 UTC
### Describe the bug

Heroic hijack all 'CTRL' button actions what you hit in your keyboard from other programs/windows.

### Add logs

```text
(17:32:09) INFO:    [Legendary]:        Refreshing library...
(17:32:09) INFO:    [Connection]:       Connectivity: check-online
(17:32:09) INFO:    [Connection]:       Pinging external endpoints
(17:32:09) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:32:10) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:32:10) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:32:10) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:32:10) WARNING: [Backend]:          Protocol already registered.
(17:32:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/max/.config/heroic/gog_store/auth.json --version
(17:32:10) INFO:    [Connection]:       Connectivity: online
(17:32:10) INFO:    [Backend]:          User Not Found, removing it from Store
(17:32:10) INFO:    [Gog]:              Checking if login is valid
(17:32:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/max/.config/heroic/gog_store/auth.json auth
(17:32:10) INFO:    [Backend]:          Loading Screen Ready
(17:32:10) INFO:    [Frontend]:         Refreshing Library
(17:32:10) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:32:10) INFO:    [Backend]:          Frontend Ready
(17:32:10) INFO:    [Backend]:          

Heroic Version: 2.7.1 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Debian GNU/Linux KERNEL: 6.1.0-0.deb11.6-amd64 ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: ondemand
RAM: Total: 62.72 GiB Available: 56.46 GiB
GRAPHICS: GPU0: Hawaii PRO [Radeon R9 290/390] VRAM: 256MB 
PROTOCOL: x11

(17:32:10) INFO:    [Backend]:          Checking for new Heroic Updates
(17:32:10) INFO:    [Backend]:          Checking for current version changelog
(17:32:10) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:32:10) INFO:    [Gog]:              Saved username to config file
(17:32:12) INFO:    [Winetricks]:       Downloading Winetricks
(17:32:15) INFO:    [Backend]:          Starting the Download Queue
(17:32:15) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/max/.config/heroic/gog_store/auth.json auth
(17:32:15) INFO:    [Backend]:          Preventing machine to sleep
(17:32:15) INFO:    [Gog]:              Installing 1207658930: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/max/.config/heroic/gog_store/auth.json download 1207658930 --platform linux "--path=/home/max/.GOG Games" --token <redacted> --skip-dlcs --lang=en
(17:32:15) DEBUG:   [Gog]:              Logging to file "/home/max/.config/heroic/GamesConfig/1207658930.log"
(17:32:18) INFO:    [Gog]:              Found 1 game(s) to update
(17:32:18) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:32:18) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:32:18) INFO:    [Legendary]:        Refreshing library...
(17:32:27) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.1%/20.20MB/01:56:42 Down: 0MB/s / Disk: 0MB/s
(17:32:39) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.2%/60.61MB/02:38:12 Down: 20.18MB/s / Disk: 20.18MB/s
(17:32:41) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.3%/60.61MB/01:56:27 Down: 0MB/s / Disk: 0MB/s
(17:32:42) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.3%/60.61MB/02:02:00 Down: 0MB/s / Disk: 0MB/s
(17:32:46) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.3%/60.61MB/02:24:11 Down: 0MB/s / Disk: 0MB/s
(17:32:49) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.4%/80.82MB/02:00:29 Down: 0MB/s / Disk: 0MB/s
(17:33:04) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.5%/121.23MB/02:26:06 Down: 20.18MB/s / Disk: 20.18MB/s
(17:33:30) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.8%/181.84MB/02:24:50 Down: 20.18MB/s / Disk: 20.18MB/s
(17:33:33) INFO:    [Frontend]:         Refreshing Library
(17:33:33) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:34) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:34) INFO:    [Backend]:          Checking for current version changelog
(17:33:35) INFO:    [Frontend]:         Refreshing Library
(17:33:35) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:35) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:35) INFO:    [Backend]:          Checking for current version changelog
(17:33:35) INFO:    [Frontend]:         Refreshing Library
(17:33:35) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:35) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:35) INFO:    [Backend]:          Checking for current version changelog
(17:33:36) INFO:    [Frontend]:         Refreshing Library
(17:33:36) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:36) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:36) INFO:    [Backend]:          Checking for current version changelog
(17:33:36) INFO:    [Frontend]:         Refreshing Library
(17:33:36) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:36) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:36) INFO:    [Backend]:          Checking for current version changelog
(17:33:37) INFO:    [Frontend]:         Refreshing Library
(17:33:37) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:33:37) INFO:    [Backend]:          Checking for new Heroic Updates
(17:33:37) INFO:    [Backend]:          Checking for current version changelog
(17:33:37) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 0.9%/181.84MB/02:21:29 Down: 0MB/s / Disk: 0MB/s
(17:33:40) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:40) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:41) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:41) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:41) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:41) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:42) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:42) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:42) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:42) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:43) INFO:    [Gog]:              Found 1 game(s) to update
(17:33:43) INFO:    [Gog]:              Skipping auto-update for Stellaris
(17:33:43) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:33:43) INFO:    [Legendary]:        Refreshing library...
(17:33:51) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.1%/222.25MB/02:16:31 Down: 0MB/s / Disk: 0MB/s
(17:33:52) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.1%/222.25MB/02:18:01 Down: 0MB/s / Disk: 0MB/s
(17:33:55) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.1%/222.25MB/02:22:32 Down: 0MB/s / Disk: 0MB/s
(17:34:06) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.2%/262.66MB/02:25:38 Down: 20.18MB/s / Disk: 20.18MB/s
(17:34:10) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.3%/262.66MB/02:19:21 Down: 0MB/s / Disk: 0MB/s
(17:34:11) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.3%/262.66MB/02:20:37 Down: 0MB/s / Disk: 0MB/s
(17:34:18) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.4%/282.86MB/02:18:40 Down: 0MB/s / Disk: 0MB/s
(17:34:19) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.4%/282.86MB/02:19:51 Down: 0MB/s / Disk: 0MB/s
(17:34:34) INFO:    [Gog]:              Progress for The Witcher 2: Assassins of Kings Enhanced Edition: 1.5%/303.07MB/02:26:50 Down: 0MB/s / Disk: 0MB/s
```

### Steps to reproduce

Way 1
1. Start heroic
2. if heroic window is minimized
3. open terminal
4. hit 'CTRL' + 'R'
5. you got no backward search
6. close heroic complet
7. repeat from point 4 it works now

Way 2

1. Start heroic
2. if heroic window is open
3. open terminal
4. hit 'CTRL' + 'R'
5. you got no backward search but heroic flash white

Both ways are all reproducable with other programs, other combinations get hijacked too.

### Expected behavior

i want my 'CTRL' button back.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: debian bullseye
- package: deb
- Heroic: 2.7.1

**Comment by arielj** [comment] 2023-05-13 15:49
duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2692, please use the search before reporting a bug

it is fixed in the development branch and the fix will be included in the next release

**Closed by arielj** 2023-05-13 15:49 UTC
