### ISSUE TITLE
[Feature request] Optionally prevent Heroic window from restoring on game quit

### ISSUE THREAD

**Issue by Yasand123** [Heroic-Games-Launcher/HeroicGamesLauncher#2527] opened 2023-03-09 16:57 UTC
### Feature description

I have a game shortcut in my launcher, it works as expected, as Heroic runs in the background. However upon exiting the game, Heroic restores itself from the systray area. This behavior can be annoying especially if you're running your games from external shortcuts. An option to prevent this behavior would be nice.

**Comment by arielj** [comment] 2023-03-09 18:59
I understand this is a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2478 and is already fixed in the repo (will be fixed in next heroic release)

**Closed by arielj** 2023-03-09 18:59 UTC
