### ISSUE TITLE
Cannot log into Epic Store

### ISSUE THREAD

**Issue by CountMurphy** [Heroic-Games-Launcher/HeroicGamesLauncher#3729] opened 2024-04-30 15:34 UTC
### Describe the bug

When selecting Epic store, a pop launches asking me to click the login button. Once clicked, heroic only shows a blank grey screen. Tried on two different systems. Same result. Both running the official AUR package.

### Add logs

```text
(10:25:15) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:25:15) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:25:15) INFO:    [Connection]:       Connectivity: check-online
(10:25:15) INFO:    [Connection]:       Pinging external endpoints
(10:25:15) INFO:    [Gog]:              Checking for existing gog manifests
(10:25:15) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(10:25:16) WARNING: [Backend]:          Protocol already registered.
(10:25:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/sarif/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:25:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json --version
(10:25:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/sarif/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(10:25:16) INFO:    [Connection]:       Connectivity: online
(10:25:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json auth
(10:25:16) INFO:    [Backend]:          User Not Found, removing it from Store
(10:25:16) INFO:    [Gog]:              Checking if login is valid
(10:25:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json auth
(10:25:16) INFO:    [Backend]:          
System Information:
CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H
Memory: 67.1 GB (used: 9.32 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA103M [GeForce RTX 3080 Ti Laptop GPU]
    IDs: D=2460 V=10de SD=0b54 SV=1028
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics]
    IDs: D=46a6 V=8086 SD=0b54 SV=1028
    Driver: i915
OS: Arch Linux 6.8.8-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(10:25:16) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:25:16) INFO:    [Frontend]:         Refreshing undefined Library
(10:25:16) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(10:25:16) INFO:    [Legendary]:        Refreshing library...
(10:25:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json auth
(10:25:16) INFO:    [Backend]:          Frontend Ready
(10:25:16) INFO:    [Gog]:              Getting GOG library
(10:25:16) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json auth
(10:25:16) INFO:    [Backend]:          Checking for new Heroic Updates
(10:25:16) INFO:    [Backend]:          Checking for current version changelog
(10:25:17) INFO:    [Gog]:              Saved username to config file
(10:25:18) INFO:    [Winetricks]:       Downloading Winetricks
(10:25:18) INFO:    [Gog]:              Saved games data
(10:25:18) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:25:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/sarif/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/sarif/.config/heroic/gog_store/auth.json auth
(10:25:19) INFO:    [Gog]:              Found 0 game(s) to update
(10:25:21) INFO:    [WineDownloader]:   Updating wine versions info
(10:25:21) INFO:    [WineDownloader]:   Fetching upstream information...
(10:25:21) INFO:    [Backend]:          Starting the Download Queue
(10:25:21) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Open heroic
2. Click on Stores. Click on Epic
3. Click the Blue login button
4. See gray screen

### Expected behavior

Some sort of login dialog to appear

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/2205997/bc818131-0c91-4042-9e7f-68fdecf5087e)

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/2205997/44be6a5a-468a-457f-8a93-127a890774a0)

### Heroic Version

Latest Stable

### System Information

- OS: Arch Linux
    -  heroic-games-launcher-bin  package from AUR

**Comment by arielj** [comment] 2024-04-30 15:42
duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3726

use the `Manage Accounts` option in the sidebar to login until the next release

**Closed by arielj** 2024-04-30 15:42 UTC
Labels: bug:unconfirmed

**Comment by CountMurphy** [comment] 2024-04-30 15:47
Sorry about the dupe, didn't check closed tickets!
