### ISSUE TITLE
Weird behaviour in winetricks

### ISSUE THREAD

**Issue by baryluk** [Heroic-Games-Launcher/HeroicGamesLauncher#3221] opened 2023-11-06 22:18 UTC
### Describe the bug

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/110322/7117e138-d4b8-44bf-a811-e530760b59d8)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/110322/08f2ea0a-69d5-4699-88a2-b70750c69a2b)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/110322/d6995cb0-8727-4605-b118-024d77918c63)

No idea what it means by "od"

### Add logs

```text
heroic-2.10.0


(22:15:55) ERROR:   [Winetricks]:       od: wine
(22:15:55) ERROR:   [Winetricks]:       : No such file or directory

```
```


### Steps to reproduce

See above

### Expected behavior

See above

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

- OS

### Additional information

_No response_

**Comment by arielj** [comment] 2023-11-07 17:45
that is normal, at least for me it happens always when I run winetricks, even outside heroic

but I haven't seen any problem caused by that whatsoever

**Comment by baryluk** [comment] 2023-11-11 10:34
More cosmetic than serious issue. Probably more a problem with winetricks than heroic, but I do not know where heroic gets winetricks from (downloads from somewhere probably), so not sure where else to report.

**Comment by arielj** [comment] 2023-11-16 04:38
> More cosmetic than serious issue. Probably more a problem with winetricks than heroic, but I do not know where heroic gets winetricks from (downloads from somewhere probably), so not sure where else to report.

we download winetricks from the winetricks repo https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b6bfb5b7ce8db79076db091b6a1fe7f00a78aa03/src/backend/tools/index.ts#L435

**Comment by arielj** [comment] 2023-11-16 04:40
There seems to be a report already https://github.com/Winetricks/winetricks/issues/2143, and a PR fixing that https://github.com/Winetricks/winetricks/pull/2147

**Comment by arielj** [comment] 2023-11-16 04:41
I'm closing this since we can't really fix the issue on Heroic's side. Eventually Winetricks will be updated and Heroic will download the latest version and the error will be gone.

**Closed by arielj** 2023-11-16 04:41 UTC
Labels: bug:unconfirmed
