### ISSUE TITLE
cannot get game info

### ISSUE THREAD

**Issue by VampyRagdoll** [Heroic-Games-Launcher/HeroicGamesLauncher#3871] opened 2024-07-21 10:30 UTC
### Describe the bug

 every time i try to play or install a game i get 'cannot get game info.
ive reset heroic and cleared the cache but it happens every time.
i dont know how to stop it from happening.
ive logged out of all accounts and logged back in but nothing changed.

### Add logs

```text
(11:04:03) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:04:03) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:04:03) INFO:    [Connection]:       Connectivity: check-online
(11:04:03) INFO:    [Connection]:       Pinging external endpoints
(11:04:03) INFO:    [Gog]:              Checking for existing gog manifests
(11:04:03) INFO:    [Nile]:             Refreshing library...
(11:04:03) INFO:    [Nile]:             Refreshing Amazon Games...
(11:04:03) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(11:04:03) INFO:    [Nile]:             Game list updated, got 355 games
(11:04:03) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(11:04:03) WARNING: [Backend]:          Failed to register protocol with OS.
(11:04:03) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:04:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(11:04:03) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(11:04:04) INFO:    [Connection]:       Connectivity: online
(11:04:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:04) INFO:    [Gog]:              Checking if login is valid
(11:04:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:04) INFO:    [Nile]:             Saved user data to config file
(11:04:04) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.53 GB (used: 5.13 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]
    IDs: D=163f V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: LCD) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(11:04:04) INFO:    [Frontend]:         Refreshing undefined Library
(11:04:04) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(11:04:04) INFO:    [Legendary]:        Refreshing library...
(11:04:04) INFO:    [Legendary]:        Refreshing Epic Games...
(11:04:04) INFO:    [Nile]:             Refreshing library...
(11:04:04) INFO:    [Nile]:             Refreshing Amazon Games...
(11:04:04) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(11:04:04) INFO:    [Nile]:             Game list updated, got 355 games
(11:04:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:04) INFO:    [Backend]:          Frontend Ready
(11:04:04) INFO:    [Gog]:              Updating redist, reason - new buildId
(11:04:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:04) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(11:04:04) INFO:    [Backend]:          Preventing machine to sleep
(11:04:04) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:04:04) INFO:    [Gog]:              Getting GOG library
(11:04:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:04) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info gog-redist --os windows
(11:04:05) INFO:    [Backend]:          Checking for current version changelog
(11:04:05) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(11:04:05) INFO:    [DownloadManager]:  Galaxy Common Redistributables  was added to the download queue.
(11:04:05) INFO:    [Gog]:              Updating GOG redistributables
(11:04:05) INFO:    [Gog]:              GOG REDIST:: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json redist --ids ISI --path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/redist/gog
(11:04:05) DEBUG:   [Gog]:              Logging to file "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/gog-redist.log"
(11:04:05) INFO:    [Gog]:              Saved username to config file
(11:04:06) INFO:    [Winetricks]:       Downloading Winetricks
(11:04:07) INFO:    [DownloadManager]:  gog-redist added to download manager finished.
(11:04:07) INFO:    [DownloadManager]:  gog-redist removed from download manager.
(11:04:08) INFO:    [Legendary]:        Game list updated, got 416 games & DLCs
(11:04:08) INFO:    [WineDownloader]:   Updating wine versions info
(11:04:08) INFO:    [WineDownloader]:   Fetching upstream information...
(11:04:09) INFO:    [Backend]:          Starting the Download Queue
(11:04:09) INFO:    [WineDownloader]:   wine versions updated
(11:04:13) INFO:    [Gog]:              Saved games data
(11:04:13) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(11:04:13) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(11:04:13) INFO:    [Gog]:              Found 0 game(s) to update
(11:04:13) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(11:04:16) INFO:    [Legendary]:        Found 0 games to update
(11:04:16) INFO:    [Nile]:             Looking for updates...
(11:04:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(11:04:17) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki datout of all accoubts and logged back in and nothing changed.a for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Youtubers Life 2
(11:04:17) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Youtubers Life 2
(11:04:18) INFO:    [Nile]:             Getting more details
(11:04:18) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.fc36e6d2-9ee9-4ff8-a5f5-1600eb62bb9d
(11:04:18) INFO:    [Nile]:             Getting more details
(11:04:18) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.fc36e6d2-9ee9-4ff8-a5f5-1600eb62bb9d
(11:04:18) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(11:04:18) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(11:04:18) ERROR:   [Frontend]:         Cannot get game info
(11:04:18) ERROR:   [Frontend]:         Cannot get game info
(11:04:18) ERROR:   [Frontend]:         Cannot get game info
(11:04:19) DEBUG:   [Backend]:          SteamDeck data for 1493760 {"success":1,"results":{"appid":1493760,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigNotFullyFunctional"},{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}
(11:04:19) DEBUG:   [Backend]:          ProtonDB data for 1493760 {"bestReportedTier":"platinum","confidence":"low","score":0.15,"tier":"silver","total":4,"trendingTier":"silver"}
(11:04:19) ERROR:   [Frontend]:         Cannot get game info
(11:04:19) DEBUG:   [Backend]:          ProtonDB data for 1493760 {"bestReportedTier":"platinum","confidence":"low","score":0.15,"tier":"silver","total":4,"trendingTier":"silver"}
(11:04:19) DEBUG:   [Backend]:          SteamDeck data for 1493760 {"success":1,"results":{"appid":1493760,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigNotFullyFunctional"},{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}
(11:14:20) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Go to ' try to play any/ install game and the error comes up.
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

i expect to be able to install or just play a game but i cant.

### Heroic Version 2.14.1

Latest Stable

### System Information

- OS : steam deck latest firmware3.5.19 holo

**Comment by CommandMC** [comment] 2024-07-22 01:01
Amazon changed something behind the scenes. Please follow the steps outlined in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3816#issuecomment-2156766034. Alternatively, wait for the next Heroic release (which should be in the next few days)

Closing this for now as it is a duplicate of the issue above, and resolved on main

**Closed by CommandMC** 2024-07-22 01:01 UTC
Labels: bug:unconfirmed
