### ISSUE TITLE
Downloading/Installing Games

### ISSUE THREAD

**Issue by PaffcioStudio** [Heroic-Games-Launcher/HeroicGamesLauncher#2987] opened 2023-08-14 13:08 UTC
### Problem description

After using HGL for several days, I have one idea. It is quite tiresome that when I want to download something from GoG or Prime Games, the program keeps offering me the Epic Games localization when installing from these stores. Is there a chance that a default path for each of the stores will be added to the HGL settings (like "Default installation path")? I.e. separately for Epic, GoG and Prime, so that I don't have to change it manually each time. 

### Feature description

The HGL program could check by just the address of the bookmark in the library and adjust the installation path based on that. That's the only thing missing for me. Overall good job, Heroic Games project I really like.

**Comment by imLinguin** [comment] 2023-08-14 18:51
I guess this is pretty much duplicate of #2955

**Closed by imLinguin** 2023-08-14 18:51 UTC
Labels: feature-request
