### ISSUE TITLE
Unable to add special charators to Game/App Title

### ISSUE THREAD

**Issue by FeedTheChunk** [Heroic-Games-Launcher/HeroicGamesLauncher#3939] opened 2024-08-11 23:00 UTC
### Describe the bug

When trying to enter a game name that contains special characters, like ! for example, you are unable.  An example game is Clank!  Entering just Clank finds a completely different game.

### Add logs

```text
n/a
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Should be able to add special characters in the Game Title.

### Screenshots

![image](https://github.com/user-attachments/assets/e87514e7-ffb7-46d6-a1fb-282c868376a7)

### Heroic Version

Latest Stable (Flatpak)

### System Information

CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600K
Memory: 67.2 GB (used: 7.6 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation AD107 [GeForce RTX 4060]
    IDs: D=2882 V=10de SD=13e3 SV=196e
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770]
    IDs: D=a780 V=8086 SD=undefined SV=undefined
    Driver: undefined
OS: Ubuntu 24.04 LTS (Noble Numbat) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.0 Will A. Zeppeli

**Comment by arielj** [comment] 2024-08-11 23:05
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3757

**Closed by arielj** 2024-08-11 23:05 UTC
Labels: bug:unconfirmed
