### ISSUE TITLE
Button to clear "Recently Played"

### ISSUE THREAD

**Issue by pupilo-py** [Heroic-Games-Launcher/HeroicGamesLauncher#1326] opened 2022-05-16 13:24 UTC
### Feature description

![image](https://user-images.githubusercontent.com/58078395/168602565-917508c4-9f6c-438c-8ae1-a0761bda35de.png)
Of course the clear button won't be an X, it's just an example.

### Additional information

It's not something that is sorely needed, but I would like it implemented if you can.

**Comment by pupilo-py** [comment] 2022-05-16 18:44
Please do not answer my request, as I want to try to contribute to the project by adding this myself. I believe I can do it, I'm looking at the code and I'll try to make a pull request with this improvement.

**Comment by flavioislima** [comment] 2022-05-16 20:05
> Please do not answer my request, as I want to try to contribute to the project by adding this myself. I believe I can do it, I'm looking at the code and I'll try to make a pull request with this improvement.

Sounds good. Let us know if you need any help.
You can also Go to our discord under the development channel. 👍

**Comment by arielj** [comment] 2022-05-16 22:19
I wonder if you want to try this one instead https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1319, I'm not sure how common is to clear the complete list (also you can kinda work around that by setting the number of recently played in the settings to 1 and after starting a game it will store that one and remove the rest)

I imagine what you want to do is remove unwanted stuff from that list and being able to remove them 1 by 1 is more flexible maybe?

**Comment by pupilo-py** [comment] 2022-05-17 00:59
> I wonder if you want to try this one instead #1319, I'm not sure how common is to clear the complete list (also you can kinda work around that by setting the number of recently played in the settings to 1 and after starting a game it will store that one and remove the rest)
> 
> I imagine what you want to do is remove unwanted stuff from that list and being able to remove them 1 by 1 is more flexible maybe?

I thought about it myself, it's better than cleaning everything, but it also makes room to clean everything. We could put these ideas together, putting the individual ones to remove as favorites and also a button to clear everything if you want.

**Comment by pupilo-py** [comment] 2022-05-17 01:05
To be honest, folks. I want to contribute to the project with code in some way. I was happy that by the types of technology, I can understand the code as I am familiar with JavaScript, HTML and CSS.

I haven't programmed for a real serious project yet, and I wanted to be able to do that to feel like a real programmer and improve myself, as well as help me in the job market.

This would be a way to help the project and help me emotionally and professionally.

**Comment by flavioislima** [comment] 2022-05-20 13:52
closing since its a duplicate of #1319

**Closed by flavioislima** 2022-05-20 13:52 UTC
Labels: good first issue, feature request
