### ISSUE TITLE
Not installing from Epic Games (not fetching correct installer from epic)

### ISSUE THREAD

**Issue by pgerlatzek** [Heroic-Games-Launcher/HeroicGamesLauncher#3804] opened 2024-06-06 10:24 UTC
### Describe the bug

HGL does not fetch the game installer (install files) for Dragon Age: Inquisition – Game of the Year Edition.
It only says some generic 1kb file size, on the game page it does not display any information about the game, the game size etc.
For other games it works.

Also, often the correct store page for games from EPIC Games is not opened.

HGL version 2.14.1 (but also present in previous versions)
System Windows 10

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/130367798/7bebd5be-41d7-4aa7-9b28-2c0d7b31eaad)

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/130367798/00999e2c-c678-41a8-8f81-3f6efaa5af5c)

### Add logs

```text
No log file is created for this problem
```

### Steps to reproduce

1. Go to 'Dragon Age: Inquisition – Game of the Year Edition in the HGL Epic Games Library'
2. Click on 'Install Game'
3. Pop Up will show install game with 1kb file size
4. Install game
5. See error: after it trying to install, it doesn't install

### Expected behavior

It should install the game

### Heroic Version

main branch from GitHub

### System Information

- Windows 10
- HGL version 2.14.1

**Comment by arielj** [comment] 2024-06-06 12:14
duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3762

**Closed by arielj** 2024-06-06 12:14 UTC
Labels: bug:unconfirmed
