### ISSUE TITLE
"Epic Alternative Login Method" login page accesibility (AppImage version)

### ISSUE THREAD

**Issue by RafaelLinux** [Heroic-Games-Launcher/HeroicGamesLauncher#2244] opened 2022-12-21 23:11 UTC
### Problem description

The "Epic Alternative Login Method"  form field is barely visible. I was not able to locate where to paste auth code before viewing the page https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Epic-Alternative-Login
In that  page, form field is clearly visible
![imagen](https://user-images.githubusercontent.com/13048959/209020158-febf4a8b-b219-4f5e-ac6f-e9b0ba430e84.png)

and this is what I see in my PC:
![imagen](https://user-images.githubusercontent.com/13048959/209020335-7b42d55e-ac18-40c1-895a-837f849ee02a.png)

Thanks

### Feature description

Only change colours is needed.

**Comment by RafaelLinux** [comment] 2022-12-22 11:47
Version is the latest one downloaded yesterday, before opening issue (I'm not in my PC now).

**Comment by arielj** [comment] 2022-12-22 12:12
> You need to add more information on the issue, we do not even know which HEroic version you are using.

@flavioislima I understand the issue is that the input field to paste the auth code is the same color as the background and really hard to see

I can confirm that in the main branch too

**Comment by RafaelLinux** [comment] 2022-12-22 13:51
> @flavioislima I understand the issue is that the input field to paste the auth code is the same color as the background and really hard to see

Exactly. I thought I wrote issue it clearly, but it seems my explanation was not so clear.

**Comment by arielj** [comment] 2023-01-27 13:05
fixed in the main branch

**Closed by arielj** 2023-01-27 13:05 UTC
Labels: bug:confirmed, good first issue
