### ISSUE TITLE
Handle installing games on external drives similiarly to Steam

### ISSUE THREAD

**Issue by thatLeaflet** [Heroic-Games-Launcher/HeroicGamesLauncher#4206] opened 2024-12-26 00:14 UTC
### Problem description

When it comes to adding games installed to an external drive, doing so on Heroic is a pain. First, you must change the default game install location and wine prefix location. Then you must individually change the game install location for every game to to its preexisting install location.

### Feature description

I would like for Heroic to handle this problem similarly to Steam. On Steam, you simply choose a folder to serve as your library. In this folder, Steam will then install its games and wine prefixes. Steam will also automatically discover installed games on this drive.

To compare, on heroic you have to complete 2+n actions when installing Heroic, where n is the number of games you have installed on the external drive. In contrast, for Steam all you have to do is tell Steam where your external library is stored and it handles the rest automatically.

**Comment by arielj** [comment] 2024-12-26 02:40
I think this is a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3377

**Closed** 2024-12-26 02:42 UTC
Labels: feature-request
