### ISSUE TITLE
Heroic fails to load libraries if some game doesn't contain keyImages in its metadata.

### ISSUE THREAD

**Issue by KillYourFM** [Heroic-Games-Launcher/HeroicGamesLauncher#313] opened 2021-04-17 11:21 UTC
**Describe the bug**
Launching Heroic after installation and login results in what seems like an endless "hanging" loading screen. 

**To Reproduce**

1. Install .deb (latest release [mod note: 1.5.7]) package on Pop OS 20.10
2. Obtain SID from Epic Games store and login to Heroic

**Expected behavior**
Main menu/games library would display after several seconds.

**Screenshots**

![Screenshot from 2021-04-17 13-19-32](https://user-images.githubusercontent.com/47599547/115111258-be760280-9f7f-11eb-94e4-9389d041795d.png)

**Desktop (please complete the following information):**

- OS: Pop OS
- Version 20.10
- Game: N/A
- Wine/Proton version: Unsure (Steam is installed)

**Comment by adityaruplaha** [comment] 2021-04-17 12:21
Can you get a log output by running Heroic from terminal?

**Comment by KillYourFM** [comment] 2021-04-17 12:51
> Can you get a log output by running Heroic from terminal?

Here's what I get: 

Error occurred in handler for 'readFile': TypeError: Cannot read property 'filter' of undefined
    at /opt/heroic/resources/app.asar/build/legendary_utils/library.js:65:47
    at Array.map (<anonymous>)
    at Object.<anonymous> (/opt/heroic/resources/app.asar/build/legendary_utils/library.js:52:22)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/heroic/resources/app.asar/build/legendary_utils/library.js:5:58)

**Comment by flavioislima** [comment] 2021-04-17 19:03
Hi Jason! :)

Well, do you have games on epic games already?
Have you used Legendary or Heroic before?
If yes, try to rename/remove the following folder:
`.config/heroic`

if doesnt work, try to do the same with `.config/legendary`

it might be some corrupted config file.

You can also check `.config/heroic/config.json` and check if the JSON is valid and well formated. Sometimes it can have an extra bracket and we are investigating why this happens but can happen from time to time.

**Comment by KillYourFM** [comment] 2021-04-18 06:35
Thanks for the assist @flavioislima! Unfortunately, none of the above seemed to work. 
-I do have a large library
-I hadn't used Legendary or Heroic until this first attempt yesterday. 

I tried removing the .config/heroic and .config/legendary folders and then entering my SID again. It got to the same stage where the main screen says "Loading games library" and then it just hangs on the spinning loading icon. 

And the json file looks right: 

{
  "defaultSettings": {
    "customWinePaths": [],
    "defaultInstallPath": "/home/jason/Games/Heroic",
    "language": "en",
    "maxWorkers": 0,
    "otherOptions": "",
    "showFps": false,
    "useGameMode": false,
    "userInfo": {
      "epicId": "3760124bff124de3aacf0d1beff15305",
      "name": "jason"
    },
    "winePrefix": "/home/jason/.wine",
    "wineVersion": {
      "bin": "/usr/bin/wine",
      "name": "Wine - wine-5.0 (Ubuntu 5.0-3ubuntu1)"
    }
  }
}


So I'm not sure what to do...

**Comment by adityaruplaha** [comment] 2021-04-18 07:34
> And the json file looks right (I'll attach it). 
> ![Screenshot from 2021-04-18 08-36-28](https://user-images.githubusercontent.com/47599547/115136623-30525880-a021-11eb-86ac-373232cf96c7.png)
> 
> So I'm not sure what to do...

Neither am I really. I did recently refactor did this code but your config looks okay. No reason for this issue.

1. Can you reproduce on the latest commit and post another log? 
2. Does this happen everytime? If no it might be a race condition.
3. Is your home partition on a HDD or SSD?

**Comment by KillYourFM** [comment] 2021-04-18 09:38
> Can you reproduce on the latest commit and post another log?
I'd be happy to, provided you can walk me through how to do that. (or link me to a general guide)

> Does this happen everytime? If no it might be a race condition.
It does seem to happen at every launch. I've never successfully loaded my library. 

> Is your home partition on a HDD or SSD?
An NVME SSD. 

Someone in my Discord group suggested that maybe it's a space allocation problem? I have an Epic Games press account, so _theoretically_, I "own" about 98% of the games available in the store. Could this be an issue?

**Comment by KillYourFM** [comment] 2021-04-18 10:15
UPDATE! 

My friend suggested registering a new account with Epic Games and trying to launch Heroic with that login. It works, instantly! 

he also supports the theory that it might be some kind of space allocation issue. Worth looking into? 

This is good news hopefully! Please let me know and thanks for working through this with me.

**Comment by flavioislima** [comment] 2021-04-18 10:16
Might be. I never tested heroic with such a huge library. So probably it is taking a long time to list the games and then heroic, or legendary process is hanging.

In this case we will need to isolate the issue.
If possible, try to run only legendary on your terminal and list your games. Then try to check if it hangs or take too much time to list them.

Thanks

**Comment by KillYourFM** [comment] 2021-04-18 10:27
> In this case we will need to isolate the issue.
> If possible, try to run only legendary on your terminal and list your games. Then try to check if it hangs or take too much time to list them.

I removed everything, installed the legendary .deb, and successfully logged in and spit out list-games. Now, should I install Heroic on top and try that?

**Comment by adityaruplaha** [comment] 2021-04-18 11:17
Its probably due to Heroic failing to load the humongous amount of data needed into memory.

**Comment by KillYourFM** [comment] 2021-04-18 11:39
For what it's worth, Legendary lists 99 games.

**Comment by Flonky** [comment] 2021-04-18 11:47
Nope its not the amount of games, i have more than 100 games and it works just fine

**Comment by adityaruplaha** [comment] 2021-04-18 11:49
I have a bit less than 200 and it still loads just fine. Weird.
@KillYourFM how many games are we talking here though?

**Comment by Flonky** [comment] 2021-04-18 11:51
Got 121 games in my lib and it loads fine too.
Although the press account might cause issues i guess

**Comment by adityaruplaha** [comment] 2021-04-18 11:53
@KillYourFM do you happen to have any pre-release games associated with your account? Cuz the error says that Legendary doesn't have image metadata for a game.

**Comment by flavioislima** [comment] 2021-04-18 13:02
I also have more than a 100. I think this is some edge case about some game that don't bring the right info and then heroic breaks. We had this before with some games that don't have a cover image.

**Comment by flavioislima** [comment] 2021-04-21 20:21
so, I think I found the issue. For some reason some game, or maybe can be a addon or tool, do not come with the Keyimage on the metadata object. So thats why the error.
should be a quick fix for the next release :)

**Comment by adityaruplaha** [comment] 2021-04-22 17:52
@KillYourFM can you test on adityaruplaha/HeroicGamesLauncher:keyimageshotfix? I think the issue might be fixed. Unfortunately you'll have to build it yourself, my connection is too slow to upload such a large binary.

**Comment by Flonky** [comment] 2021-04-23 14:55
Compiled the version by @adityaruplaha.
You can download it [here](https://drive.google.com/file/d/16U4hmqPws-ZnBDxjbTxHbriFHp5dOLX1/view?usp=sharing)

**Comment by KillYourFM** [comment] 2021-04-24 06:06
It loads INSTANTLY! Thank you @Flonky and @adityaruplaha and @flavioislima for your help. 
So happy to be a Patron of this software!

**Comment by adityaruplaha** [comment] 2021-04-24 06:18
I love how this was literally 1 line changed. Exactly 4 characters.

Also @KillYourFM we'll close this issue only after the fix gets merged to main.

**Comment by flavioislima** [comment] 2021-04-24 06:45
> It loads INSTANTLY! Thank you @Flonky and @adityaruplaha and @flavioislima for your help. 
> So happy to be a Patron of this software!

Thanks for finding the issue and providing the logs as well. And of course, for supporting our software 😁

Thanks @adityaruplaha for the quick fix and @Flonky for the build. 😀

**Comment by KillYourFM** [comment] 2021-04-24 07:04
> I love how this was literally 1 line changed. Exactly 5 characters.
> 
> Also @KillYourFM we'll close this issue only after the fix gets merged to main.

Roger that, I got over-eager :D

**Closed** 2021-04-24 08:41 UTC
Labels: bug
