### ISSUE TITLE
Closing heroic while Winetricks is opened leaves Winetricks open

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1997] opened 2022-11-06 04:06 UTC
### Describe the bug

I Winetricks is running from the option in the settings, users can close Heroic and Winetricks stays open.

### Add logs

Nothing relevant

### Steps to reproduce

1. Go to any game's settings that uses wine (non-native linux)
2. Click on the WINETRICKS button
3. Wait until Winetricks shows up
4. Close Heroic
5. Winetricks is still open

### Expected behavior

As a user, I would expect that closing Heroic will close Winetricks too.

Maybe even warn me that Winetricks is running before closing to confirm the exit?

### System Information

- OS [e. g. "Ubuntu"]: Linux Mint
- Heroic Version [e. g. 2.1.1]: main and beta

**Comment by flavioislima** [comment] 2022-11-06 15:29
I noticed thst as well.
I also think that the winetricks dialog in heroic is broken visually and the dialog should not have a way of closing it while winetricks is opened. Right now we show the close button on it.

**Comment by flavioislima** [comment] 2022-12-16 21:43
I think now that this is actually a feature and not a bug.

Imagine if the person closes heroic accidentally in the middle of a wine tricks operation? Ideally, the operation should be finished. Also, we need to think That wine tricks is a tool that is not part of heroic, is an external one. So I believe we should keep this behavior.

**Closed by flavioislima** 2022-12-16 21:43 UTC
