### ISSUE TITLE
Error installing DXVK/VKD3D on new install

### ISSUE THREAD

**Issue by bobbyhundreds** [Heroic-Games-Launcher/HeroicGamesLauncher#3255] opened 2023-11-22 12:32 UTC
### Describe the bug

I just did a fresh install of Heroic on Garuda Linux KDE and get the following warning when I open the application:
"Error installing DXVK/VKD3D! Please check your connection!"
I also tried on Endeavour OS and got the same warning.

### Add logs

```text
(12:18:25) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:18:25) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:18:25) INFO:    [Connection]:       Connectivity: check-online
(12:18:25) INFO:    [Connection]:       Pinging external endpoints
(12:18:25) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(12:18:26) WARNING: [Backend]:          Protocol already registered.
(12:18:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:18:26) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jon/.config/heroic/gog_store/auth.json --version
(12:18:26) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jon/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(12:18:26) INFO:    [Connection]:       Connectivity: online
(12:18:26) INFO:    [Backend]:          User Not Found, removing it from Store
(12:18:26) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(12:18:26) INFO:    [Backend]:          
System Information:
CPU: 12x AMD Ryzen 5 5600X 6-Core Processor
Memory: 67.33 GB (used: 3.23 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M]
    IDs: D=73ff V=1002 SD=6501 SV=1eae
    Driver: amdgpu
OS: Garuda Linux 6.6.2-zen1-1-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(12:18:26) INFO:    [Backend]:          Loading Screen Ready
(12:18:26) INFO:    [Backend]:          Frontend Ready
(12:18:26) INFO:    [Backend]:          Checking for new Heroic Updates
(12:18:26) INFO:    [Backend]:          Checking for current version changelog
(12:18:26) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:18:28) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(12:18:28) INFO:    [Winetricks]:       Downloading Winetricks
(12:18:28) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-v2.10
(12:18:29) INFO:    [DXVKInstaller]:    Updating dxvk-nvapi to: dxvk-nvapi-v0.6.4
(12:18:29) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.3
(12:18:29) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz. 
Error: Error: Request failed with status code 401
(12:18:29) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Failed to get headers
    at downloadFile$2 (/opt/Heroic/resources/app.asar/build/electron/main.9bb8a6b7.js:127:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(12:18:30) INFO:    [WineDownloader]:   Updating wine versions info
(12:18:30) INFO:    [WineDownloader]:   Fetching upstream information...
(12:18:31) INFO:    [Backend]:          Starting the Download Queue
(12:18:31) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.10/vkd3d-proton-v2.10.tar.xz
(12:18:31) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.10/vkd3d-proton-v2.10.tar.xz
(12:18:31) INFO:    [DXVKInstaller]:    downloaded vkd3d
(12:18:31) INFO:    [DXVKInstaller]:    extracting vkd3d
(12:18:31) INFO:    [DXVKInstaller]:    vkd3d updated!
(12:18:31) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/jp7677/dxvk-nvapi/releases/download/v0.6.4/dxvk-nvapi-v0.6.4.tar.gz
(12:18:31) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/jp7677/dxvk-nvapi/releases/download/v0.6.4/dxvk-nvapi-v0.6.4.tar.gz
(12:18:31) INFO:    [DXVKInstaller]:    downloaded dxvk-nvapi
(12:18:31) INFO:    [DXVKInstaller]:    extracting dxvk-nvapi
(12:18:31) INFO:    [DXVKInstaller]:    dxvk-nvapi updated!
(12:18:34) INFO:    [WineDownloader]:   wine versions updated
(12:27:22) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:27:22) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jon/.config/heroic/gog_store/auth.json --version
(12:27:22) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jon/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(12:27:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/jon/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:27:27) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/jon/.config/heroic/gog_store/auth.json --version
(12:27:27) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/jon/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

### Steps to reproduce

Open Heroic Launcher
Get warning

### Expected behavior

Cannot install games.

### Screenshots

![Screenshot_20231122_122934](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/151745157/a617766c-0fb9-4378-a03b-6dab4fc29989)

### Heroic Version

Latest Stable

### System Information

- OS Garuda KDE
- also Endeavour OS

**Comment by redromnon** [comment] 2023-11-23 06:18
Can you try launching Heroic again? I'm pretty sure the link should work fine now.

I tried it today on my machine and it works, here's my log:
```
(11:41:19) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz
(11:41:19) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz
(11:41:19) INFO:    [DXVKInstaller]:    downloaded dxvk
(11:41:19) INFO:    [DXVKInstaller]:    extracting dxvk
(11:41:20) INFO:    [DXVKInstaller]:    dxvk updated!
```

**Comment by bobbyhundreds** [comment] 2023-11-23 17:36
> Can you try launching Heroic again? I'm pretty sure the link should work fine now.
> 
> I tried it today on my machine and it works, here's my log:
> 
> ```
> (11:41:19) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz
> (11:41:19) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz
> (11:41:19) INFO:    [DXVKInstaller]:    downloaded dxvk
> (11:41:19) INFO:    [DXVKInstaller]:    extracting dxvk
> (11:41:20) INFO:    [DXVKInstaller]:    dxvk updated!
> ```

Thanks brother, I got home just now and reinstalled it on EndeavourOS and whoosh, we're back in action.
By the way, I'm in the UK, but my partner is from Pune, what a small world. :)

**Comment by redromnon** [comment] 2023-11-24 06:43
Closing since the issue is fixed.

**Closed by redromnon** 2023-11-24 06:43 UTC
Labels: bug:unconfirmed
