### ISSUE TITLE
Flatpak version doesn't inhibit screen saver

### ISSUE THREAD

**Issue by bacteriostat** [Heroic-Games-Launcher/HeroicGamesLauncher#3451] opened 2024-01-18 07:33 UTC
### Describe the bug

The flatpak version doesn't include `org.freedesktop.ScreenSaver` permission. I added it manually but it didn't change anything so it looks like some extra work needs to be done to make it working for the flatpak. I also use Steam via flatpak and it inhibits the screen saver.

### Add logs

```text
(13:01:18) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:01:18) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:01:18) INFO:    [Connection]:       Connectivity: check-online
(13:01:18) INFO:    [Connection]:       Pinging external endpoints
(13:01:19) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(13:01:19) WARNING: [Backend]:          Failed to register protocol with OS.
(13:01:19) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/provost/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:01:20) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/provost/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(13:01:20) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/provost/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:01:20) INFO:    [Connection]:       Connectivity: online
(13:01:20) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:01:20) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 4800H with Radeon Graphics
Memory: 32.98 GB (used: 5.13 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon RX Vega 6 (Ryzen 4000/5000 Mobile Series)]
    IDs: D=1636 V=1002 SD=09f5 SV=1028
    Driver: amdgpu
  GPU 1:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    IDs: D=731f V=1002 SD=09f5 SV=1028
    Driver: amdgpu
OS: Arch Linux 6.6.11-201.fsync.fc39.x86_64 (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.12.0 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(13:01:20) INFO:    [Frontend]:         Refreshing undefined Library
(13:01:20) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:01:20) INFO:    [Legendary]:        Refreshing library...
(13:01:20) INFO:    [Legendary]:        Refreshing Epic Games...
(13:01:20) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(13:01:20) INFO:    [Backend]:          Frontend Ready
(13:01:20) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:01:20) INFO:    [Gog]:              Found 0 game(s) to update
(13:01:20) INFO:    [Backend]:          Checking for current version changelog
(13:01:20) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:01:21) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/provost/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:01:21) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/provost/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:01:22) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(13:01:22) INFO:    [Winetricks]:       Downloading Winetricks
(13:01:24) INFO:    [WineDownloader]:   Updating wine versions info
(13:01:24) INFO:    [WineDownloader]:   Fetching upstream information...
(13:01:25) INFO:    [Backend]:          Starting the Download Queue
(13:01:26) INFO:    [WineDownloader]:   wine versions updated
(13:01:28) INFO:    [Legendary]:        Found 0 games to update
```

### Steps to reproduce

1. Launch a game using the launcher
2. Play with a controller so that no keyboard or mouse interrupt happens.
3. Wait for the screen saver to kick in.

### Expected behavior

Any games launched should inhibit the screen saver

### Heroic Version

Latest Stable (Flatpak)

### System Information

Distro: Arch Linux
DE: KDE Plasma 5.27 (Wayland)

**Comment by arielj** [comment] 2024-01-29 22:42
This seems to be a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2644

**Closed** 2024-01-31 16:30 UTC
Labels: bug:unconfirmed
