### ISSUE TITLE
Unable to select game components by clicking on a checkbox

### ISSUE THREAD

**Issue by dklementowski** [Heroic-Games-Launcher/HeroicGamesLauncher#1446] opened 2022-06-06 21:04 UTC
### Describe the bug

I'm not sure if the problem is already known, but I couldn't find existing issue.
I'm using Flatpak version from stable channel and haven't tried beta.

When installing game, clicking on a component checkbox always selects first item from the list. I can still check the component I want by using keyboard or gamepad. I recorded the behavior: https://streamable.com/5po8ln

### Add logs

(22:48:51) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:48:51) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:48:51) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:48:51) INFO:    [Backend]:

Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.18.1-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 2700 Eight-Core Processor @3.2 GOVERNOR: schedutil
RAM: Total: 15.6 GiB Available: 12.41 GiB
GRAPHICS: GPU0: Device 2489  VRAM: 32MB DRIVER:  
PROTOCOL: x11

(22:48:51) INFO:    [Gog]:             Getting data about the user
(22:48:51) INFO:    [Gog]:             Refreshing access_token
(22:48:52) WARNING: [Backend]:         Failed to register protocol with OS.
(22:48:52) INFO:    [Gog]:             Token refreshed successfully
(22:48:52) INFO:    [Gog]:             Saved user data to config
(22:48:53) INFO:    [Frontend]:        Refreshing Library
(22:48:53) INFO:    [Legendary]:       Refreshing library...
(22:48:53) INFO:    [Legendary]:       Refreshing Epic Games...
(22:48:53) INFO:    [Gog]:             Getting GOG library
(22:48:53) INFO:    [Gog]:             Number of library pages: 1
(22:48:53) INFO:    [Gog]:             Saved games data
(22:48:53) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(22:48:54) INFO:    [Legendary]:       Updating game list
(22:48:54) INFO:    [Legendary]:       Game List Updated
(22:48:54) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(22:48:54) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(22:48:54) INFO:    [Backend]:         Downloaded Winetricks
(22:48:56) INFO:    [Legendary]:       Found 0 game(s) to update
(22:48:56) INFO:    [Gog]:             Found 0 game(s) to update
(22:49:12) INFO:    [Backend]:         Changing Language to: en
(22:49:16) INFO:    [Legendary]:       Getting Info from Epic API
(22:49:16) DEBUG:   [Legendary]:       Using cached install info
(22:49:18) DEBUG:   [Legendary]:       Using cached install info
(22:49:18) DEBUG:   [Legendary]:       Using cached install info
(22:49:18) WARNING: [Backend]:         default is not writable
(22:51:23) DEBUG:   [Legendary]:       Using cached install info
(22:51:23) DEBUG:   [Legendary]:       Using cached install info
(22:51:23) WARNING: [Backend]:         default is not writable
(22:52:02) DEBUG:   [Legendary]:       Using cached install info
(22:52:02) DEBUG:   [Legendary]:       Using cached install info
(22:52:02) WARNING: [Backend]:         default is not writable
(22:52:17) DEBUG:   [Legendary]:       Using cached install info
(22:52:18) DEBUG:   [Legendary]:       Using cached install info
(22:52:18) DEBUG:   [Legendary]:       Using cached install info
(22:52:18) WARNING: [Backend]:         default is not writable

### Steps to reproduce

1. Go to the installation of a game that has additional components like languages or extensions
2. Click on a component that is not the first one on the list to try to enable it
3. The first component of the list is checked

### Expected behavior

Should allow to choose component when clicking on it

### Screenshots

https://streamable.com/5po8ln

### System Information

- OS [e. g. "Ubuntu"]: Arch BTW
- Heroic Version [e. g. 2.1.1]: 2.3.7 Brook

**Comment by Etaash-mathamsetty** [comment] 2022-06-07 01:25
duplicate of #1427 ?

**Comment by dklementowski** [comment] 2022-06-07 02:15
> duplicate of #1427 ?

It doesn't like one to me. I didn't mention actually downloading a game with selected additional content, but rather the UI behavior.

**Closed** 2022-06-10 22:09 UTC
