### ISSUE TITLE
Application doesn't load on first launch

### ISSUE THREAD

**Issue by SnowzNZ** [Heroic-Games-Launcher/HeroicGamesLauncher#2656] opened 2023-04-28 05:18 UTC
### Describe the bug

When first opening Heroic, nothing loads in, its just a blank application. But after fully closing it and making sure its closed in tray and task manager and reopening it, it finally loads in.

### Add logs

```text
(17:16:23) INFO:    [Connection]:       Connectivity: check-online
(17:16:23) INFO:    [Connection]:       Pinging external endpoints
(17:16:23) INFO:    [Legendary]:        Running command: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:16:23) INFO:    [Legendary]:        Legendary location: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(17:16:23) INFO:    [Gog]:              GOGDL location: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:16:23) INFO:    [Gog]:              GOGDL location: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:16:23) WARNING: [Backend]:          Protocol already registered.
(17:16:23) INFO:    [Connection]:       Connectivity: online
(17:16:23) INFO:    [Gog]:              Running command: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\jackson\AppData\Roaming\heroic\gog_store\auth.json --version
(17:16:23) INFO:    [Backend]:          Loading Screen Ready
(17:16:23) INFO:    [Frontend]:         Refreshing Library
(17:16:23) INFO:    [Legendary]:        Refreshing library...
(17:16:23) INFO:    [Legendary]:        Refreshing Epic Games...
(17:16:23) INFO:    [Legendary]:        Found 0 games to update
(17:16:23) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs
(17:16:23) INFO:    [Gog]:              Found 0 game(s) to update
(17:16:23) INFO:    [Backend]:          Frontend Ready
(17:16:23) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:16:23) INFO:    [Legendary]:        Refreshing library...
(17:16:23) INFO:    [Legendary]:        Game list updated, got 14 games & DLCs
(17:16:23) INFO:    [Backend]:          Checking for new Heroic Updates
(17:16:24) INFO:    [Frontend]:         Force Update
(17:16:24) INFO:    [Backend]:          Checking for current version changelog
(17:16:24) INFO:    [Legendary]:        Running command: C:\Users\jackson\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(17:16:28) WARNING: [Backend]:          Could not determine System Info
(17:16:28) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Open Heroic
2. Application doesnt load
3. Close Heroic
4. Reopen Heroic
5. Application loads in

### Expected behavior

I expect the application to load in when opening it the first time.

### Screenshots

*I will provide a screenshot when I next restart my PC.*

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 11 Pro (22621)
- CPU: i5 11400F
- RAM: 2x8GB 3200MHz
- GPU: RTX 3060

**Comment by Nocccer** [comment] 2023-04-28 09:25
Duplicate of #2604.

**Closed** 2023-04-28 09:26 UTC
