### ISSUE TITLE
Support for Humble Bundle

### ISSUE THREAD

**Issue by lgcavalheiro** [Heroic-Games-Launcher/HeroicGamesLauncher#2274] opened 2022-12-28 03:22 UTC
### Feature description

Hi! I was having a look at the source code for both heroic and lutris, and i was wondering if you guys would be interested in adding support for Humble Bundle, if so, i could try giving it a shot if that's ok with you  :

**Comment by arielj** [comment] 2022-12-28 03:25
Closing as a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1223

@lgcavalheiro we are happy to receive contributions to add support for it

**Closed by arielj** 2022-12-28 03:25 UTC
