### ISSUE TITLE
Add support for multiple accounts

### ISSUE THREAD

**Issue by quinnzbellz** [Heroic-Games-Launcher/HeroicGamesLauncher#1782] opened 2022-09-05 01:02 UTC
### Feature description

It would be really cool if you could add support for multiple epic and gog accounts within the app, that way friends can share accounts, or if for some reason you have multiple you can use all of them.

**Comment by arielj** [comment] 2022-09-05 01:33
Closing, duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1534

**Closed by arielj** 2022-09-05 01:33 UTC
