### ISSUE TITLE
Games fails to launch when Steam Runtime is enabled

### ISSUE THREAD

**Issue by xdevc512l** [Heroic-Games-Launcher/HeroicGamesLauncher#2183] opened 2022-12-12 03:09 UTC
### Describe the bug

Borderlands 3 doesn't launch when Steam runtime is enabled.

### Add logs

```text
System Info:

Heroic Version: 2.5.1 Yamato

Legendary Version:  0.20.31 Dark Energy (hotfix #5)

GOGdl Version: 0.5

OS: Freedesktop SDK KERNEL: 6.0.11-300.fc37.x86_64 ARCH: x64

CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil

RAM: Total: 31.22 GiB Available: 17.76 GiB

GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB  

PROTOCOL: wayland

Game Settings: {

	"autoInstallDxvk": false,

	"autoInstallVkd3d": false,

	"preferSystemLibs": false,

	"enableEsync": false,

	"enableFSR": false,

	"enableFsync": true,

	"launcherArgs": "-nostartupmovies -nosplash",

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"savesPath": "{UserDir}/My Games/Borderlands 3/Saved/SaveGames/{EpicID}/",

	"showFps": false,

	"showMangohud": true,

	"useGameMode": true,

	"useSteamRuntime": true,

	"language": "",

	"wineVersion": {

		"bin": "/mnt/SATA-SSD1/SteamLibrary/steamapps/common/Proton 7.0/proton",

		"name": "Proton - Proton 7.0",

		"type": "proton"

	},

	"winePrefix": "/mnt/SATA-SSD2/Heroic/Prefix/Borderlands3"

}

Game launched at: Mon Dec 12 2022 03:44:45 GMT+0100 (Central European Standard Time)

Legendary's config from config.ini (before Heroic's settings):

{

  "game_parameters": [],

  "game_executable": "Borderlands3.exe",

  "game_directory": "/mnt/SATA-SSD2/Heroic/Games/Borderlands3/Borderlands3",

  "launch_command": [

    "wine"

  ],

  "working_directory": "/mnt/SATA-SSD2/Heroic/Games/Borderlands3/Borderlands3",

  "user_parameters": [],

  "environment": {},

  "pre_launch_command": "",

  "pre_launch_wait": false

}

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/xdevc512l/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/mnt/SATA-SSD2/Heroic/Prefix/Borderlands3 PROTON_NO_ESYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Borderlands3 PROTON_LOG_DIR=/home/xdevc512l/.var/app/com.heroicgameslauncher.hgl /usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/gamemoderun /mnt/SATA-SSD1/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/run --filesystem=/mnt/SATA-SSD2/Heroic/Games/Borderlands3/Borderlands3 -- /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Catnip --language en --no-wine --wrapper "'/mnt/SATA-SSD1/SteamLibrary/steamapps/common/Proton 7.0/proton' run" -nostartupmovies -nosplash

Game Log:

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

bwrap: Can't chdir to /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux: No such file or directory
```

### Steps to reproduce

1. Install both Steam and Heroic from flatpak
2. Install Proton 7.0-5 from Steam and Steam Linux Runtime - Soldier
3. Set Proton 7.0-5 as default wine for Heroic
4. Install any game
5. Enable in settings the game to use Steam Runtime
6. Try to launch the game

### Expected behavior

The prefix is created and game is launched

### System Information

- OS: Fedora Workstation 37
- Heroic Version: 2.5.1 (Flatpak version)
- Wine: Proton 7.0-5

**Comment by MicahBird** [comment] 2022-12-12 04:03
I can confirm that I am experiencing the same issue when trying to play Rocket League. Likewise I'm on Fedora 37 (KDE on Wayland), using the latest Flatpak versions of both Steam and Heroic. I have also allowed the Heroic flatpak to access`~/.var/app/com.valvesoftware.Steam` with no luck.

**Comment by ArchitBhonsle** [comment] 2022-12-19 06:01
I also allowed access to the entire user file system and it still fails. Is there some way to specify the path to the steam runtime?

**Comment by MicahBird** [comment] 2022-12-19 16:56
> Is there some way to specify the path to the steam runtime?
Yep! Just go to Settings > General > Default Steam Path

**Comment by msdobrescu** [comment] 2023-01-14 18:59
I have the same issue using HGL from flatpak, but native Steam.
I see Steam path is ~/.steam/bin/steam, HGL has access to ~/.steam, but the issue persists even though I have set the path in HGL (as /home/user/.steam/bin/steam).

I have noticed in the logs that Steam soldier runtime is not found either.

Any advice?

**Comment by MicahBird** [comment] 2023-01-14 19:17
> I have the same issue using HGL from flatpak, but native Steam. I see Steam path is ~/.steam/bin/steam, HGL has access to ~/.steam, but the issue persists even though I have set the path in HGL (as /home/user/.steam/bin/steam).
> 
> I have noticed in the logs that Steam soldier runtime is not found either.
> 
> Any advice?

You most likely need to give the HGL flatpak access to your native Steam path. [This page in the docs explains how to give the HGL flatpak access to other directories.
](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/SteamDeck---Flatpak#give-permissions-to-sd-card-other-partitions-external-drives-etc) Hope this helps!

**Comment by msdobrescu** [comment] 2023-01-14 19:21
Which is the native Steam path besides ~/.steam, where it has access?
It is weird that can browse up to that, but does not list ("see") anything inside.

**Comment by Nocccer** [comment] 2023-01-14 19:30
> I have the same issue using HGL from flatpak, but native Steam.
> I see Steam path is ~/.steam/bin/steam, HGL has access to ~/.steam, but the issue persists even though I have set the path in HGL (as /home/user/.steam/bin/steam).
> 
> I have noticed in the logs that Steam soldier runtime is not found either.
> 
> Any advice?

Don't set it to this path. We just need the `.steam` path. From there we searching for everything. Can you give us general logs and game logs. They might have some information

**Comment by msdobrescu** [comment] 2023-01-14 19:48
Here is a log:

```
System Info:
Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Freedesktop SDK KERNEL: 5.15.85-mocaccino ARCH: x64
CPU: Intel Core™ i7 920 @2.67 GOVERNOR: userspace
RAM: Total: 23.47 GiB Available: 19.67 GiB
GRAPHICS: GPU0: GA104 [GeForce RTX 3060 Ti Lite Hash Rate]  VRAM: 32MB  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"useSteamRuntime": true,
	"language": "",
	"wineVersion": {
		"bin": "/home/myuser/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-43/proton",
		"name": "Proton - Proton-GE-Proton7-43",
		"type": "proton"
	},
	"winePrefix": "/home/myuser/Games/Heroic/Prefixes/Kerbal Space Program"
}

Game launched at: Sat Jan 14 2023 21:44:12 GMT+0200 (Eastern European Standard Time)

Launch aborted: Steam Runtime is enabled, but no runtimes could be found
Make sure Steam and the "SteamLinuxRuntime - Soldier" are installed

```

**Comment by Nocccer** [comment] 2023-01-14 19:52
> Here is a log:
> 
> ```
> System Info:
> Heroic Version: 2.5.2 Yamato
> Legendary Version:  0.20.31 Dark Energy (hotfix #5)
> GOGdl Version: 0.5
> OS: Freedesktop SDK KERNEL: 5.15.85-mocaccino ARCH: x64
> CPU: Intel Core™ i7 920 @2.67 GOVERNOR: userspace
> RAM: Total: 23.47 GiB Available: 19.67 GiB
> GRAPHICS: GPU0: GA104 [GeForce RTX 3060 Ti Lite Hash Rate]  VRAM: 32MB  
> PROTOCOL: x11
> 
> Game Settings: {
> 	"autoInstallDxvk": true,
> 	"autoInstallVkd3d": true,
> 	"preferSystemLibs": false,
> 	"nvidiaPrime": false,
> 	"enviromentOptions": [],
> 	"wrapperOptions": [],
> 	"showFps": false,
> 	"useGameMode": false,
> 	"useSteamRuntime": true,
> 	"language": "",
> 	"wineVersion": {
> 		"bin": "/home/myuser/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-43/proton",
> 		"name": "Proton - Proton-GE-Proton7-43",
> 		"type": "proton"
> 	},
> 	"winePrefix": "/home/myuser/Games/Heroic/Prefixes/Kerbal Space Program"
> }
> 
> Game launched at: Sat Jan 14 2023 21:44:12 GMT+0200 (Eastern European Standard Time)
> 
> Launch aborted: Steam Runtime is enabled, but no runtimes could be found
> Make sure Steam and the "SteamLinuxRuntime - Soldier" are installed
> 
> ```

First of all. If you run proton or wine, never enable steam runtime. The runtime is 99% needed only for linux native games and breaks windows versions via wine/proton most of the time. Also i would advise to not take proton or proton-ge and use wine-ge with dxvk and vkd3d. Make sure to have all wine dependecies installed (not needed on steam deck). 

If you want the runtime did you installed it via steam?

**Comment by msdobrescu** [comment] 2023-01-14 19:58
I thought it would use Steam wine/proton automatically.
I have native Steam installed. What else should be installed?

I can run fine this game under proton-ge (via HGL).

I've tried to run Fortnite and TrackMania, but they simply stop at startup, sooner or later., so I have tried several wine or proton distros.

**Comment by Nocccer** [comment] 2023-01-14 20:00
> I thought it would use Steam wine/proton automatically.
> I have native Steam installed. What else should be installed?
> 
> I can run fine this game under proton-ge (via HGL).
> 
> I've tried to run Fortnite and TrackMania, but they simply stop at startup, sooner or later., so I have tried several wine or proton distros.

Fortnite does not work on linux because of Anti-Cheat. Trackmania is ubisoft game and needs extra steps. But tm works great after.

**Comment by msdobrescu** [comment] 2023-01-14 20:02
Is there a DB on how to run games like Trackmania? (Sorry if I hijack this thread).

**Comment by Nocccer** [comment] 2023-01-14 20:04
If possible join our discord server and read the pinned message in support channel. Else i think there is some guide in our github wiki. Maybe you find it

**Comment by msdobrescu** [comment] 2023-01-14 20:12
Is it relevant that I have installed all those games via Epic Games?
Is install in Steam a feature related to a Linux host OS?
If so, should this feature use the path to Steam?

**Comment by Nocccer** [comment] 2023-01-15 00:35
> Is it relevant that I have installed all those games via Epic Games?
> Is install in Steam a feature related to a Linux host OS?
> If so, should this feature use the path to Steam?

What do you mean? Games installed via steam belongs to steam support. We provide a way to install epic and gog games.

**Comment by msdobrescu** [comment] 2023-01-15 07:27
I refer to "Add games to Steam automatically" option.

**Comment by arielj** [comment] 2023-02-20 02:45
I'm closing this issue since Steam Runtime sometimes makes games fail and it's not Heroic's fault, it's just that the runtime it's not meant to be used with all games.

The Steam Runtime should only be used when needed (when it's known that it would fix a linux native game that is not working).

**Closed by arielj** 2023-02-20 02:45 UTC

**Comment by B4rabbas** [comment] 2023-07-09 21:15
Steam is installed but I have the message : 
Steam Runtime is enabled, but no runtimes could be found
Make sure Steam and the "SteamLinuxRuntime - Soldier" are installed

The runtimes folder is in ".steam" folder, the steam path is set into heroic games, the issue is still here in v2.8.0
