### ISSUE TITLE
Heroic seems to capture keystrokes from other apps when running and not having focus

### ISSUE THREAD

**Issue by Mfarshore** [Heroic-Games-Launcher/HeroicGamesLauncher#2740] opened 2023-05-29 22:48 UTC
### Describe the bug

I recently started using Heroic, to avoid use that klunky Epic Launcher. I works fine, lightweight and not at all intrusive. However, I noticed that it captures keystrokes from other apps when Heroic does not have focus. I noticed the problem while installing a game, which can be a lengthy process, and I was using DaVinci Resolve to do some editing. When quiting Resolve, using CMD-Q (I am on a Mac) I got a popup notice from Heroic asking if I wanted to quit while a process was in progress.

This is not a major problem for me, since there is a warning from Heroic before quiting when there is a process in progress.

iMac 2017, running Monterey 12.6.4.

Contact me at farshore@mindspring.com for more info.

Thanks for providing this app!

### Add logs

```text
(16:36:08) INFO:    [Legendary]:        Refreshing library...

(16:36:08) INFO:    [Legendary]:        Refreshing Epic Games...

(16:36:08) INFO:    [Connection]:       Connectivity: check-online

(16:36:08) INFO:    [Connection]:       Pinging external endpoints

(16:36:08) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(16:36:08) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary

(16:36:08) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl

(16:36:08) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl

(16:36:08) INFO:    [Legendary]:        Game list updated, got 3 games & DLCs

(16:36:08) WARNING: [Backend]:          Protocol already registered.

(16:36:09) INFO:    [Connection]:       Connectivity: online

(16:36:09) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(16:36:09) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(16:36:09) INFO:    [Backend]:          Loading Screen Ready

(16:36:09) INFO:    [Frontend]:         Refreshing Library

(16:36:09) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(16:36:09) INFO:    [Gog]:              Found 0 game(s) to update

(16:36:09) INFO:    [Backend]:          Frontend Ready

(16:36:09) INFO:    [Backend]:          Checking for new Heroic Updates

(16:36:10) INFO:    [Backend]:          Checking for current version changelog

(16:36:10) INFO:    [Legendary]:        Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(16:36:11) INFO:    [Winetricks]:       Downloading Winetricks

(16:36:13) WARNING: [Backend]:          Could not determine System Info

(16:36:14) INFO:    [Backend]:          Starting the Download Queue

(16:36:15) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/michael1/Library/Application Support/heroic/gog_store/auth.json" --version

(16:36:24) INFO:    [Legendary]:        Found 0 games to update

(16:42:48) INFO:    [Backend]:          Heroic: Setting exitToTray to true

(16:43:34) INFO:    [Backend]:          Heroic: Setting minimizeOnLaunch to true

(16:44:17) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(16:44:17) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/michael1/Library/Application Support/heroic/gog_store/auth.json" --version
```

### Steps to reproduce

1. Run Heroic
2. Start a game installation 
3. While the install is in progress, switch to another application, work a while, the use CMD-Q to quit that app.
4. A notice from Heroic should pop up in a notice asking whether you really want to quit Heroic while the active process has not finished.
5.  An even simpler test is to run something like the calculator app while Heroic is running. Then try to quit the calculator with CMD-Q and Heroic will quit, but not the calculator.

### Expected behavior

Heroic should not capure keystrokes from other apps when Heroic does not have focus.

### Heroic Version

Latest Stable

### System Information

macOS 12.6.4.
Heroic version 2.7.1

### Additional information

Epic login with the captcha screen does not work (2.7.1 Hotfix #1), but the alternative login does.

**Comment by arielj** [comment] 2023-05-29 23:20
This is fixed in the development branch and will be included in the next 2.7.2 release.

Closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2692

**Closed by arielj** 2023-05-29 23:20 UTC
