### ISSUE TITLE
Allow export of data to json or csv

### ISSUE THREAD

**Issue by Code-Slave** [Heroic-Games-Launcher/HeroicGamesLauncher#3190] opened 2023-11-03 11:57 UTC
### Problem description

Between steam and heroic I have a very large library (Over 1k games). Im looking for a way to export info into a csv so I can add it to a game collection db so i dont buy games I already have.

### Feature description

Export game list to a csv file

**Comment by arielj** [comment] 2023-11-04 15:48
Closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2649

There's a comment in that issue with a workaround (you can find the json files with the lists of games in heroic's config folder)

**Closed by arielj** 2023-11-04 15:48 UTC
Labels: feature-request
