### ISSUE TITLE
Crash on connection to game servers

### ISSUE THREAD

**Issue by GamerKing122** [Heroic-Games-Launcher/HeroicGamesLauncher#3180] opened 2023-10-31 01:44 UTC
### Describe the bug

Crash on connection to game servers

### Add logs

```text
(12:10:24) INFO:    [Legendary]:        Legendary location: /snap/heroic/247/resources/app.asar.unpacked/build/bin/linux/legendary
(12:10:24) INFO:    [Gog]:              GOGDL location: /snap/heroic/247/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:10:24) INFO:    [Connection]:       Connectivity: check-online
(12:10:24) INFO:    [Connection]:       Pinging external endpoints
(12:10:24) ERROR:   [Backend]:          Error: spawn free EACCES
(12:10:24) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(12:10:24) WARNING: [Backend]:          Protocol already registered.
(12:10:24) INFO:    [Connection]:       Connectivity: online
(12:10:24) INFO:    [Backend]:          User Not Found, removing it from Store
(12:10:24) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(12:10:25) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:10:25) INFO:    [Backend]:          Loading Screen Ready
(12:10:25) INFO:    [Backend]:          Frontend Ready
(12:10:25) INFO:    [Backend]:          Checking for new Heroic Updates
(12:10:25) INFO:    [Backend]:          Checking for current version changelog
(12:10:25) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(12:10:27) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(12:10:27) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, VKD3D will not work
(12:10:27) WARNING: [DXVKInstaller]:    No GPU with Vulkan 1.1 support found, DXVK will not work
(12:10:27) INFO:    [Winetricks]:       Downloading Winetricks
(12:10:27) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-v2.10
(12:10:29) INFO:    [WineDownloader]:   Updating wine versions info
(12:10:29) INFO:    [WineDownloader]:   Fetching upstream information...
(12:10:30) INFO:    [Backend]:          Starting the Download Queue
(12:10:30) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.10/vkd3d-proton-v2.10.tar.xz
(12:10:30) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.10/vkd3d-proton-v2.10.tar.xz
(12:10:30) INFO:    [DXVKInstaller]:    downloaded vkd3d
(12:10:30) INFO:    [DXVKInstaller]:    extracting vkd3d
(12:10:30) ERROR:   [DXVKInstaller]:    Extraction of vkd3d failed with: Error: Command failed: tar -xf /home/sean/snap/heroic/247/.config/heroic/tools/vkd3d/vkd3d-proton-v2.10.tar.xz -C /home/sean/snap/heroic/247/.config/heroic/tools/vkd3d
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:323:12)
(12:10:31) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

just connect  then crash

### Expected behavior

error window

### Screenshots

![Screenshot from 2023-10-31 12-09-21](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/27757241/3cdd9a93-1417-4551-b445-c53e1b42cf2a)

### Heroic Version

Latest Stable

### System Information

- OS "Ubuntu 23.10"
- vmware inside workstation pro 17.5
-

**Comment by arielj** [comment] 2023-10-31 02:19
if you are using the snap package, that's the issue, use something else like flatpak, appimage or .deb instead

**Comment by arielj** [comment] 2023-11-05 15:39
Closing this, there are similar reports and it's caused by the snap package, heroic 2.10.0 should fix this.

**Closed by arielj** 2023-11-05 15:39 UTC
Labels: bug:unconfirmed
