### ISSUE TITLE
Can't start heroic on Ubuntu 20.04

### ISSUE THREAD

**Issue by x-channel** [Heroic-Games-Launcher/HeroicGamesLauncher#962] opened 2022-02-06 18:40 UTC
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
The game launcher not starting.

**Add Logs**
caire@caire-A320MH:~$ heroic --enable-logging
INFO: Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(node:7612) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.get (/opt/Heroic/resources/app.asar/build/config.js:36:28)
    at getLegendaryVersion (/opt/Heroic/resources/app.asar/build/utils.js:63:61)
    at getSystemInfo (/opt/Heroic/resources/app.asar/build/utils.js:140:68)
    at /opt/Heroic/resources/app.asar/build/main.js:185:60
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:7612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[7643:0206/153624.002454:WARNING:gpu_sandbox_hook_linux.cc(445)] dlopen(libxcb-dri3.so) failed with error: libxcb-dri3.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
[7643:0206/153624.002698:WARNING:gpu_sandbox_hook_linux.cc(447)] dlopen(libxcb-present.so) failed with error: libxcb-present.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
[7643:0206/153624.002777:WARNING:gpu_sandbox_hook_linux.cc(450)] dlopen(libxcb-sync.so) failed with error: libxcb-sync.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**
1. Open Terminal
2. write heroic

**Expected behavior**
Open Software

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu Studio 20.04
- Heroic Version [e.g. 22]
- Game: not aplicable
- Wine/Proton version: not aplicable
- Hardware specs (RAM, CPU, GPU):
- Ryzen 5 1600 af
- nvidia gt 1030
- 16gb 2666mhz

**Additional context**
I think that was update problem, I uninstalled and installed again, but error persist.

**Comment by flavioislima** [comment] 2022-02-06 21:48
I guess your distro is missing some libs. Try installing some of the ones that are listed on the error and try again.

**Comment by x-channel** [comment] 2022-02-07 17:36
I think this is not the problem, because I used this app during end of last year. But I tried to install libxcb-dri3, libxcb-present and libxcb-sync reboot my computer and try to open heroic again. But did not work  :(


caire@caire-A320MH:~$ heroic --enable-logging
INFO: Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(node:2873) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.get (/opt/Heroic/resources/app.asar/build/config.js:36:28)
    at getLegendaryVersion (/opt/Heroic/resources/app.asar/build/utils.js:63:61)
    at getSystemInfo (/opt/Heroic/resources/app.asar/build/utils.js:140:68)
    at /opt/Heroic/resources/app.asar/build/main.js:185:60
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:2873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2905:0207/142809.852168:WARNING:gpu_sandbox_hook_linux.cc(445)] dlopen(libxcb-dri3.so) failed with error: libxcb-dri3.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
^Ccaire@caire-A320MH:~$ sudo apt-get update
[sudo] senha para caire: 
Atingido:1 http://br.archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                                                                                                            
Atingido:2 http://br.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                                                                                                                                                            
Atingido:3 https://repo.steampowered.com/steam stable InRelease                                                                                                                                                                                                                                   
Atingido:4 https://deb.nodesource.com/node_14.x focal InRelease                                                                                                                                                                                                    
Atingido:5 http://br.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                                                                                              
Atingido:6 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu focal InRelease                                                                                                                        
Atingido:7 https://linux.teamviewer.com/deb stable InRelease                                                                                                                
Atingido:8 http://dl.openfoam.org/ubuntu focal InRelease                                                                                                           
Atingido:9 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                              
Atingido:10 http://archive.canonical.com/ubuntu focal InRelease                                              
Atingido:11 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu focal InRelease
Atingido:12 http://ppa.launchpad.net/lutris-team/lutris/ubuntu focal InRelease
Atingido:13 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu focal InRelease
Lendo listas de pacotes... Pronto                  
caire@caire-A320MH:~$ sudo apt-get install -y libxcb-dri3-0
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
libxcb-dri3-0 já é a versão mais recente (1.14-2).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

**Comment by flavioislima** [comment] 2022-02-10 16:53
I think the issue is with your OS, so I recommend a clean install. For Now I will close the issue.

**Closed by flavioislima** 2022-02-10 16:53 UTC
