### ISSUE TITLE
Heroic doesn't show when there isn't enough space

### ISSUE THREAD

**Issue by TabulateJarl8** [Heroic-Games-Launcher/HeroicGamesLauncher#1063] opened 2022-03-09 02:39 UTC
### Describe the bug

If you don't have enough space to install whatever game you're trying to install, heroic will just immediately say that the installation finished without error.

### Add logs

```
(20:06:23) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:06:23) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
/bin/sh: line 1: hostname: command not found
(20:06:23) INFO:    [Backend]:         
  Heroic Version: 2.2.3 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.12-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 33.7 GB Available: 28.7 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 SUPER VRAM: 8192MB DRIVER: 510.54 
  PROTOCOL: x11
  
(20:06:23) WARNING: [Backend]:         Protocol already registered.
[50340:0308/200623.890357:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[50340:0308/200623.890438:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[50340:0308/200623.890479:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(20:06:24) INFO:    [Frontend]:        Refreshing Library
(20:06:24) INFO:    [Legendary]:       Refreshing library...
(20:06:24) INFO:    [Legendary]:       Refreshing Epic Games...
(20:06:24) INFO:    [Legendary]:       Refreshing Epic Games...
(20:06:24) INFO:    [Legendary]:       [cli] INFO: Logging in...
(20:06:24) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(20:06:24) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(20:06:25) INFO:    [Legendary]:       Updating game list
(20:06:25) INFO:    [Legendary]:       Game List Updated
(20:06:25) INFO:    [Legendary]:       Checking for game updates
(20:06:25) INFO:    [Legendary]:       Found 0 game(s) to update
(20:06:25) INFO:    [Gog]:             Found 0 game(s) to update
(20:06:28) INFO:    [Backend]:         checking for heroic updates
(20:06:30) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(20:06:31) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(20:06:33) INFO:    [Legendary]:       Installing Calluna with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install Calluna --platform Windows --base-path '/home/tabulate/legendary' --skip-dlcs --skip-sdl  -y |& tee "/home/tabulate/.config/heroic/GamesConfigCalluna.log"
(20:06:33) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(20:06:33) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(20:06:34) INFO:    [Backend]:         Progress: Calluna /MiB/undefined
(20:06:35) INFO:    [Backend]:         finished installing
(20:06:35) INFO:    [Legendary]:       Getting More details with Legendary info command... 
```
Example Legendary log file (just chose a random large game):
```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "NBA 2K21" (639977eecfd2497c941b71af949b5067)...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /home/tabulate/legendary/NBA2K21
[Core] INFO: Selected CDN: download.epicgames.com (https)
[cli] INFO: Install size: 99188.59 MiB
[cli] INFO: Download size: 94522.18 MiB (Compression savings: 4.6%)
[cli] INFO: Reusable size: 0.00 MiB (chunks) / 0.00 MiB (unchanged / skipped)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.
[cli] CRITICAL: Installation cannot proceed, exiting.

Installation requirements check returned the following results:
 ! Failure: Not enough available disk space! 45150.09 MiB < 99188.59 MiB
```

### Steps to reproduce

1. Select a folder to install that is on a disk which does not have enough space to install the game
2. Click the install button

### Expected behavior

Heroic should probably give an error message instead of immediately saying installation completed

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.2.3

**Comment by flavioislima** [comment] 2022-03-12 12:30
duplicate of #951

**Closed by flavioislima** 2022-03-12 12:30 UTC
