### ISSUE TITLE
Collisions in game `app_name` cause UI breakage

### ISSUE THREAD

**Issue by derrod** [Heroic-Games-Launcher/HeroicGamesLauncher#2843] opened 2023-07-05 14:31 UTC
### Describe the bug

When two games have the same `app_name` various library UI features break, such as sorting, hidden games, and favourites (possibly more behind the scenes things, but these are the most visible ones).

In this case an item from Epic has the app name `1`, and so does "Fallout Classic" on GOG. Sorting the games list results in duplicate and empty items being inserted.

### Steps to reproduce

1. Have two items in your library (across various platforms) that have the same `app_name`
2. Click the sorting button

### Expected behavior

Items are sorted, not duplicated/broken.

### Screenshots

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/3123295/289358ae-ce80-4a9c-bdf7-8e9ed39c193d

### Heroic Version

Latest Stable

### System Information

Windows 10

### Additional information

Neither items are available on their respective storefronts anymore, but manually changing app names of apps in the library caches can be used to reproduce this issue.

**Comment by arielj** [comment] 2023-12-31 01:36
is this still happening?

I tried changing one a GOG game to have the same app_name as a Legendary game and I can't reproduce this problem.

**Comment by derrod** [comment] 2024-01-01 07:00
I also can't reproduce it anymore right now, though I don't know if this was actually fixed or some other thing is now different.

**Comment by arielj** [comment] 2024-01-01 14:14
Ok, I'll close this issue then. We can reopen it if it starts happening again

**Closed by arielj** 2024-01-01 14:14 UTC
Labels: bug:confirmed
