### ISSUE TITLE
DLC Manager

### ISSUE THREAD

**Issue by 32bitx64bit** [Heroic-Games-Launcher/HeroicGamesLauncher#2252] opened 2022-12-24 08:20 UTC
### Feature description

A DLC manager for both Epic games and GOG would be nice so you can manage what DLC's you want to install

**Comment by pktiuk** [comment] 2022-12-26 12:40
Duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1119  
To be closed

**Closed** 2022-12-26 13:06 UTC
