### ISSUE TITLE
Add a all games section in the library and can we get soon support for ubisoft connect and origin?

### ISSUE THREAD

**Issue by MrArdillo** [Heroic-Games-Launcher/HeroicGamesLauncher#1212] opened 2022-04-16 19:25 UTC
### Feature description

I know it's on the works but id like to know if it will be soon. And a all games button for not looking for a game in both stores. And a button for select between linux or windows version in the games with ports for the two OS will be nice. Thanks for the hard work and this amazing launcher

**Comment by jtbg** [comment] 2022-04-20 04:16
Lutris has an Ubisoft Connect integration in the meantime

**Comment by MrArdillo** [comment] 2022-04-20 06:24
I know that but i prefer heroic and i think it will be better if they can add it. And its in their plans to add more launcher to their client

**Comment by wiryfuture** [comment] 2022-04-23 17:53
Could you split this up into separate issues for each store and for an all games section? 
Cheers,

**Comment by wiryfuture** [comment] 2022-04-23 20:04
Dupe of #352 , #351 and #945

**Closed by wiryfuture** 2022-04-23 20:04 UTC
Labels: duplicate
