### ISSUE TITLE
Fall Guys stuck on easy anticheat loading screen

### ISSUE THREAD

**Issue by Vishnu-2004** [Heroic-Games-Launcher/HeroicGamesLauncher#1547] opened 2022-07-04 10:32 UTC
### Describe the bug

Fall Guys stuck on easy anti-cheat loading screen. (Mac OS)

### Add logs

Launch Command: CX_BOTTLE=Heroic /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 0a2d9f6403244d12969e11da6713137b --wine /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine --wine-prefix /Users/Vishnu/.wine

System Info:
Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: macOS KERNEL: 21.5.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 6.32 GiB
GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"launcherArgs": "",
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/Users/Vishnu/.wine",
	"wineVersion": {
		"bin": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine",
		"name": "CrossOver - 21.1",
		"type": "crossover",
		"wineserver": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wineserver",
		"wineboot": ""
	}
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Using CrossOver Bottle "Heroic"
[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...

Game Log:
Legendary update available!
- New version: 0.20.27 - "Dark Energy (hotfix)"
- Release summary:
 [*] Adds instructions to recover from missing manifest file errors
 [*] Updates "eos-overlay" for more intuitive Linux/macOS usage
 [*] Adds instructions for use on Windows when exe is double-cliecked instead of run from a terminal.
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.27

- Download URL: https://legendary.gl/release/download/0.20.27/legendary_macOS.zip
FGenericBootstrapper::Bootstrap: Started Epic Online Services Bootstrapper 1.0.0++EOSSDK+Release-FGS6-CL-18019720
FGenericBootstrapper::Bootstrap: Getting config path
FGenericBootstrapper::Bootstrap: Reading config from path: 'Y:\Games\Heroic\FallGuys\FallGuys_client.ini'
FGenericBootstrapper::Bootstrap: Creating session
FGenericBootstrapper::TryCreateSession: Creating process group
FGenericBootstrapper::Bootstrap: Getting path to User Helper
FWindowsPlatform::TryGetValueFromRegistry: Failed to get value from registry with SubKeyName 'SOFTWARE\Epic Games\EOS\UserHelper' and ValueName 'Path'
FWindowsBootstrapper::TryGetUserHelperPath: Path does not exist in registry
FGenericBootstrapper::Bootstrap: Failed to find path to User Helper
FGenericBootstrapper::Bootstrap: Executing target application: 'Y:\Games\Heroic\FallGuys\FallGuysEACLauncher.exe'
FGenericBootstrapper::Bootstrap: Succeeded

### Steps to reproduce

Install Fall Guys through epic games and click on play.

### Expected behavior

Game to run.

### System Information

Mac OS

### Additional information

NA

**Comment by arielj** [comment] 2022-07-04 12:15
I understand Fall Guys doesn't work on MacOS, it's not a Heroic bug, the anticheat stuff depends on a specific version of wine/proton and you can't use that on Mac. Closing this since it's not a bug in heroic.

**Closed by arielj** 2022-07-04 12:15 UTC

**Comment by felipecrs** [comment] 2022-07-21 16:30
I have the exact same issue, running on Heroic 2.4.0-beta.2, Ubuntu 22.04, EasyAntiCheat Runtime installed and enabled, and using ProtonGE 7-26.

So, I would not mark this as macOS specific.

**Comment by Nocccer** [comment] 2022-07-21 16:32
Please follow the guide for Linux Fall Guys:

Current steps to run Fall Guys:
- Follow the "Editing the files" part of https://steamcommunity.com/sharedfiles/filedetails/?id=2787044978 (move the .so file and edit the .ini. It will not work with just the .so file)
Next step depends on your setup.
If you're using the Heroic Beta:
- Enable the EasyAntiCheat Runtime in the game settings ("Wine Extensions" tab)
- That's it, you can run the game now
- On Flatpak GameMode needs to be enabled in settings.

**On Mac os Fall guys does not work.**

**Comment by felipecrs** [comment] 2022-07-21 16:36
Thank you, it works like a charm now.
