### ISSUE TITLE
Tiny Tina’s Wonderlands games won’t sync

### ISSUE THREAD

**Issue by pmarreck** [Heroic-Games-Launcher/HeroicGamesLauncher#1269] opened 2022-05-03 03:36 UTC
### Describe the bug

Tiny Tina’s Wonderlands save games won’t sync on a new install, and inspecting the logs, I think it’s due to the apostrophe in the game name not being represented in the predicted savegame location

### Add logs

Will attach when on desktop

### Steps to reproduce

1. Install Wonderlands after having played it on Windows on the same account
2. Load game
3. See no sync’d saves
4. See logs

### Expected behavior

Save games sync properly

### System Information

- OS: Pop_OS latest 
- Heroic Version: latest beta

**Comment by wiryfuture** [comment] 2022-05-03 23:39
Afaik this is compound issue; the apostrophe not being parsed correctly, and the location where saves are made is different from what it usually is. 
While someone could easily fix the issue of the apostrophe in Heroic, it may not resolve the issue entirely per #1175 

Will mark this as good first issue for the apostrophe parsing, but will close this afterwards since the problem may lie with Legendary.

**Comment by flavioislima** [comment] 2022-05-04 07:52
would be good to test with legendary only, running just: `legendary sync-saves appname` without the path arguments and see if it will work.

**Comment by pmarreck** [comment] 2022-05-05 15:42
ah, I see it's a Legendary issue, my bad. thanks all

**Comment by wiryfuture** [comment] 2022-05-07 11:43
@flavioislima are apostrophes being handled correctly? 
I can't actually tell, since we've had issues with them in the past iirc but would be worth checking quickly so I can close this.

**Comment by flavioislima** [comment] 2022-05-07 12:46
I don't know, it's being some time since we touched that save sync stuff since it works for most games. I will download and test this one once I have the time. But I believe the issue is with heroic and not legendary.

**Comment by irish-bug** [comment] 2022-06-30 00:41
> so I symlinked to the directory with the errant name using the expected name (in the same location) and that seemed to solve the immediate issue but progress is still not syncing properly across platforms

@pmarreck  Any chance you can walk me through the symlink? I'm familiar with creating symlinks, I'm just not sure which folder needs linked to which. I just want load my PC game once so I can play from there on the deck for now since this issue won't be worked on. Thanks!

**Comment by Nocccer** [comment] 2022-08-03 16:32
Seems to be solved. Closing.

**Closed by Nocccer** 2022-08-03 16:32 UTC
Labels: bug:confirmed, good first issue, issue:wontfix, issue:upstream

**Comment by kode54** [comment] 2022-09-16 07:05
Manually syncing this game still synced my saves to a `Tiny Tinas Wonderlands` folder instead of `Tiny Tina's Wonderlands` where my existing local saves were. (Complicated story, I started the game in Linux, then was in Windows 11 primarily for a while, and started a new save there.)
