### ISSUE TITLE
Does not run on Steam OS (Steam Deck)

### ISSUE THREAD

**Issue by nexomad** [Heroic-Games-Launcher/HeroicGamesLauncher#2459] opened 2023-02-16 16:52 UTC
### Describe the bug

Although it worked at first, now when I try to run it from the Desktop it does not open. Running it with "flatpak run com.heroicgameslauncher.hgl" shows the log I show below. I install Heroic Games Launcher from Discover.

### Add logs

```text
$ flatpak run com.heroicgameslauncher.hgl
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 8170
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/app/bin/heroic/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
    at get store [as store] (/app/bin/heroic/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/app/bin/heroic/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
    at new ElectronStore (/app/bin/heroic/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at new TypeCheckedStoreBackend (/app/bin/heroic/resources/app.asar/build/electron/main.6ace4a2c.js:2:3204)
    at Object.<anonymous> (/app/bin/heroic/resources/app.asar/build/electron/main.6ace4a2c.js:169:13835)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
Gtk-Message: 17:35:49.833: Failed to load module "canberra-gtk-module"
[3:0216/173549.890155:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0216/173549.890203:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

### Steps to reproduce

1. Open from Desktop.
2. If not, open from Konsole with flatpak run com.heroicgameslauncher.hgl

### Expected behavior

Open Heroic Games Launcher as usual.

### Heroic Version

Latest Stable

### System Information

- Steam OS Holo 3.4.4
- Heroic Games Launcher v2.6.2

**Comment by LeoHirasawa** [comment] 2023-02-24 02:06
same issue,too.
The launcher runs well at first, but can't open after that.I tried to remove and re-install,but the issue exist still.

**Comment by Nocccer** [comment] 2023-03-06 20:21
Sounds like the heroic config is broken. You might need to remove the config.json

**Comment by nexomad** [comment] 2023-03-07 11:06
In the end I uninstalled, deleted all traces of the program and reinstalled, with everything working as before.
The real question is why it got corrupted, I didn't do anything special...

**Comment by arielj** [comment] 2023-11-04 15:35
Closing since things are working now and it's not clear how to even reproduce the corruption of the data

**Closed by arielj** 2023-11-04 15:35 UTC
