### ISSUE TITLE
Sort by: More options

### ISSUE THREAD

**Issue by AtFreezingPoint** [Heroic-Games-Launcher/HeroicGamesLauncher#4081] opened 2024-10-26 23:27 UTC
### Problem description

There's not much sorting you can do in the app, it's annoying.

### Feature description

You should be able to sort games by popularity (I guess third party source somehow) and other stuff, the current option(s?) is quite basic. Like genre, playtime (if applicable) etc.

### Alternatives

2025 big Heroic Launcher update; announcing Heroic AI

**Comment by arielj** [comment] 2024-11-08 22:58
Closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2968

**Closed by arielj** 2024-11-08 22:58 UTC
Labels: feature-request
