### ISSUE TITLE
Epic login fails

### ISSUE THREAD

**Issue by tautrimas** [Heroic-Games-Launcher/HeroicGamesLauncher#1843] opened 2022-09-25 14:58 UTC
### Describe the bug

Logging into Epic does nothing. Updating Legendary to `0.20.29 - Dark Energy (hotfix #3)` fixes the issue.

### Add logs

```
(15:51:58) INFO:    [Frontend]:        Called Login

(15:51:58) INFO:    [Frontend]:        No cache found, getting data from legendary...

(15:51:58) INFO:    [Legendary]:       Refreshing library...
```

### Steps to reproduce

1. Install Heroic.
2. Login using any method to Epic
3. It shows Logging In for a long time and then falls back to log in selection as if nothing happened.
4. Web UI shows my logged in account
5. Library tab is not visible and still displays "Log In"
6. Logs don't show any error.

### Expected behavior

Should show Library of games.

### System Information

- MacOS 12.6 CPU M1
- Heroic Version 2.4.3 Chopper

**Comment by ywmaa** [comment] 2022-09-28 06:30
this happens to me too.

**Comment by ywmaa** [comment] 2022-09-28 06:30
I think the problem is that https://legendary.gl/epiclogin is down or something

**Comment by flavioislima** [comment] 2022-09-28 07:18
> I think the problem is that https://legendary.gl/epiclogin is down or something
> 

It is not down. are you using some kind of proxy?

**Comment by ywmaa** [comment] 2022-09-28 08:10
no I probably don't use proxy, but I recently use nobara project, though I install herioc launcher and I logged in fine no issues, but recently I couldn't start any game, and it says credentials have expired so I logged out to try to log in again, then it keeps loading and never shows epic games login screen.

**Comment by ywmaa** [comment] 2022-09-28 08:25
never mind, It turns out that making google the main dns server for some reason made the link un accessible for me, now it works.

**Comment by flavioislima** [comment] 2022-09-28 08:53
ok, closing this one then.

**Closed by flavioislima** 2022-09-28 08:53 UTC

**Comment by ywmaa** [comment] 2022-09-28 08:55
hey, I am not the author, at first I thought that my issue is the same as the author, now I don't if the author's issue was the same as me.

**Comment by flavioislima** [comment] 2022-09-28 08:57
> hey, I am not the author, at first I thought that my issue is the same as the author, now I don't know if the author's issue was the same as me.

yes, he fixed it by changing legendary version. I believe he was using an old one.
I just tested login in with 2.4.3 on a clean install on the steam deck and it was fine.
So could also be a temporary issue.
