### ISSUE TITLE
Steam Runtime not be found

### ISSUE THREAD

**Issue by ketronix-dev** [Heroic-Games-Launcher/HeroicGamesLauncher#2673] opened 2023-05-04 07:33 UTC
### Describe the bug

Heroic displayed this:
> Launch aborted
Error:
Steam Runtime is enabled, but no runtimes could be found
Make sure Steam and the "SteamLinuxRuntime - Soldier" are installed

### Add logs

```text
(10:26:37) INFO:    [Legendary]:        Refreshing library...
(10:26:37) INFO:    [Legendary]:        Refreshing Epic Games...
(10:26:37) INFO:    [Connection]:       Connectivity: check-online
(10:26:37) INFO:    [Connection]:       Pinging external endpoints
(10:26:37) INFO:    [Legendary]:        Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:26:37) INFO:    [Legendary]:        Legendary location: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:26:37) INFO:    [Gog]:              GOGDL location: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:26:37) INFO:    [Gog]:              GOGDL location: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:26:37) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(10:26:37) WARNING: [Backend]:          Protocol already registered.
(10:26:37) INFO:    [Gog]:              Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/artem/.config/heroic/gog_store/auth.json --version
(10:26:37) INFO:    [Connection]:       Connectivity: online
(10:26:38) INFO:    [Legendary]:        Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:26:38) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:26:38) INFO:    [Backend]:          

Heroic Version: 2.7.1 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Solus KERNEL: 6.2.14-232.current ARCH: x64
CPU: Intel Core™ i3-4130 @3.4 GOVERNOR: ondemand
RAM: Total: 7.71 GiB Available: 5.95 GiB
GRAPHICS: GPU0: Oland XT [Radeon HD 8670 / R5 340X OEM / R7 250/350/350X OEM] VRAM: 256MB 
PROTOCOL: x11

(10:26:38) INFO:    [Backend]:          Loading Screen Ready
(10:26:38) INFO:    [Frontend]:         Refreshing Library
(10:26:38) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:26:38) INFO:    [Gog]:              Found 0 game(s) to update
(10:26:38) INFO:    [Backend]:          Frontend Ready
(10:26:38) INFO:    [Backend]:          Checking for new Heroic Updates
(10:26:38) INFO:    [Backend]:          Checking for current version changelog
(10:26:38) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(10:26:38) INFO:    [Legendary]:        Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(10:26:39) INFO:    [Legendary]:        Checking for game updates: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:26:40) INFO:    [Winetricks]:       Downloading Winetricks
(10:26:41) INFO:    [Legendary]:        Found 0 games to update
(10:26:41) INFO:    [Frontend]:         No cache found, getting data from legendary...
(10:26:41) INFO:    [Legendary]:        Refreshing library...
(10:26:41) INFO:    [Legendary]:        Refreshing Epic Games...
(10:26:41) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(10:26:42) INFO:    [Legendary]:        Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:26:43) INFO:    [Backend]:          Starting the Download Queue
(10:26:59) INFO:    [Backend]:          Ovenbird: Setting useSteamRuntime to true
(10:27:09) INFO:    [Backend]:          Launching Surviving Mars (Ovenbird)
(10:27:09) INFO:    [Backend]:          Preventing display from sleep
(10:27:09) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 8.0
(10:27:09) INFO:    [Backend]:          Preventing machine to sleep
(10:27:09) INFO:    [Backend]:          Stopping Power Saver Blocker
(10:27:10) WARNING: [Backend]:          No runtimes of type soldier could be found, returning first available one
(10:27:10) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(10:27:10) INFO:    [Frontend]:         Refreshing Library
(10:27:10) INFO:    [Legendary]:        Refreshing library...
(10:27:10) INFO:    [Legendary]:        Refreshing Epic Games...
(10:27:10) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(10:27:10) INFO:    [Legendary]:        Running command: /usr/share/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:29:47) INFO:    [Backend]:          Heroic: Setting autoUpdateGames to true
(10:29:57) INFO:    [Backend]:          Heroic: Setting darkTrayIcon to true
(10:29:57) INFO:    [Backend]:          Changing Tray icon Color...
(10:29:58) INFO:    [Backend]:          Heroic: Setting darkTrayIcon to false
(10:29:58) INFO:    [Backend]:          Changing Tray icon Color...
(10:30:03) INFO:    [Backend]:          Heroic: Setting addStartMenuShortcuts to true
```

### Steps to reproduce

1. Go to any game settings and click to the "Other"
2. Click on 'Use Steam Runtime'
3. Close game settings and click Run

### Expected behavior

Normal run game

### Heroic Version

Latest Stable

### System Information

- OS Solus:

**Comment by ketronix-dev** [comment] 2023-05-25 08:33
> Do you have Steam and the runtime installed like the error said? We don't ship those runtimes, that's why they are called Steam runtimes.

The launcher is looking for the old version of the runtime, the new version has a new codename, so you have an error.

You are looking for: Steam Runtime Soldier
You should be looking for: Steam Runtime Sniper

**Comment by Etaash-mathamsetty** [comment] 2023-05-26 03:48
we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think

**Comment by ketronix-dev** [comment] 2023-05-26 05:50
> we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think

You don't have to do that. Because proton 7 works fine on my sniper.

**Comment by Etaash-mathamsetty** [comment] 2023-05-26 16:31
> > we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think
> 
> You don't have to do that. Because proton 7 works fine on my sniper.

how did you test this?

**Comment by ketronix-dev** [comment] 2023-05-26 17:38
> > > we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think
> > 
> > You don't have to do that. Because proton 7 works fine on my sniper.
> 
> how did you test this?

I have the early access version of Sniper installed, and one game uses proton 7. You can also check it out.

**Comment by Etaash-mathamsetty** [comment] 2023-05-27 02:13
> > > > we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think
> > > 
> > > 
> > > You don't have to do that. Because proton 7 works fine on my sniper.
> > 
> > 
> > how did you test this?
> 
> I have the early access version of Sniper installed, and one game uses proton 7. You can also check it out.

proton 7 auto downloads soldier ?

**Comment by ketronix-dev** [comment] 2023-06-01 07:46
> > > > > we have to make proton 7 use soldier and proton 8 use sniper and identifying that is going to be tricky i think
> > > > 
> > > > 
> > > > You don't have to do that. Because proton 7 works fine on my sniper.
> > > 
> > > 
> > > how did you test this?
> > 
> > I have the early access version of Sniper installed, and one game uses proton 7. You can also check it out.
> 
> proton 7 auto downloads soldier ?

Nope

**Comment by varad-kadam** [comment] 2023-06-06 15:11
Hi, any update on this?
Ever since last week, possibly the latest update (v2.8.0), I've run into the same.

I can confirm I've got both the Soldier & Sniper installed.
I'm using the AUR version for Heroic & Steam Flatpak.

**Comment by Etaash-mathamsetty** [comment] 2023-06-06 18:02
I have a patch in my heroic fork that switches from soldier to sniper, I can cherry pick it onto hear so more people can test and see if it breaks anything :)

**Comment by varad-kadam** [comment] 2023-06-26 10:39
Okay so I think I've figured out the problem:
TL,DR: Heroic is looking in the wrong place for the Linux runtimes.

In the pacman repositories, steam uses version `1668654564`. This version works just fine, and heroic is able to use the Steam runtime. This version stores the runtimes under:
 `/home/_USER_/.local/share/Steam/steamapps/common/` 

The Flatpak uses a newer steam version, which is version `1687386907` at the time of writing. Here the runtimes are stored under:
`_STEAM LIBRARY_/steamapps/common/`.

Using a symlink at the old location that points to the directory in the new location fixes the problem.

**Comment by Etaash-mathamsetty** [comment] 2023-06-26 13:13
> Okay so I think I've figured out the problem: TL,DR: Heroic is looking in the wrong place for the Linux runtimes.
> 
> In the pacman repositories, steam uses version `1668654564`. This version works just fine, and heroic is able to use the Steam runtime. This version stores the runtimes under: `/home/_USER_/.local/share/Steam/steamapps/common/`
> 
> The Flatpak uses a newer steam version, which is version `1687386907` at the time of writing. Here the runtimes are stored under: `_STEAM LIBRARY_/steamapps/common/`.
> 
> Using a symlink at the old location that points to the directory in the new location fixes the problem.

ofc it's looking in the wrong place, because it's still using the old runtime ?

**Comment by varad-kadam** [comment] 2023-07-08 11:13
>  still using the old runtime

I don't understand what you mean by this, could you please elaborate? The runtimes, Solider and Sniper, are the same in both versions, it's the file paths that have changed and heroic is still using the old file paths.  

However, simply switching to the new paths wouldn't work as it would now cause issues for those on older version on Steam.

**Comment by Etaash-mathamsetty** [comment] 2023-07-08 15:10
> > still using the old runtime
> 
> I don't understand what you mean by this, could you please elaborate? The runtimes, Solider and Sniper, are the same in both versions, it's the file paths that have changed and heroic is still using the old file paths.
> 
> However, simply switching to the new paths wouldn't work as it would now cause issues for those on older versions on Steam.

oh seems like I didn't understand what you originally posted
here's the thing, both of the paths you described are identical on most systems, the steam library is located in /home/_USER_/.local/share/Steam/steamapps/common/ 98% of the time

**Comment by varad-kadam** [comment] 2023-07-09 11:18
Ahh that's right, my apologies, that is the default steam library location.
That's strange then, its working fine on my end.

**Comment by arielj** [comment] 2023-12-31 03:49
Closing this since I understand this is not an issue anymore (we handle the different runtimes already)

**Closed by arielj** 2023-12-31 03:49 UTC
Labels: issue:investigating

**Comment by Leza89** [comment] 2024-01-12 02:33
> Closing this since I understand this is not an issue anymore (we handle the different runtimes already)

I still have this issue:



```
flatpak update com.heroicgameslauncher.hgl
Looking for updates…

New com.heroicgameslauncher.hgl permissions:
    file access [1]

    [1] xdg-run/gamescope-0


        ID                                    Branch           Op          Remote           Download
 1. [✓] com.heroicgameslauncher.hgl           stable           u           flathub          2,0 MB / 159,2 MB

Updates complete.
```

-----------

Steam Runtime is enabled, but no runtimes could be found
Make sure Steam and the SteamLinuxRuntime - Sniper are installed

```
(03:26:22) INFO:    [WineDownloader]:   Finished installation of wine version Wine-GE-Proton8-27-LoL
which: no wine in (/app/bin:/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin:/usr/lib/extensions/vulkan/gamescope/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin:/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux)
(03:26:22) INFO:    [Backend]:          Changing wine version to Wine - Wine-GE-Proton8-27-LoL
(03:26:22) INFO:    [Backend]:          Heroic: Setting wineVersion to {"bin":"/home/gregg/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/bin/wine","name":"Wine - Wine-GE-Proton8-27-LoL","type":"wine","lib":"/home/gregg/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/lib64","lib32":"/home/gregg/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/lib","wineserver":"/home/gregg/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton8-27-LoL/bin/wineserver"} (previous value: {"bin":"/home/gregg/.local/share/Steam/steamapps/common/Proton - Experimental/proton","name":"Proton - Proton - Experimental","type":"proton"})
(03:26:56) INFO:    [Backend]:          Launching Offworld Trading Company (twd7yzw5C3peyLowMyeZ6p)
(03:26:56) INFO:    [Backend]:          Preventing display from sleep
(03:26:56) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton8-6
(03:26:56) INFO:    [Backend]:          Preventing machine to sleep
(03:26:56) WARNING: [Backend]:          No runtimes of type sniper could be found, returning first available one
(03:26:56) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton8-6
(03:26:56) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(03:26:56) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton8-6
(03:26:56) INFO:    [Backend]:          Checking if wine version exists: Proton - GE-Proton8-6
(03:26:56) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(03:26:58) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(03:26:58) INFO:    [Frontend]:         Refreshing sideload Library
(03:26:58) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(03:26:58) INFO:    [Backend]:          Stopping Power Saver Blocker
```
