### ISSUE TITLE
"Cannot get game info" for GOG Goodies

### ISSUE THREAD

**Issue by lfom** [Heroic-Games-Launcher/HeroicGamesLauncher#2777] opened 2023-06-04 01:44 UTC
### Describe the bug

Hello, there!

Thank you a lot for maintaining Heroic!

If I recall correctly, it used to work in the past: it was possible to show the info for a "Goodies" entry from GOG, now it just shows the generic "Cannot get game info" after a while (it seems to get some info correctly tho, like the package description, but then just shows the error).

### Add logs

```text
(22:18:57) INFO:    [Legendary]:        Refreshing library...
(22:18:57) INFO:    [Legendary]:        Refreshing Epic Games...
(22:18:57) INFO:    [Connection]:       Connectivity: check-online
(22:18:57) INFO:    [Connection]:       Pinging external endpoints
(22:18:57) INFO:    [Legendary]:        Running command: /usr/bin/legendary --version
(22:18:57) INFO:    [Legendary]:        Legendary location: /usr/bin/legendary
(22:18:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:18:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:18:57) INFO:    [Legendary]:        Game list updated, got 133 games & DLCs
(22:18:57) WARNING: [Backend]:          Protocol already registered.
(22:18:57) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json --version
(22:18:57) INFO:    [Connection]:       Connectivity: online
(22:18:57) INFO:    [Gog]:              Checking if login is valid
(22:18:57) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json auth
(22:18:58) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:18:58) INFO:    [Backend]:          Loading Screen Ready
(22:18:58) INFO:    [Frontend]:         Refreshing undefined Library
(22:18:58) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:18:58) INFO:    [Backend]:          Frontend Ready
(22:18:58) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.2

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Garuda KERNEL: 6.1.31-x64v1-xanmod1-1-lts ARCH: x64
CPU: Intel Core™ i5-1035G1 @1 GOVERNOR: powersave
RAM: Total: 7.54 GiB Available: 2.71 GiB
GRAPHICS: GPU0: Iris Plus Graphics G1  VRAM: 256MB GPU1: NVIDIA GeForce MX350 VRAM: 2001MB DRIVER: 530.41.03
PROTOCOL: wayland

(22:18:58) INFO:    [Backend]:          Checking for new Heroic Updates
(22:18:58) INFO:    [Backend]:          Checking for current version changelog
(22:18:58) INFO:    [Legendary]:        Running command: /usr/bin/legendary list --third-party
(22:18:58) INFO:    [Gog]:              Saved username to config file
(22:19:00) INFO:    [Winetricks]:       Downloading Winetricks
(22:19:02) INFO:    [Gog]:              Found 0 game(s) to update
(22:19:03) INFO:    [Backend]:          Starting the Download Queue
(22:19:03) INFO:    [Legendary]:        Checking for game updates: /usr/bin/legendary list --third-party
(22:19:06) DEBUG:   [Legendary]:        Update is available for 40cb42e38c0b4a14a1bb133eb3291572: IdleDragons51464Live != IdleDragons51764Live
(22:19:06) INFO:    [Legendary]:        Found 1 game to update
(22:19:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for CDPR Goodie Pack Content
(22:19:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json auth
(22:19:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for CDPR Goodie Pack Content
(22:19:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json auth
(22:19:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json auth
(22:19:10) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json auth
(22:19:11) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json info 1185685769 --token <redacted> --lang=en-US --os windows
(22:19:11) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json info 1185685769 --token <redacted> --lang=en-US --os windows
(22:19:11) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json info 1185685769 --token <redacted> --lang=en-US --os windows
(22:19:11) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/lfom/.config/heroic/gog_store/auth.json info 1185685769 --token <redacted> --lang=en-US --os windows
(22:19:11) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(22:19:11) ERROR:   [Frontend]:         Cannot get game info
(22:19:11) ERROR:   [Frontend]:         Cannot get game info
(22:19:11) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(22:19:11) ERROR:   [Frontend]:         Cannot get game info
(22:19:11) ERROR:   [Frontend]:         Cannot get game info
(22:19:12) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(22:19:12) ERROR:   [Frontend]:         Cannot get game info
(22:19:12) ERROR:   [Frontend]:         Cannot get game info
(22:19:12) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(22:19:12) ERROR:   [Frontend]:         Cannot get game info
(22:19:12) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

1. Go Library
2. Search for any "Goodies" packages from GOG
3. Click on a Goodie pack to get more info

### Expected behavior

As I said, it worked in the past, before the major visual changes (before 2.5.0, maybe?), it used to display the info about the package just like games. Actually, some packages even include "abandonware" versions of games, but I have never tried to install them in Heroic.

### Screenshots

![Screenshot from 2023-06-03 22-40-44](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/15659999/9cec941f-473c-40eb-a066-9c3f6f9ab2ce)

### Heroic Version

Latest Stable

### System Information

- OS: Garuda/Arch

### Additional information

I have tried the normal stuff:

- cleared cache
- reset Heroic (it erased all games config, I am glad I had a backup)
- Login again to my GOG account

I did a search for Goodies and "cannot get game info" and found nothing related, I hope I did not missed anything.

There are some glitches with the login/logout with the accounts, but I saw other open issues about it, hopefully it will be fixed soon. It is weird to enter the account token and then have to login again to browse the store in the app...

Thanks again!

Regards

**Comment by arielj** [comment] 2023-06-04 03:08
this is kinda a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2002

we don't support downloading the goodies content, so we should not list them at all (but I couldn't find a clear way to filter them out)

**Closed by arielj** 2023-06-04 03:08 UTC

**Comment by lfom** [comment] 2023-06-04 17:23
@arielj Thank you for your reply. I'm sorry, but:

- 1. The problem reported isn't related to crashing, but not displaying the package and telling the user to do things that can cause problems (resetting Heroic causes loss of games config);

2. It used to work, displaying the rebates info in previous versions.

I don't see why they should be hidden, maybe work just like unsupported games: display a badge and hide them if the user enable this option, otherwise just show the relevant info ;or even seems to do so before covering the screen with the error message).
