### ISSUE TITLE
Cannot install Dragon Age Inquisition (epic)

### ISSUE THREAD

**Issue by kenderipa** [Heroic-Games-Launcher/HeroicGamesLauncher#3774] opened 2024-05-21 10:03 UTC
### Describe the bug

Hello,

I cannot install recently obtained DAI. In the pre-installation window the download size is shown as 1.08KiB and the install size as 4 B. The reloggint into Epic account didn't help. If clicked Install, notification about starting and finishing installtions are shown, the game is not installed.

### Add logs

```text
-
```

### Steps to reproduce

1. Try to install DAI

### Expected behavior

Should install normally

### Heroic Version

Latest Stable

### System Information

Debian Trixie

### Additional information

XServer, JWM

**Comment by imLinguin** [comment] 2024-05-21 10:09
Duplicate of #3762

**Closed by imLinguin** 2024-05-21 10:09 UTC
Labels: bug:unconfirmed
