### ISSUE TITLE
Misleading Icon in Downloads Tab

### ISSUE THREAD

**Issue by iacore** [Heroic-Games-Launcher/HeroicGamesLauncher#2883] opened 2023-07-22 20:56 UTC
### Describe the bug

![removef](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/74560659/6c0cb1d4-c0d1-4f0a-b483-486c287cdccb)

I don't think the description and the icon match.

### Add logs

```text
N/A
```

### Steps to reproduce

1. Download some game fully
2. Go to the "Downloads" Tab
3. See the button under "Completed"

### Expected behavior

I have no idea what the expected behavior of the button is.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Linux

**Comment by arielj** [comment] 2023-07-29 19:38
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2485

**Closed by arielj** 2023-07-29 19:38 UTC
Labels: bug:unconfirmed
