### ISSUE TITLE
Updating Cyberpunk 2077 on GoG

### ISSUE THREAD

**Issue by szentigrad3** [Heroic-Games-Launcher/HeroicGamesLauncher#1787] opened 2022-09-08 12:27 UTC
### Describe the bug

The update wont go away after updating and wants to keep updating over and over

### Screenshots

https://i.imgur.com/4VSntJL.png

### System Information

- OS [e. g. "Ubuntu"]:  Windows 11
- Heroic Version [e. g. 2.1.1]: 2.4.2

**Comment by Antagram** [comment] 2022-09-09 19:24
Mine get's stuck on 0,42%

**Comment by modestub0203** [comment] 2022-09-20 03:21
No previous installation, after I paused download to sleep, the next day I pressed update/repair and it occasionally downloaded in increments of 10 MB. During the download my steam crashed trying to download other games and my firefox froze briefly after clicking off youtube. Armory crate an asus system software had updates to install and they look much longer than what I'm used to with my SSD. I probably shouldn't have installed cyberpunk on an external HDD over usb and I assume the reason my firefox stutters as I write this post is due to poor file handling on windows as I've had no issues using gogdl in lutris on my exHDD linux laptop.
If I dont edit this post please assume my cyberpunk install has finished processing files (its only been around a day or two so far btw)

**Comment by davidM-tugraz** [comment] 2022-09-20 07:45
Also got stuck on updating. A few hours later it said that it was done, but the install folder suddenly was only 4GB.
After reinstalling the game Heroic still insists that there is an update available, even though in-game the game tells me that it's already at 1.6.

- OS: Fedora 36
- Heroic Version: 2.4.3 (installed via RPM)

![Bildschirmfoto vom 2022-09-20 09-40-41](https://user-images.githubusercontent.com/56354350/191197802-c3d1d906-a913-48b1-9b12-8a405ceea20c.png)

![Bildschirmfoto vom 2022-09-20 09-41-58](https://user-images.githubusercontent.com/56354350/191197850-e3a97130-12c7-4bb9-98ab-c7b016e1cbad.png)

**Comment by davidM-tugraz** [comment] 2022-10-01 07:13
@flavioislima 
Thanks for your reply. I tried the update again and this time it was finished within a couple of minutes and the install folder size seems reasonable (68,5GB instead of 4GB last time), so the update worked fine this time and the version number did not change.

Just strange that it nuked the install the first time I tried to update and had to redownload the whole game, but glad it worked this time.

**Comment by davidM-tugraz** [comment] 2022-11-30 08:10
Well it's happening again.
Yesterday it downloaded the whole game again when clicking on update (heroic version 2.4.3), and today it always says that there is an update available (version 2.5.0).
I've clicked on update and let it download things at least 6 times now, but the message always re-appears.

OS: Fedora 36
Heroic Version: 2.5.0 (installed via RPM)

**Comment by arielj** [comment] 2023-06-02 02:55
closing since it's been many months, we can reopen if this still happens in Heroic 2.8.0

**Closed by arielj** 2023-06-02 02:55 UTC

**Comment by Gamertech** [comment] 2023-07-24 06:40
This is still happening on 2.8.0.

GoG Cyberpunk version 1.63_Hotfix is stuck in an update loop atm. Directory size is still 64GB. It doesn't look like there's any actual update to my client available.

From the looks of it, GoG released a 1.63 > 1.63 hotfix update, but immediately after released the whole 1.63_hotfix client in 28 parts. idk if that would effect it. Heroic could be trying to grab the latest download which is only a small part of the client, failing and fetching it again instead of getting the actual update file.

```(15:55:22) INFO:    [Backend]:          Loading Screen Ready
(15:55:23) INFO:    [Frontend]:         Refreshing undefined Library
(15:55:23) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:55:23) INFO:    [Backend]:          Frontend Ready
(15:55:23) INFO:    [Backend]:          Checking for current version changelog
(15:55:23) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:55:23) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(15:55:24) INFO:    [Gog]:              Found 1 game(s) to update
(15:55:24) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(15:55:24) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:24) INFO:    [Backend]:          Preventing machine to sleep
(15:55:24) INFO:    [Gog]:              Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1423049311 --token <redacted> --lang=en-US --os windows
(15:55:24) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:55:24) INFO:    [Gog]:              Saved username to config file
(15:55:25) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:55:25) INFO:    [Winetricks]:       Downloading Winetricks
(15:55:25) INFO:    [Legendary]:        Found 0 games to update
(15:55:28) INFO:    [Backend]:          Starting the Download Queue
(15:55:28) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.
(15:55:28) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:28) INFO:    [Gog]:              Updating 1423049311: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3
(15:55:28) DEBUG:   [Gog]:              Logging to file "/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(15:55:33) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(15:55:34) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/171.09MB/00:18:39 Down: 0MB/s / Disk: 0MB/s
(15:55:35) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/171.09MB/00:24:52 Down: 0MB/s / Disk: 0MB/s
(15:55:38) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:05:42 Down: 0MB/s / Disk: 0MB/s
(15:55:39) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:09:07 Down: 0MB/s / Disk: 0MB/s
(15:55:40) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:10:15 Down: 0MB/s / Disk: 0MB/s
(15:55:42) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:11:24 Down: 0MB/s / Disk: 0MB/s
(15:55:43) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:13:41 Down: 0MB/s / Disk: 0MB/s
(15:55:45) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:14:49 Down: 0MB/s / Disk: 0MB/s
(15:55:47) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:17:06 Down: 0MB/s / Disk: 0MB/s
(15:55:47) INFO:    [Backend]:          Trying to kill 1423049311
(15:55:47) INFO:    [Backend]:          Killed 1423049311
(15:55:47) INFO:    [Gog]:              Abort command "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3"
(15:55:47) INFO:    [DownloadManager]:  Finished Update of 1423049311
(15:55:47) INFO:    [Frontend]:         Refreshing gog Library
(15:55:47) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:47) INFO:    [Gog]:              Getting GOG library
(15:55:48) INFO:    [Gog]:              Number of library pages: 2
(15:55:48) INFO:    [Gog]:              Getting data for page 2
(15:55:49) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:49) INFO:    [Gog]:              Saved games data
(15:55:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:55:50) INFO:    [Gog]:              Found 1 game(s) to update
(15:55:50) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(15:55:50) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.
(15:55:50) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:55:50) INFO:    [Backend]:          Preventing machine to sleep
(15:55:50) INFO:    [Gog]:              Updating 1423049311: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3
(15:55:50) DEBUG:   [Gog]:              Logging to file "/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(15:55:55) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(15:55:56) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:03:25 Down: 0MB/s / Disk: 0MB/s
(15:55:59) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:04:33 Down: 0MB/s / Disk: 0MB/s
...
(15:57:37) INFO:    [Gog]:              Progress for Cyberpunk 2077: 62.77%/40136.86MB/00:01:01 Down: 0MB/s / Disk: 0MB/s
(15:57:39) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:33 Down: 0MB/s / Disk: 0MB/s
(15:57:46) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:57:52) INFO:    [DownloadManager]:  Finished Update of 1423049311
(15:57:52) INFO:    [DownloadManager]:  1423049311 added to download manager finished.
(15:57:52) INFO:    [DownloadManager]:  1423049311 removed from download manager.
(15:57:52) INFO:    [Frontend]:         Refreshing gog Library
(15:57:52) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:57:52) INFO:    [Backend]:          Stopping Power Saver Blocker
(15:57:52) INFO:    [Gog]:              Getting GOG library
(15:57:52) INFO:    [Gog]:              Number of library pages: 2
(15:57:52) INFO:    [Gog]:              Getting data for page 2
(15:57:53) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:57:54) INFO:    [Gog]:              Saved games data
(15:57:54) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(15:57:59) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Cached ExtraGameInfo data for Cyberpunk 2077 outdated.
(15:57:59) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Cyberpunk 2077
(15:57:59) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:57:59) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Cached ExtraGameInfo data for Cyberpunk 2077 outdated.
(15:57:59) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Cyberpunk 2077
(15:57:59) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Cyberpunk 2077
(15:57:59) INFO:    [Gog]:              Found 1 game(s) to update
(15:57:59) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(15:57:59) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:57:59) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.
(15:58:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:00) INFO:    [Gog]:              Updating 1423049311: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3
(15:58:00) DEBUG:   [Gog]:              Logging to file "/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(15:58:00) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Cyberpunk 2077 Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:58:00) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Cyberpunk 2077 Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/app/bin/heroic/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(15:58:02) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:33 Down: 0MB/s / Disk: 0MB/s
(15:58:04) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(15:58:05) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/171.09MB/00:18:39 Down: 0MB/s / Disk: 0MB/s
...
(15:58:18) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:18:15 Down: 0MB/s / Disk: 0MB/s
(15:58:19) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:19:23 Down: 0MB/s / Disk: 0MB/s
(15:58:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(15:58:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(15:58:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:20) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:20:31 Down: 0MB/s / Disk: 0MB/s
(15:58:21) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:21) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(15:58:21) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:21:40 Down: 0MB/s / Disk: 0MB/s
(15:58:22) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:22:48 Down: 0MB/s / Disk: 0MB/s
(15:58:25) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:23:57 Down: 0MB/s / Disk: 0MB/s
(15:58:26) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(15:58:27) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:27:22 Down: 0MB/s / Disk: 0MB/s
(15:58:28) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:29:39 Down: 0MB/s / Disk: 0MB/s
(15:58:29) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:30:47 Down: 0MB/s / Disk: 0MB/s
(15:58:31) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:31:56 Down: 0MB/s / Disk: 0MB/s
(15:58:32) INFO:    [Gog]:              Progress for Cyberpunk 2077: 9.87%/6309.93MB/00:04:34 Down: 0MB/s / Disk: 0MB/s
(15:58:32) INFO:    [Frontend]:         Refreshing wine downloader releases
(15:58:32) INFO:    [WineDownloader]:   Updating wine versions info
(15:58:32) INFO:    [WineDownloader]:   Fetching upstream information...
(15:58:33) INFO:    [Gog]:              Progress for Cyberpunk 2077: 9.87%/6309.93MB/00:04:43 Down: 0MB/s / Disk: 0MB/s
(15:58:34) INFO:    [WineDownloader]:   wine versions updated
(15:58:34) INFO:    [Gog]:              Progress for Cyberpunk 2077: 9.87%/6309.93MB/00:04:52 Down: 0MB/s / Disk: 0MB/s
(15:58:37) INFO:    [Gog]:              Progress for Cyberpunk 2077: 9.87%/6309.93MB/00:05:01 Down: 0MB/s / Disk: 0MB/s
...
(15:59:58) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:36 Down: 0MB/s / Disk: 0MB/s
(16:00:00) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:37 Down: 0MB/s / Disk: 0MB/s
(16:00:02) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:37 Down: 0MB/s / Disk: 0MB/s
(16:00:03) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:04) INFO:    [DownloadManager]:  Finished Update of 1423049311
(16:00:04) INFO:    [DownloadManager]:  1423049311 added to download manager finished.
(16:00:04) INFO:    [DownloadManager]:  1423049311 removed from download manager.
(16:00:04) INFO:    [Frontend]:         Refreshing gog Library
(16:00:04) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:00:04) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:00:04) INFO:    [Gog]:              Getting GOG library
(16:00:05) INFO:    [Gog]:              Number of library pages: 2
(16:00:05) INFO:    [Gog]:              Getting data for page 2
(16:00:05) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:00:06) INFO:    [Gog]:              Saved games data
(16:00:06) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:00:07) INFO:    [Gog]:              Found 1 game(s) to update
(16:00:07) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(16:00:07) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:07) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.
(16:00:07) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:00:07) INFO:    [Gog]:              Updating 1423049311: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3
(16:00:07) DEBUG:   [Gog]:              Logging to file "/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(16:00:12) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
(16:00:13) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/171.09MB/00:18:39 Down: 0MB/s / Disk: 0MB/s
(16:00:14) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/171.09MB/00:24:52 Down: 0MB/s / Disk: 0MB/s
(16:00:16) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:05:42 Down: 0MB/s / Disk: 0MB/s
(16:00:17) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:07:59 Down: 0MB/s / Disk: 0MB/s
(16:00:18) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:09:07 Down: 0MB/s / Disk: 0MB/s
(16:00:19) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:10:15 Down: 0MB/s / Disk: 0MB/s
(16:00:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(16:00:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Cyberpunk 2077
(16:00:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:19) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:20) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:11:24 Down: 0MB/s / Disk: 0MB/s
(16:00:21) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:12:32 Down: 0MB/s / Disk: 0MB/s
(16:00:30) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:00:30) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:13:41 Down: 0MB/s / Disk: 0MB/s
(16:00:30) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(16:00:31) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:23:57 Down: 0MB/s / Disk: 0MB/s
(16:00:32) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:25:05 Down: 0MB/s / Disk: 0MB/s
(16:00:33) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:26:14 Down: 0MB/s / Disk: 0MB/s
(16:00:33) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
...
(16:02:02) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:35 Down: 0MB/s / Disk: 0MB/s
(16:02:05) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:35 Down: 0MB/s / Disk: 0MB/s
(16:02:08) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:36 Down: 0MB/s / Disk: 0MB/s
(16:02:10) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:14) INFO:    [DownloadManager]:  Finished Update of 1423049311
(16:02:14) INFO:    [DownloadManager]:  1423049311 added to download manager finished.
(16:02:14) INFO:    [DownloadManager]:  1423049311 removed from download manager.
(16:02:14) INFO:    [Frontend]:         Refreshing gog Library
(16:02:14) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:02:14) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:02:14) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:14) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:14) INFO:    [Gog]:              Getting GOG library
(16:02:15) INFO:    [Gog]:              Number of library pages: 2
(16:02:15) INFO:    [Gog]:              Getting data for page 2
(16:02:16) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:02:17) INFO:    [Gog]:              Saved games data
(16:02:17) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:02:17) INFO:    [Gog]:              Found 1 game(s) to update
(16:02:17) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(16:02:17) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:17) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.
(16:02:17) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(16:02:17) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:17) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:17) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:17) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:18) INFO:    [Gog]:              Updating 1423049311: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3
(16:02:18) DEBUG:   [Gog]:              Logging to file "/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1423049311.log"
(16:02:20) INFO:    [Gog]:              Progress for Cyberpunk 2077: 75.97%/48576.48MB/00:00:37 Down: 0MB/s / Disk: 0MB/s
(16:02:22) INFO:    [Gog]:              Progress for Cyberpunk 2077: 0.27%/0.00MB/00:00:00 Down: 0MB/s / Disk: 0MB/s
...
(16:02:31) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:12:32 Down: 0MB/s / Disk: 0MB/s
(16:02:32) INFO:    [Gog]:              Progress for Cyberpunk 2077: 1.44%/921.79MB/00:13:41 Down: 0MB/s / Disk: 0MB/s
(16:02:32) INFO:    [Backend]:          Trying to kill 1423049311
(16:02:32) INFO:    [Backend]:          Killed 1423049311
(16:02:32) INFO:    [DownloadManager]:  1423049311 removed from download manager.
(16:02:32) INFO:    [Gog]:              Abort command "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1423049311 --platform windows "--path=/mnt/games/Heroic/Cyberpunk 2077" --token <redacted> --skip-dlcs --lang=en-US --max-workers 3"
(16:02:32) INFO:    [DownloadManager]:  Finished Update of 1423049311
(16:02:32) INFO:    [DownloadManager]:  1423049311 added to download manager finished.
(16:02:32) INFO:    [DownloadManager]:  1423049311 removed from download manager.
(16:02:32) INFO:    [Frontend]:         Refreshing undefined Library
(16:02:32) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:02:32) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:02:33) INFO:    [Gog]:              Found 1 game(s) to update
(16:02:33) INFO:    [Gog]:              Auto-Updating Cyberpunk 2077
(16:02:33) INFO:    [Gog]:              Got install info from cache for 1423049311 on windows platform
(16:02:33) INFO:    [DownloadManager]:  Cyberpunk 2077  was added to the download queue.```

**Comment by Gamertech** [comment] 2023-07-25 10:00
Issue did not occur with the same update on 2.9.0

**Comment by matthieuHenocque** [comment] 2025-01-25 12:34
The issue is still happening with version 2.15.2 of Heroic on macOS, updating CyberPunk
