### ISSUE TITLE
"Cannot get game info" on DOOM 3: BFG Edition. GOG version

### ISSUE THREAD

**Issue by Rathmox** [Heroic-Games-Launcher/HeroicGamesLauncher#3622] opened 2024-03-09 11:13 UTC
### Describe the bug

When I open the game page, it loads the details, but instantly shows "Cannot get game info".
I also cannot install or load an already installed version.
I tried resetting Heroic, removing and re-adding my account, it's still broken

### Add logs

```text
(12:07:50) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:07:50) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:07:50) INFO:    [Connection]:       Connectivity: check-online
(12:07:50) INFO:    [Connection]:       Pinging external endpoints
(12:07:50) INFO:    [Gog]:              Checking for existing gog manifests
(12:07:50) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(12:07:50) WARNING: [Backend]:          Failed to register protocol with OS.
(12:07:50) INFO:    [Connection]:       Connectivity: online
(12:07:50) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:07:50) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(12:07:50) INFO:    [Frontend]:         Refreshing undefined Library
(12:07:50) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:07:50) INFO:    [Legendary]:        Refreshing library...
(12:07:50) INFO:    [Legendary]:        Refreshing Epic Games...
(12:07:50) INFO:    [Backend]:          Frontend Ready
(12:07:50) INFO:    [Backend]:          Checking for current version changelog
(12:07:51) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:07:52) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:07:52) INFO:    [Winetricks]:       Downloading Winetricks
(12:07:55) INFO:    [WineDownloader]:   Updating wine versions info
(12:07:55) INFO:    [WineDownloader]:   Fetching upstream information...
(12:07:55) INFO:    [Backend]:          Starting the Download Queue
(12:07:58) INFO:    [Legendary]:        Game list updated, got 216 games & DLCs
(12:07:58) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:07:59) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(12:08:02) INFO:    [WineDownloader]:   wine versions updated
(12:08:04) DEBUG:   [Legendary]:        Update is available for 0a2d9f6403244d12969e11da6713137b: EGS_5226 != EGS_5527
(12:08:04) INFO:    [Legendary]:        Found 1 game to update
(12:08:10) INFO:    [Gog]:              Logging using GOG credentials
(12:08:10) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth --code <redacted>
(12:08:11) INFO:    [Gog]:              Login Successful
(12:08:11) INFO:    [Gog]:              Checking if login is valid
(12:08:11) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:12) INFO:    [Gog]:              Saved username to config file
(12:08:12) INFO:    [Frontend]:         Refreshing gog Library
(12:08:12) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:12) INFO:    [Gog]:              Getting GOG library
(12:08:12) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:15) WARNING: [Backend]:          No clientId in goggame-1435828198.info file. Cannot resolve save path
(12:08:15) WARNING: [Backend]:          No clientId in goggame-1441704824.info file. Cannot resolve save path
(12:08:15) WARNING: [Backend]:          No clientId in goggame-1441704920.info file. Cannot resolve save path
(12:08:15) WARNING: [Backend]:          No clientId in goggame-1441704976.info file. Cannot resolve save path
(12:08:15) INFO:    [Gog]:              Saved games data
(12:08:18) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting GamesDB data for DOOM 3 BFG Edition
(12:08:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:18) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for DOOM 3 BFG Edition
(12:08:18) INFO:    [ExtraGameInfo]:    Getting GamesDB data for DOOM 3 BFG Edition
(12:08:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:18) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:18) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:08:18) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:08:20) DEBUG:   [Backend]:          ProtonDB data for 208200 {"bestReportedTier":"platinum","confidence":"strong","score":0.57,"tier":"gold","total":116,"trendingTier":"gold"}
(12:08:20) DEBUG:   [Backend]:          ProtonDB data for 208200 {"bestReportedTier":"platinum","confidence":"strong","score":0.57,"tier":"gold","total":116,"trendingTier":"gold"}
(12:08:20) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:08:20) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:08:20) ERROR:   [Frontend]:         Cannot get game info
(12:08:20) ERROR:   [Frontend]:         Cannot get game info
(12:08:20) ERROR:   [Frontend]:         Cannot get game info
(12:08:20) DEBUG:   [Backend]:          SteamDeck data for 208200 {"success":1,"results":{"appid":208200,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}
(12:08:21) DEBUG:   [Backend]:          SteamDeck data for 208200 {"success":1,"results":{"appid":208200,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}
(12:08:21) ERROR:   [Frontend]:         Cannot get game info
(12:08:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for DOOM 3 BFG Edition
(12:08:23) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for DOOM 3 BFG Edition
(12:08:23) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:23) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:23) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:08:23) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:08:24) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:08:24) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:08:24) ERROR:   [Frontend]:         Cannot get game info
(12:08:24) ERROR:   [Frontend]:         Cannot get game info
(12:08:24) ERROR:   [Frontend]:         Cannot get game info
(12:08:38) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:38) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Wolfenstein Enemy Territory
(12:08:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:38) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:38) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1126166849 --os windows
(12:08:38) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1126166849 --os windows
(12:08:39) DEBUG:   [Backend]:          ProtonDB data for 1873030 {"bestReportedTier":"platinum","confidence":"moderate","score":0.65,"tier":"platinum","total":12,"trendingTier":"platinum"}
(12:08:39) DEBUG:   [Backend]:          ProtonDB data for 1873030 {"bestReportedTier":"platinum","confidence":"moderate","score":0.65,"tier":"platinum","total":12,"trendingTier":"platinum"}
(12:08:39) DEBUG:   [Backend]:          SteamDeck data for 1873030 {"success":1,"results":{"appid":1873030,"resolved_category":0,"resolved_items":[],"steam_deck_blog_url":"","search_id":null}}
(12:08:39) DEBUG:   [Backend]:          SteamDeck data for 1873030 {"success":1,"results":{"appid":1873030,"resolved_category":0,"resolved_items":[],"steam_deck_blog_url":"","search_id":null}}
(12:08:41) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting GamesDB data for The Elder Scrolls Arena
(12:08:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:41) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for The Elder Scrolls Arena
(12:08:41) INFO:    [ExtraGameInfo]:    Getting GamesDB data for The Elder Scrolls Arena
(12:08:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:41) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:08:41) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1435828982 --os windows
(12:08:41) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1435828982 --os windows
(12:08:42) DEBUG:   [Backend]:          ProtonDB data for 1812290 {"bestReportedTier":"platinum","confidence":"moderate","score":0.52,"tier":"gold","total":14,"trendingTier":"gold"}
(12:08:42) DEBUG:   [Backend]:          SteamDeck data for 1812290 {"success":1,"results":{"appid":1812290,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigNotFullyFunctional"},{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}
(12:08:42) DEBUG:   [Backend]:          ProtonDB data for 1812290 {"bestReportedTier":"platinum","confidence":"moderate","score":0.52,"tier":"gold","total":14,"trendingTier":"gold"}
(12:08:42) DEBUG:   [Backend]:          SteamDeck data for 1812290 {"success":1,"results":{"appid":1812290,"resolved_category":2,"resolved_items":[{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigNotFullyFunctional"},{"display_type":3,"loc_token":"#SteamDeckVerified_TestResult_TextInputDoesNotAutomaticallyInvokesKeyboard"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"}],"steam_deck_blog_url":"","search_id":null}}
(12:09:06) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:09:06) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:09:06) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(12:09:07) INFO:    [Backend]:          
System Information:
CPU: 16x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Memory: 16.69 GB (used: 5.2 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER]
    IDs: D=1e81 V=10de SD=13a1 SV=10de
    Driver: nvidia
OS: Arch Linux 6.7.9-arch1-1 (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(12:09:17) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for DOOM 3 BFG Edition
(12:09:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:09:17) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for DOOM 3 BFG Edition
(12:09:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:09:17) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(12:09:17) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:09:17) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info 1135892318 --os windows
(12:09:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:09:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(12:09:19) ERROR:   [Frontend]:         Cannot get game info
(12:09:19) ERROR:   [Frontend]:         Cannot get game info
(12:09:19) ERROR:   [Frontend]:         Cannot get game info
(12:09:19) ERROR:   [Frontend]:         Cannot get game info
(12:09:27) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:09:27) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:09:27) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/alerymin/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

### Steps to reproduce

1. Select the game
2. Info loads
3. Heroic shows "Cannot get game info"

### Expected behavior

Heroic allows installing the gamme

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Arch Linux
- Kernel: 6.7.9-arch1-1

### Additional information

seeing these lines in the log:
```
(12:09:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo

(12:09:19) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo

(12:09:19) ERROR:   [Frontend]:         Cannot get game info

(12:09:19) ERROR:   [Frontend]:         Cannot get game info

(12:09:19) ERROR:   [Frontend]:         Cannot get game info

(12:09:19) ERROR:   [Frontend]:         Cannot get game info
```
I think it's a GOGDL issue, I may be wrong though

**Comment by imLinguin** [comment] 2024-03-09 11:16
Duplicate of #3572

**Closed by imLinguin** 2024-03-09 11:16 UTC
Labels: bug:unconfirmed
