### ISSUE TITLE
exitToTray on mac isn't working

### ISSUE THREAD

**Issue by whitespacecode** [Heroic-Games-Launcher/HeroicGamesLauncher#3441] opened 2024-01-15 10:52 UTC
### Describe the bug

In the settings you can add the option to exit to System Tray.
When doing so the app is closing but you can't re-open the app by clicking on the dock icon.
https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos

### Add logs

```text
(11:41:16) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(11:41:16) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(11:41:16) INFO:    [Connection]:       Connectivity: check-online
(11:41:16) INFO:    [Connection]:       Pinging external endpoints
(11:41:16) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(11:41:16) WARNING: [Backend]:          Protocol already registered.
(11:41:16) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/joeriverstraete/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(11:41:16) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --auth-config-path "/Users/joeriverstraete/Library/Application Support/heroic/gog_store/auth.json" --version
(11:41:16) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH="/Users/joeriverstraete/Library/Application Support/heroic/nile_config" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/nile --version
(11:41:16) INFO:    [Connection]:       Connectivity: online
(11:41:16) INFO:    [Backend]:          User Not Found, removing it from Store
(11:41:16) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(11:41:16) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(11:41:16) INFO:    [Backend]:          Frontend Ready
(11:41:16) INFO:    [Backend]:          Checking for new Heroic Updates
(11:41:16) INFO:    [Backend]:          Checking for current version changelog
(11:41:19) INFO:    [GlobalConfig]:     Searching for Gaming Porting Toolkit Wine
(11:41:19) INFO:    [Winetricks]:       Downloading Winetricks
(11:41:21) INFO:    [WineDownloader]:   Updating wine versions info
(11:41:21) INFO:    [WineDownloader]:   Fetching upstream information...
(11:41:21) INFO:    [Backend]:          Starting the Download Queue
(11:41:22) INFO:    [Backend]:          Heroic: Setting exitToTray to false (previous value: true)
(11:41:22) INFO:    [Backend]:          Heroic: Setting exitToTray to true (previous value: false)
(11:41:22) INFO:    [WineDownloader]:   wine versions updated
(11:41:22) INFO:    [Backend]:          
System Information:
CPU: 10x Apple M1 Pro
Memory: 17.18 GB (used: 6.62 GB)
GPUs:

OS:  14.1.2 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.12.0 Vegapunk
  Legendary: 0.20.34 Direct Intervention
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(11:41:22) INFO:    [Backend]:          Heroic: Setting exitToTray to false (previous value: true)
```

### Steps to reproduce

1. Go to 'settings
2. Click on 'exit to system tray'
3. Click or hide the window
4. Try re-opening the window

### Expected behavior

The window should at least re-open.
Looking at the code maybe this would help in the main process
```
app.on("activate", () => {
    const mainWindow = getMainWindow()
    if(mainWindow){
        mainWindow.show()
    }else{
        createMainWindow();
    }
});
```

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by arielj** [comment] 2024-01-18 01:09
Closing as a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3436 (that issue mentions launching in the title, but also closing to tray in the description)

**Closed by arielj** 2024-01-18 01:09 UTC
Labels: bug:unconfirmed
