### ISSUE TITLE
[Request] Queue downloading and updating Games.

### ISSUE THREAD

**Issue by onurbbr** [Heroic-Games-Launcher/HeroicGamesLauncher#1210] opened 2022-04-16 01:48 UTC
### Problem description

When I need to download/update multiple games in Heroic I have to wait for the game to download and it's very frustrating.

### Feature description

While you are downloading/updating one game in Heroic, you cannot download/update another game. To avoid this, the queuing system would be very logical and useful. Without waiting for the game to be downloaded/updated, it will switch to the download/update process of the next game after the download/update process of the game is finished by putting other games in queue and this process will save time for the user. This will be especially beneficial for users who download/update games at midnight.

### Alternatives

Steam's game download/update system can be a very good example of this.

**Comment by wiryfuture** [comment] 2022-04-23 17:55
Dupe of #457

**Closed by wiryfuture** 2022-04-23 17:55 UTC
Labels: duplicate, feature request
