### ISSUE TITLE
Can not fetch the correct game size"Dragon Age: Inquisition – Game of the Year Edition"form epic

### ISSUE THREAD

**Issue by Boooob626** [Heroic-Games-Launcher/HeroicGamesLauncher#3769] opened 2024-05-19 05:57 UTC
### Describe the bug

Can not fetch the correct game size .It shouldn't  just need 1.08 KiB spaced.And i can not install it. Thank you for the patience. 

### Add logs

```text
(13:41:57) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:41:57) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:41:57) INFO:    [Connection]:       Connectivity: check-online
(13:41:57) INFO:    [Connection]:       Pinging external endpoints
(13:41:57) INFO:    [Gog]:              Checking for existing gog manifests
(13:41:58) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(13:41:58) WARNING: [Backend]:          Protocol already registered.
(13:41:58) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:41:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/bob/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.config/heroic/gog_store/auth.json --version
(13:41:58) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/bob/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:41:58) INFO:    [Backend]:          
System Information:
CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900HX
Memory: 33.28 GB (used: 3.26 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation AD104M [GeForce RTX 4080 Max-Q / Mobile]
    IDs: D=27e0 V=10de SD=8bad SV=103c
    Driver: nvidia
OS: Kali GNU/Linux 2024.1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(13:41:58) INFO:    [Frontend]:         Refreshing undefined Library
(13:41:58) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:41:58) INFO:    [Legendary]:        Refreshing library...
(13:41:58) INFO:    [Legendary]:        Refreshing Epic Games...
(13:41:58) INFO:    [Backend]:          Frontend Ready
(13:41:58) INFO:    [Backend]:          Checking for new Heroic Updates
(13:41:58) INFO:    [Backend]:          Checking for current version changelog
(13:41:58) INFO:    [Connection]:       Connectivity: online
(13:41:58) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/bob/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.config/heroic/gog_store/auth.json auth
(13:41:58) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:41:58) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:41:59) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:42:00) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dragon Age Inquisition – Game of the Year Edition
(13:42:00) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dragon Age Inquisition – Game of the Year Edition
(13:42:00) DEBUG:   [Legendary]:        Using cached install info
(13:42:00) DEBUG:   [Legendary]:        Using cached install info
(13:42:00) INFO:    [Winetricks]:       Downloading Winetricks
(13:42:01) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:01) INFO:    [DXVKInstaller]:    Updating dxvk-nvapi to: dxvk-nvapi-v0.7.0
(13:42:01) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.3.1
(13:42:01) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.12
(13:42:01) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/doitsujin/dxvk/releases/download/v2.3.1/dxvk-2.3.1.tar.gz. 
Error: Error: Client network socket disconnected before secure TLS connection was established
(13:42:01) WARNING: [DXVKInstaller]:    Error when downloading dxvk Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
(13:42:01) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/jp7677/dxvk-nvapi/releases/download/v0.7.0/dxvk-nvapi-v0.7.0.tar.gz. 
Error: Error: Client network socket disconnected before secure TLS connection was established
(13:42:01) WARNING: [DXVKInstaller]:    Error when downloading dxvk-nvapi Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
(13:42:01) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://github.com/Heroic-Games-Launcher/vkd3d-proton/releases/download/v2.12/vkd3d-proton-2.12.tar.xz. 
Error: Error: Client network socket disconnected before secure TLS connection was established
(13:42:01) WARNING: [DXVKInstaller]:    Error when downloading vkd3d Error: Failed to get headers
    at downloadFile (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installOrUpdateTool (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:99:198)
(13:42:03) INFO:    [Legendary]:        Game list updated, got 1 games & DLCs
(13:42:03) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:42:03) INFO:    [WineDownloader]:   Updating wine versions info
(13:42:03) INFO:    [WineDownloader]:   Fetching upstream information...
(13:42:03) INFO:    [Backend]:          Starting the Download Queue
(13:42:03) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:42:03) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:03) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:42:04) INFO:    [WineDownloader]:   wine versions updated
(13:42:04) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) INFO:    [Backend]:          Writing config for verdi
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) INFO:    [DownloadManager]:  Dragon Age: Inquisition – Game of the Year Edition  was added to the download queue.
(13:42:06) INFO:    [Backend]:          Preventing machine to sleep
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) WARNING: [Legendary]:        Failed to parse games from /home/bob/.config/heroic/legendaryConfig/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/bob/.config/heroic/legendaryConfig/legendary/installed.json'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at t.readFileSync (node:electron/js2c/node_init:2:9771)
    at Module.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:114:4090)
    at async /opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:235:3193
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(13:42:06) INFO:    [Legendary]:        Found 0 games to update
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) INFO:    [Legendary]:        Installing verdi: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install verdi --platform Windows --base-path /home/bob/Games/Heroic --skip-dlcs -y --skip-sdl
(13:42:06) DEBUG:   [Legendary]:        Logging to file "/home/bob/.config/heroic/GamesConfig/verdi.log"
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) DEBUG:   [Legendary]:        Using cached install info
(13:42:06) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:06) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:07) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/epic/verdi-epic.json. 
Error: Error: Request failed with status code 404
(13:42:07) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:08) INFO:    [Backend]:          Adding shortcuts for Dragon Age: Inquisition – Game of the Year Edition
(13:42:08) INFO:    [DownloadManager]:  Finished Installation of verdi
(13:42:08) INFO:    [DownloadManager]:  verdi added to download manager finished.
(13:42:08) INFO:    [DownloadManager]:  verdi removed from download manager.
(13:42:08) INFO:    [Frontend]:         Refreshing legendary Library
(13:42:08) INFO:    [Legendary]:        Refreshing library...
(13:42:08) INFO:    [Legendary]:        Refreshing Epic Games...
(13:42:08) DEBUG:   [Legendary]:        Using cached install info
(13:42:08) DEBUG:   [Legendary]:        Using cached install info
(13:42:08) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:08) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:42:09) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:42:09) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:09) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:09) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:42:10) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:10) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:42:11) INFO:    [Legendary]:        Game list updated, got 1 games & DLCs
(13:42:11) DEBUG:   [Legendary]:        Using cached install info
(13:42:11) DEBUG:   [Legendary]:        Using cached install info
(13:42:12) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:13) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:42:13) ERROR:   [Legendary]:        Error: Request failed with status code 403
    at createError (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/Heroic/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/Heroic/resources/app.asar/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:42:13) ERROR:   [Legendary]:        Error Getting Info from Epic API
(13:43:25) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:43:25) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/bob/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.config/heroic/gog_store/auth.json --version
(13:43:25) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/bob/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:43:26) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/bob/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:43:26) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/bob/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.config/heroic/gog_store/auth.json --version
(13:43:26) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/bob/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
```

### Steps to reproduce

1. Own the game
2. Click the install bottom 

### Expected behavior

install normally. 

### Screenshots

file:///home/bob/Pictures/Screenshot_20240519_133918.png

### Heroic Version

Latest Stable

### System Information

-Debian

**Comment by deeply-cynical** [comment] 2024-05-19 08:22
I have the same problem, so I tested using the Epic launcher on a Windows installation.
When installed on Windows through the Epic store, the EA app gets installed and the game installs through that. 
However running the game through the EA App opens the Epic store, both need to be running.

My guess is the installer that Heroic grabs is just a script that downloads and installs via the EA App.

**Comment by imLinguin** [comment] 2024-05-19 11:40
Duplicate of #3762

**Closed by imLinguin** 2024-05-19 11:40 UTC
Labels: bug:unconfirmed
