### ISSUE TITLE
(Windows) Heroic won't login when the user folder has spaces on the name

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#575] opened 2021-07-28 16:08 UTC
**Describe the bug**
When $USER or $HOME has spaces, Heroic can't find the path.

**To Reproduce**
**Note: this bug has been reproduced on Windows. I don't know if it will work the same way on Linux or Mac.**
1. Create a user called 'John Johnson'
2. Download Heroic 1.9.0
3. On a clean install, log in into your epic games account.
4. See error. You can't login.
5. If you can login,you can't see the library. It's empty.

**Expected behavior**
You can log in, you can see your library and you can download, import and play games.

**Screenshots**
Null

**Desktop (please complete the following information):**

- OS: Windows and possibly Unix based
- Version 1.9.0
- Game: Any
- Wine/Proton version: Any
- Hardware specs (RAM, CPU, GPU): Any

**Additional context**
See our discord for more context.

**Comment by flavioislima** [comment] 2021-08-03 17:25
The issue is actually not with the user name but with the folder name.

**Comment by dragonDScript** [comment] 2021-08-03 17:37
> The issue is actually not with the user name but with the folder name.

Alright

**Comment by ArjixWasTaken** [comment] 2021-08-19 12:37
> **Describe the bug**
> When $USER or $HOME has spaces, Heroic can't find the path.
> 
> **To Reproduce**
> **Note: this bug has been reproduced on Windows. I don't know if it will work the same way on Linux or Mac.**
> 
> 1. Create a user called 'John Johnson'
> 2. Download Heroic 1.9.0
> 3. On a clean install, log in into your epic games account.
> 4. See error. You can't login.
> 5. If you can login,you can't see the library. It's empty.
> 
> **Expected behavior**
> You can log in, you can see your library and you can download, import and play games.
> 
> **Screenshots**
> Null
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows and possibly Unix based
> * Version 1.9.0
> * Game: Any
> * Wine/Proton version: Any
> * Hardware specs (RAM, CPU, GPU): Any
> 
> **Additional context**
> See our discord for more context.

In windows the folder username is the first 5 characters from the provided name in lowercase.
`John Johnson` would either be `john` or `johnj`.
I highly doubt that it would be `john `

**Comment by ArjixWasTaken** [comment] 2021-08-19 12:38
But, it would make sense if the userfolder was not in Latin characters.

**Comment by arielj** [comment] 2021-11-07 01:42
I tried this and I can login with no issues with a user name with spaces on windows 10. Maybe this got fixed by another change? or some legendary update? like I shared on this other issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/711 I don't have any problem with spaces in directories when installing games either

**Comment by flavioislima** [comment] 2021-11-07 10:34
> I tried this and I can login with no issues with a user name with spaces on windows 10. Maybe this got fixed by another change? or some legendary update? like I shared on this other issue #711 I don't have any problem with spaces in directories when installing games either
> 
> edit: to clarify, I'm using the latest commit from github, not the latest release binary

I think I fixed this when I created the function to get the legendary binary. I added a workaround to deal with spaces since the binary can be anywhere and this might have fixed this windows issue.

I'll close it and if it's not fixed we can reopen it

**Closed by flavioislima** 2021-11-07 10:34 UTC
Labels: bug:confirmed
