### ISSUE TITLE
Game saving path on macOS

### ISSUE THREAD

**Issue by ikir83** [Heroic-Games-Launcher/HeroicGamesLauncher#1883] opened 2022-10-08 20:42 UTC
### Problem description

Heroic saves game in home folder, it would be more consistent with macOS if th game are saved in Application or Application/Heroic

### Feature description

Saving games in home is not consistent with macOS philosophy. It would make more sense if the downloaded game should be located in Application or Application/Heroic at least.

**Comment by arielj** [comment] 2022-10-10 19:51
Heroic does not define where saves are stored, each game handles that internally and we can't change the path.

If you are using Crossover, it might be Crossover the one translating windows' `Documents` folder as the home folder.

**Comment by flavioislima** [comment] 2022-10-10 22:51
Exactly.
Closing...

**Closed by flavioislima** 2022-10-10 22:51 UTC

**Comment by ikir83** [comment] 2022-10-10 22:56
Sorry I'm not native English speaker, I will try to explain better. I meant game download folder, where Heroic saves games, not "save game" files. For example Subnautica game is downloaded by Heroic in /Users/ikir/Games/Heroic/Subnautica which is incoherent in macOS.

**Comment by arielj** [comment] 2022-10-10 23:49
Hmmm I don't think we can do that, I did try to add shortcuts for games in the /Application folder to have them appear in the app's launcher, but it doesn't work and I tried so many things. I can't confirm this cause I'm not a mac developer, but seems to not be possible to programmatically add things there.

**Comment by ikir83** [comment] 2022-10-11 08:04
And without shortcut? Just the real entire app in Applications/ it should be this way on macOS.
User could have a Heroic folder in Application with Heroic and a subfolder with downloaded games. Or at least ask where the game is downloaded or located if someone wants to move the game.

**Comment by flavioislima** [comment] 2022-10-11 08:10
I see what you mean, @ikir83 
I believe that for native apps that would make sense.
But the problem is: if the game won't be launched through Heroic, how would you use Heroic features like Cloud Saves, for instance?
So Heroic would be only a 'downloader'. This would also lead to issues with games that need authentication from Epic.

So we actually need a way to create a shortcut to a game inside Heroic, that would keep these features but so far our investiigations went anywhere and we don't have a dedicated macOS developer to go deeper on that.

**Comment by ikir83** [comment] 2022-10-11 08:13
I understand. Maybe some macOS devs will join since Heroic si getting popular thank to video like this
https://www.youtube.com/watch?v=L9sTGF_5mXA

Thanks for all your work and thanks for supporting macOS.
