### ISSUE TITLE
Heroic is huge on HiDPi screens. 

### ISSUE THREAD

**Issue by nebadon2025** [Heroic-Games-Launcher/HeroicGamesLauncher#509] opened 2021-07-02 19:49 UTC
### Discussed in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/discussions/508

<div type='discussions-op-text'>

<sup>Originally posted by **nebadon2025** July  2, 2021</sup>
I upgraded to v1.8 and its zoomed to like 200% and it will not let me resize the window at all, also it keeps telling me there is a new version, yet it points me to the same version I already have, i can't even access the whole interface so its basically 100% unuseable now I will include system specs below as well.  I am running in 3840x2160 resolution with 200% desktop scaling in KDE

![heroic1_8_borked_01](https://user-images.githubusercontent.com/693958/124321750-3948c580-db4c-11eb-90da-5eb8eaeea9d7.png)
![heroic1_8_borked_02](https://user-images.githubusercontent.com/693958/124321752-3b128900-db4c-11eb-9325-9a92e0165d37.png)
![heroic1_8_borked_03](https://user-images.githubusercontent.com/693958/124321757-3c43b600-db4c-11eb-9e73-1ff5b3d8aa5a.png)

[System]
OS:              Ubuntu 20.10 groovy
Arch:            x86_64
Kernel:          5.12.14-xanmod1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             62.8 GB
Swap:            32.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.12.14-xanmod1, LLVM 12.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.0-devel (git-25ad699 2021-07-02 groovy-oibaf-ppa)
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.0-devel (git-25ad699 2021-07-02 groovy-oibaf-ppa)
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.0-devel (git-25ad699 2021-07-02 groovy-oibaf-ppa)
Vulkan:          Supported
</div>

**Comment by flavioislima** [comment] 2021-07-02 21:22
Can we mark as fixed since it is an issue with your resolution?

**Comment by nebadon2025** [comment] 2021-07-02 21:36
how is this an issue with my resolution? previous versions did not have this issue.

**Comment by DoppelDoppler** [comment] 2021-07-03 07:06
I've had the exact same issue with similar specs. I was able to bypass the problem by starting the launcher with the flag "--force-device-scale-factor=2".

**Comment by flavioislima** [comment] 2021-07-03 07:15
> I've had the exact same issue with similar specs. I was able to bypass the problem by starting the launcher with the flag "--force-device-scale-factor=2".

Yes exactly. Thanks.

**Comment by wouter1984** [comment] 2021-07-03 11:26
@DoppelDoppler --> Great comment this fixed my issue as well

I have the same issue on kUbuntu 20.04 LTS with 3840x2160 resolution with 200% scaling on KDE desktop...
I can confirm that changing my Heroic Launcher shortcut with the "--force-device-scale-factor=2" flag fixes the issue for now.

example of my shortcut command:
![image](https://user-images.githubusercontent.com/86877318/124352708-4a540e00-dc02-11eb-8139-57308f780e21.png)

**Comment by nebadon2025** [comment] 2021-07-06 13:18
This fix has to be reapplied every time you update

**Comment by wouter1984** [comment] 2021-07-06 13:22
agree this is a workaround and not a fix... My screenshot above was for version 1.8.1.

I do see version 1.8.2 of Heroic has been released. So I will check the updated version to see if the issue is still persistent in version 1.8.2.

**Comment by flavioislima** [comment] 2021-07-06 14:11
I did some investigation to put a fix on 1.8.2 and could not find anything. Unfortunately, we won't be able to fix this on our side. I can force a scale factor, but that would not fix for everyone I guess.

**Comment by wouter1984** [comment] 2021-07-06 14:15
> how is this an issue with my resolution? previous versions did not have this issue.

I agree that in the 1.7.x builds the issue was not present... At least glad I have a workaround. Because Heroic on Linux is amazing!

**Comment by flavioislima** [comment] 2021-07-06 14:36
> > how is this an issue with my resolution? previous versions did not have this issue.
> 
> I agree that in the 1.7.x builds the issue was not present... At least glad I have a workaround. Because Heroic on Linux is amazing!

I think the issue might have been introduced with Electron 13. Since we upgrade it on 1.8 build. 1.7 used electron 12.
The thing is that electron 13 brings several other improvements and features and has better memory usage as well. I just expect that electron 14 fixes this.
I'll do more research onto the electron community.

**Comment by wouter1984** [comment] 2021-07-06 14:40
OK I will keep monitoring the upgrades for Heroic anyways... So keep up the good work and let's hope electron 14 will fix the issue eventually like you said.

**Comment by arielj** [comment] 2022-05-13 00:00
hey! @wouter1984 @nebadon2025 @DoppelDoppler can you check the build from this PR? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1281

hopefully it adds improvements on your devices (support for smaller window size so it can fit the screen, automatic zoom in so heroic doesn't look too big, and accessibility options to further tweak the zoom level if needed)

**Comment by wouter1984** [comment] 2022-05-13 08:48
@arielj Do you want me to install the [2.3.0 Beta 3] version? If so I can try to install later today when I am back from the office.

**Comment by flavioislima** [comment] 2022-05-13 09:40
@wouter1984 no, this is not released on the beta. You need to download from here:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2316614702

**Comment by flavioislima** [comment] 2022-05-15 11:19
so can we close this one?

**Comment by wouter1984** [comment] 2022-05-15 11:32
@flavioislima I vote yes

**Comment by arielj** [comment] 2022-05-15 20:35
Closing this, seems like the zoom features in Heroic 2.3.1 solved this issue.

**Closed by arielj** 2022-05-15 20:35 UTC
Labels: bug:confirmed, enhancement
