### ISSUE TITLE
[GOG/EPIC] HOWTO: Witcher 3 (next gen) 

### ISSUE THREAD

**Issue by nolt** [Heroic-Games-Launcher/HeroicGamesLauncher#2202] opened 2022-12-15 08:02 UTC
### Describe the bug

This is not a bug report, rather quick FAQ how to run the game (I didn't found any solutions to this anywhere).

The Witcher 3 (Next Gen) runs default with DirectX 12 (using GOG version; Steam version comes with REDLauncher where you can choose DirectX version) while game is able to launch it eventually crash after loading besides performance with DirectX12 is not very good.

To launch Witcher 3 we must point out .exe with DirectX11 version in game settings in Heroic Launcher
![other_exe_run](https://user-images.githubusercontent.com/6367933/207802453-93f54b76-b207-4d9c-a175-f7fba0e5eea0.png)
Well it's simple but for now there is no other way to play it I suppouse.

I tried to launch game with arguments but it won't work (i.e. -dx11 etc).
This solution has been tested on Linux (Ubuntu 22.04) and also on Steam Deck - game works as it should.

### Add logs

_no additional info_

### Steps to reproduce

_no additional info_

### Expected behavior

_no additional info_

### System Information

- OS: Ubuntu 22.04
- Heroic Version: 2.5.2

**Comment by mfcodeworks** [comment] 2022-12-15 08:56
Where can I actually find the dx11 exe? I tried the `bin/x64/witcher3.exe` file but that crashes immediately on launch, which is worse than dx12 exe which at least gets to the menu.

**Comment by imLinguin** [comment] 2022-12-15 09:23
Attach goggame-someid.info, there might be some clues about game options

**Comment by nolt** [comment] 2022-12-15 10:00
@mfcodeworks 
You pointed correct .exe. Be sure that you have checkbox dxvk enabled. FYI I use Wine-GE-Proton7-31 prefix.

**Comment by mfcodeworks** [comment] 2022-12-15 10:32
Here's the crash log: 
[1495134320-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10236100/1495134320-lastPlay.log)

@imLinguin where do I pull that info file from?

I've previously been using Proton-GE-42 without issue

@nolt did the DXVK option move in the latest patch? Can't seem to find it now

**Comment by imLinguin** [comment] 2022-12-15 10:34
it's in game directory

**Comment by mfcodeworks** [comment] 2022-12-15 12:12
Thanks for the pointers

@imLinguin here's the game options; dx12 crashes when the gameplay starts after loading which is a known bug. The odd thing is dx11 binary fails to launch for me, not even a loading screen or intro video which dx12 has: 
[goggame-1495134320.info.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10236807/goggame-1495134320.info.txt)

@nolt thanks I knew I'd seen it somewhere, I tried that but same results in wine unfortunately 
[1495134320-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10236818/1495134320-lastPlay.log)

**Comment by mfcodeworks** [comment] 2022-12-15 12:28
I tried Wine-GE-Proton-31 additionally but neither seems to be able to launch anything

**Comment by nolt** [comment] 2022-12-15 12:56
Strange, please try this:
- quit Heroic Launcher
- delete everything in /run/media/mmcblk0p1/Games/Heroic/Prefixes/
- run HeroicLauncher [be sure that Proton 7.0.5 is default comatibility tool (if not choose it from the list in steam overlay) to only launch Heroic] and go to Witcher3 settings
- check that Wine-GE-Proton7-31 is selected for this game
- press button winecfg (it will recreate prefix for the game) wait till it finish
- tick the checkbox DXVK option (you can try to untick and tick again checkbox to be sure it doing something - it should modify prefix)
- go back to game but launch it from detail windos (window where whole description of the game is)
- if nothing happens try to launch it again (first launch can take few seconds longer)

**Comment by mfcodeworks** [comment] 2022-12-15 14:24
> Strange, please try this:
> 
> * quit Heroic Launcher
> * delete everything in /run/media/mmcblk0p1/Games/Heroic/Prefixes/
> * run HeroicLauncher [be sure that Proton 7.0.5 is default comatibility tool (if not choose it from the list in steam overlay) to only launch Heroic] and go to Witcher3 settings
> * check that Wine-GE-Proton7-31 is selected for this game
> * press button winecfg (it will recreate prefix for the game) wait till it finish
> * tick the checkbox DXVK option (you can try to untick and tick again checkbox to be sure it doing something - it should modify prefix)
> * go back to game but launch it from detail windos (window where whole description of the game is)
> * if nothing happens try to launch it again (first launch can take few seconds longer)

Still no luck, Heroic doesn't seem to attempt launch at all when using Wine-GE 
[1495134320-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10237764/1495134320-lastPlay.log)

Even when switching back to dx12 binary it doesn't launch, logs end after the launch command

**Comment by nolt** [comment] 2022-12-15 14:43
When you run winecfg from game settings it opens correctly?

**Comment by Tundraaa** [comment] 2022-12-16 08:02
Hey guys can you help me? i was playing the game normaly but i cant launch it now with Dx11, only with Dx12 but thats very hard on my pc. Im using steam, i allready tried reinstalling game

**Comment by flavioislima** [comment] 2022-12-16 10:14
What worked for me was to update VKD3D on the prefix if you are using Wine-GE. 

I needed to do it manually because Bottles still have not updated their VKD3D repo so it is still 2.7. And we use their version on Heroic.
So, for now,  download from vkd3d repo and replace the DLLs on the prefix:
`d3d12 x86 dlls -> syswow64`
`d3d12 x64 dlls -> system32`

https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.8

With Proton 7.0.5 the game on DX12 worked just fine, just make sure you have the latest update of Proton.

**Comment by mfcodeworks** [comment] 2022-12-16 10:19
> > When you run winecfg from game settings it opens correctly?
> 
> winecfg and winetricks both work, but now dx12 fails to launch even with Proton/Proton-GE so it seems no wine versions open my Witcher 3. Might try a reinstall tomorrow to see if that helps anything because this seems like a different issue.

An update on my state; Steam has released a Proton fix for Witcher with dx11 binary so using Proton-experimental worked for dx11. dx12 binary only gave a blank screen but dx11 worked on SteamDeck.

**Comment by flavioislima** [comment] 2022-12-16 10:29
Using Proton 7.0.5 DX12 worked fine, I can see the FSR option on it so I believe it is working.

**Comment by Tundraaa** [comment] 2022-12-16 10:31
Ill try it, im now reinstalling it for second time, i was helpless guys thank you so much

**Comment by Tundraaa** [comment] 2022-12-16 13:38
This is fix for Dx12, but i need fix for Dx11, do you guys have any?

**Comment by imLinguin** [comment] 2022-12-16 13:40
Install `d3dcompiler_47` using winetricks, that should do it

**Comment by Tundraaa** [comment] 2022-12-16 13:49
Im sorry for me being annoying but does it work on Windows 10 also? i saw you wrote something about linux, im sorry im very cluelles about these things guys

**Comment by imLinguin** [comment] 2022-12-16 13:52
Oh, in case of Windows you shouldn't really do anything. In case of GOG you can try installing redistributables from __redist directory in game files

**Comment by Tundraaa** [comment] 2022-12-16 13:54
Yeah im using steam, there isnt any fix for steam?

**Comment by imLinguin** [comment] 2022-12-16 14:04
Not that I'm aware of

**Comment by arcadeblood** [comment] 2022-12-17 06:17
lemme just point out something.
![image](https://user-images.githubusercontent.com/116328606/208228370-3252b8de-cf88-4ad3-819d-8bc6c4a88d8d.png)
Doesn't work?

**Comment by gerritb** [comment] 2022-12-17 08:57
> Using Proton 7.0.5 DX12 worked fine, I can see the FSR option on it so I believe it is working.

On steam deck using heroic?

**Comment by mimimi085181** [comment] 2022-12-19 17:07
Is there a way to use the Classic "beta" channel for the GOG version of Witcher 3? That would be an alternative solution, especially for devices with limited performance and/or storage like the Steam Deck.

And if anyone was not able to fix the game, there's a game update, PC Hotfix, from today, maybe it helps.

**Comment by johnybutelkowiec** [comment] 2022-12-23 19:04
Can anybody post their settings for Steam Deck after the last hotfix? I've tried everything from this thread but the game keeps crashing.

**Comment by nolt** [comment] 2022-12-23 20:53
I have set medium settings with HW & antialiasing off, SSAO off, SSAO reflections low. FPS ~47-55.

**Comment by johnybutelkowiec** [comment] 2022-12-23 21:23
> I have set medium settings with HW & antialiasing off, SSAO off, SSAO reflections low. FPS ~47-55.

Thanks, but I meant Heroic/directX/Proton settings. No matter what I do the game crashes on start up. Some of the comments in this thread suggest different settings, that's why I'm asking for confirmed Steam Deck set up.

**Comment by gerritb** [comment] 2022-12-24 04:58
> > I have set medium settings with HW & antialiasing off, SSAO off, SSAO reflections low. FPS ~47-55.
> 
> Thanks, but I meant Heroic/directX/Proton settings. No matter what I do the game crashes on start up. Some of the comments in this thread suggest different solutions, that's why I'm asking for a confirmed Steam Deck set up.

I got it running using latest ge-proton (43) and directx12 (no alternative exe in heroic). Delete your game prefix in home/deck/games/heroic/prefixes, set the proton version, run winecfg to unpack the prefix. Start the game and wait, start the game again if the first attempt doesn't work (without changing anything).

**Comment by lluukinha** [comment] 2023-01-04 09:16
unfortunately this does not work (at least not on steamdeck).

**Comment by nolt** [comment] 2023-01-10 12:45
> unfortunately this does not work (at least not on steamdeck).

Well I'm playing GOG version on Steam Deck using Dx11 and it work very good.

**Comment by Makotwinsen** [comment] 2023-01-10 22:24
> > unfortunately this does not work (at least not on steamdeck).
> 
> Well I'm playing GOG version on Steam Deck using Dx11 and it work very good.

I was in the same case after updating my game to the last version through heroic launcher (dx12 was working but with high CPU usage and dx11 was crashing systematically on startup).

After a full reinstall of the game with heroic launcher, it is now working with the dx11 exe.

**Comment by flavioislima** [comment] 2023-09-18 09:49
Closing this one since should work fine now by default.

**Closed by flavioislima** 2023-09-18 09:49 UTC
