### ISSUE TITLE
Heroic Games Launcher taking half of my storage for logging

### ISSUE THREAD

**Issue by R0X0RE0** [Heroic-Games-Launcher/HeroicGamesLauncher#1663] opened 2022-08-03 19:59 UTC
### Describe the bug

Heroic doesn't open, then uses half of my storage to write the same line over and over again.

### Add logs

# Heroic Log
```
(15:47:01) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:47:02) ERROR:   [Backend]:         Error: write EPIPE <-- this line gets repeated over and over again
```

### Steps to reproduce

1. Install Heroic as a flatpak
2. Run it once
3. Close it
4. Try to open it again, only for it to not work and then generate large log files.

### Expected behavior

I want my computer to open Heroic without issues. I don't know how to quite explain it, it's just not opening and it's generating a giant log file. I don't see any other person having an issue with this, but feel free to link similar issues.

### System Information

- OS [e. g. "Ubuntu"]: Debian
- Heroic Version [e. g. 2.1.1]: 2.3.9
- Package Manager : flatpak
Output of `sudo flatpak info com.heroicgames[tab completion]` : 

```
Heroic Games Launcher - An Open Source GOG and Epic Games Launcher.

          ID: com.heroicgameslauncher.hgl
         Ref: app/com.heroicgameslauncher.hgl/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v2.3.9
     License: GPL-3.0
      Origin: flathub
 Collection: org.flathub.Stable
Installation: system
    Installed: 410.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 4d62222f94654ef6041297dfa884f9b00b9ff765aad8492ba945352ea25f9e34
      Parent: edec5d991d6b8cd75a2cc40d5579a44fab715b3fd0f5fa7185c5d7f92af7f274
     Subject: [release] v2.3.9 (dc134092)
        Date: 2022-06-15 16:40:16 +0000
```

**Comment by Nocccer** [comment] 2022-08-03 20:12
Duplicate of #1118. Please report there. Also try heroic 2.3.10 or heroic beta.

We also need more informarion about your system.

**Closed** 2022-08-03 20:12 UTC

**Comment by R0X0RE0** [comment] 2022-08-03 23:09
## System Info

<img width="304" alt="image" src="https://user-images.githubusercontent.com/44986343/182727655-a567edf8-960e-4ff0-b0ac-d253cc1c1aea.png">

**Comment by R0X0RE0** [comment] 2022-08-04 00:50
updated to version 2.3.10, issue persists

**Comment by Nocccer** [comment] 2022-08-04 02:57
Can you try the appimage what i posted in the other ticket the exception? I need the stacktrace!

**Comment by Nocccer** [comment] 2022-08-05 10:08
@R0X0RE0 need your help here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1118
Please test the appimage and see if it shows a error message in frontend. I need the stacktrace of the error, to see where it comes from.
