### ISSUE TITLE
Cannot open Amazon games info view

### ISSUE THREAD

**Issue by PawelRaciborski** [Heroic-Games-Launcher/HeroicGamesLauncher#3850] opened 2024-07-04 06:43 UTC
### Describe the bug

 The game info view for Amazon games cannot load. It always finishes with an error `Cannot get game info`.

### Add logs

```text
Amazon/Nile logs:

[7/4/2024, 8:26:02 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
INFO [AUTH_MANAGER]:	 Refreshing token
[7/4/2024, 8:26:03 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
1.0.2 Jonathan Joestar
[7/4/2024, 8:26:03 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
INFO [LIBRARY]:	 Synchronizing library
INFO [LIBRARY]:	 Got next token in response, making next request
INFO [LIBRARY]:	 Got next token in response, making next request
INFO [LIBRARY]:	 Got next token in response, making next request
INFO [LIBRARY]:	 Got next token in response, making next request
INFO [LIBRARY]:	 Successfully synced the library
[7/4/2024, 8:26:12 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
ERROR [LIBRARY]:	 There was an error getting versions
[]
[7/4/2024, 8:27:02 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d
[7/4/2024, 8:27:02 AM] NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d
INFO [CLI]:	 Found: Star Wars: The Force Unleashed
ERROR [LIBRARY]:	 There was an error getting game manifest
Traceback (most recent call last):
  File "nile/cli.py", line 347, in <module>
  File "nile/cli.py", line 328, in main
  File "nile/cli.py", line 161, in handle_install
  File "nile/downloading/manager.py", line 153, in info
  File "nile/downloading/manager.py", line 31, in get_manifest
TypeError: 'NoneType' object is not subscriptable
[227] Failed to execute script 'cli' due to unhandled exception!

Heroic logs:

(08:26:02) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(08:26:02) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(08:26:02) INFO:    [Connection]:       Connectivity: check-online
(08:26:02) INFO:    [Connection]:       Pinging external endpoints
(08:26:02) INFO:    [Gog]:              Checking for existing gog manifests
(08:26:02) INFO:    [Nile]:             Refreshing library...
(08:26:02) INFO:    [Nile]:             Refreshing Amazon Games...
(08:26:02) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(08:26:02) INFO:    [Nile]:             Game list updated, got 205 games
(08:26:02) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(08:26:02) WARNING: [Backend]:          Failed to register protocol with OS.
(08:26:03) INFO:    [Connection]:       Connectivity: online
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:03) INFO:    [Gog]:              Checking if login is valid
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:03) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(08:26:03) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(08:26:03) INFO:    [Nile]:             Saved user data to config file
(08:26:03) INFO:    [Frontend]:         Refreshing undefined Library
(08:26:03) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(08:26:03) INFO:    [Legendary]:        Refreshing library...
(08:26:03) INFO:    [Legendary]:        Refreshing Epic Games...
(08:26:03) INFO:    [Nile]:             Refreshing library...
(08:26:03) INFO:    [Nile]:             Refreshing Amazon Games...
(08:26:03) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(08:26:03) INFO:    [Nile]:             Game list updated, got 205 games
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:03) INFO:    [Backend]:          Frontend Ready
(08:26:03) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(08:26:03) INFO:    [Gog]:              Updating redist, reason - new buildId
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:03) INFO:    [Backend]:
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.54 GB (used: 4.34 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]
    IDs: D=163f V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: LCD) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(08:26:03) INFO:    [Backend]:          Preventing machine to sleep
(08:26:03) INFO:    [Gog]:              Getting GOG library
(08:26:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:03) INFO:    [Gog]:              Getting game metadata: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json info gog-redist --os windows
(08:26:04) INFO:    [Backend]:          Checking for current version changelog
(08:26:04) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:26:04) INFO:    [Gog]:              Saved username to config file
(08:26:04) ERROR:   [Gog]:              stdout = false and res.abort = false in getInstallInfo
(08:26:04) INFO:    [DownloadManager]:  Galaxy Common Redistributables  was added to the download queue.
(08:26:04) INFO:    [Gog]:              Updating GOG redistributables
(08:26:04) INFO:    [Gog]:              GOG REDIST:: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json redist --ids ISI,dotNet4,DirectX,MSVC2005,MSVC2005_x64,MSVC2010,MSVC2010_x64,language_setup,MSVC2008,MSVC2012 --path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/redist/gog
(08:26:04) DEBUG:   [Gog]:              Logging to file "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/gog-redist.log"
(08:26:05) INFO:    [Winetricks]:       Downloading Winetricks
(08:26:05) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:06) INFO:    [DownloadManager]:  gog-redist added to download manager finished.
(08:26:06) INFO:    [DownloadManager]:  gog-redist removed from download manager.
(08:26:06) WARNING: [Backend]:          No clientId in goggame-1.info file. Cannot resolve save path
(08:26:07) INFO:    [Gog]:              Saved games data
(08:26:07) INFO:    [Legendary]:        Game list updated, got 530 games & DLCs
(08:26:07) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:26:07) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:26:07) INFO:    [WineDownloader]:   Updating wine versions info
(08:26:07) INFO:    [WineDownloader]:   Fetching upstream information...
(08:26:08) INFO:    [Backend]:          Starting the Download Queue
(08:26:08) INFO:    [WineDownloader]:   wine versions updated
(08:26:09) INFO:    [Gog]:              Found 0 game(s) to update
(08:26:09) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:26:12) INFO:    [Legendary]:        Found 0 games to update
(08:26:12) INFO:    [Nile]:             Looking for updates...
(08:26:12) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(08:27:02) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Star Wars The Force Unleashed
(08:27:02) INFO:    [ExtraGameInfo]:    Getting GamesDB data for Star Wars The Force Unleashed
(08:27:02) INFO:    [Nile]:             Getting more details
(08:27:02) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d
(08:27:02) INFO:    [Nile]:             Getting more details
(08:27:02) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d
(08:27:03) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(08:27:03) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /app/bin/heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(08:27:03) ERROR:   [Frontend]:         Cannot get game info
(08:27:03) ERROR:   [Frontend]:         Cannot get game info
(08:27:03) ERROR:   [Frontend]:         Cannot get game info
(08:27:05) DEBUG:   [Backend]:          ProtonDB data for 32430 {"bestReportedTier":"platinum","confidence":"strong","score":0.6,"tier":"gold","total":62,"trendingTier":"platinum"}
(08:27:05) DEBUG:   [Backend]:          SteamDeck data for 32430 {"success":1,"results":{"appid":32430,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}
(08:27:05) ERROR:   [Frontend]:         Cannot get game info
(08:27:05) DEBUG:   [Backend]:          ProtonDB data for 32430 {"bestReportedTier":"platinum","confidence":"strong","score":0.6,"tier":"gold","total":62,"trendingTier":"platinum"}
(08:27:06) DEBUG:   [Backend]:          SteamDeck data for 32430 {"success":1,"results":{"appid":32430,"resolved_category":1,"resolved_items":[{"display_type":2,"loc_token":"#SteamDeckVerified_TestResult_SteamOSDoesNotSupport"}],"steam_deck_blog_url":"","search_id":null}}
```

### Steps to reproduce

1. Log into your Amazon account
2. Go to the library
3. Select any game from Amazon
4. Game info view loads briefly and then is replaced with `Cannot get game info`. No interaction with the button fixes it.

### Expected behavior

The game info view is visible.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Device: Steam Deck LCD
- OS: SteamOS 3.5.19 holo

**Comment by CommandMC** [comment] 2024-07-04 08:43
Download Nile from [here](<https://nightly.link/imLinguin/nile/actions/runs/9428563942>), unzip the binary into `~/Games/Heroic`, make sure it's executable, then specify it as an alternative Nile binary in Heroic's advanced settings.
Alternatively, wait for the next release (whenever that'll be)

Duplicate of #3816

**Closed** 2024-07-04 09:40 UTC
Labels: bug:unconfirmed
