### ISSUE TITLE
EA Library and Store

### ISSUE THREAD

**Issue by PaganDegree** [Heroic-Games-Launcher/HeroicGamesLauncher#3571] opened 2024-02-14 22:16 UTC
### Problem description

Would very like to add EA Store and Library natively into Heroic

### Feature description

Create direct connection to EA App Store and Library

**Comment by arielj** [comment] 2024-02-14 22:30
Closing as a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1768 (it says Origin, but it's the EA App now)

Just for context, there is work going into this, but it's in early stages

**Closed by arielj** 2024-02-14 22:30 UTC
Labels: feature-request
