### ISSUE TITLE
 I can't run the game when i start the heroic launcher from steam

### ISSUE THREAD

**Issue by johnsonmiss** [Heroic-Games-Launcher/HeroicGamesLauncher#1453] opened 2022-06-09 14:13 UTC
### Describe the bug

I can't run the game when I start the heroic launcher from steam.But launching heroic from the desktop can run the game normally. All games are like this.

### Add logs

 
Launch Command: SteamGameId=heroic-NeverAlone STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/.wine STEAM_COMPAT_APP_ID=0 PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /home/deck/Downloads/legendary launch f38de9fa4c6d43eabac080942cb394a1 --no-wine --wrapper "/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/run --filesystem=/var/run/media/mmcblk0p1/NeverAlone -- '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-20/proton' waitforexitandrun"

System Info:
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
CPU: AMD Custom APU 0405 @1.76 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 10.96 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/.wine",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-20/proton",
		"name": "Proton - GE-Proton7-20",
		"type": "proton"
	},
	"useSteamRuntime": true
}

Error Log:
[Core] WARNING: Could not determine locale, falling back to en-US
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching f38de9fa4c6d43eabac080942cb394a1...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1639, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-17: ordinal not in range(128)
[226] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

no

### Screenshots

no

### System Information

- OS [steam deck steam os]: 
- Heroic Version [e. g. 2.3.7]:

### Additional information

no

**Comment by cmalvi** [comment] 2022-06-14 07:10
Run it from game mode and works, tried myself

**Comment by Nocccer** [comment] 2022-06-15 15:17
If you use the `heroic --no-gui "heroic://launch/<Game>"` command add `--no-sandbox` to it. Also run steam from terminal and check logs. There are problems where legendary can't get the locale language and defaults to en_US which crashes legendary if you have special character in your epic name.

**Comment by cmalvi** [comment] 2022-06-15 19:38
From game mode it works without any modification

**Comment by Nocccer** [comment] 2022-06-15 21:20
@cmalvi please see my post and try it out. Also run steam from terminal or provide games log, else i can't help.

**Comment by cmalvi** [comment] 2022-06-15 21:28
For me it’s works from game mode, I’ve opened the issue for the desktop mode, sorry if I didn’t specified. Tomorrow I’ll try your suggestion thank you

**Comment by Nocccer** [comment] 2022-06-15 21:58
Ok no problem. Actually i don't know what game mode means? Can you explain it to me so maybe there is something intresting for my pr (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1331)

**Comment by Etaash-mathamsetty** [comment] 2022-06-15 22:30
> Ok no problem. Actually i don't know what game mode means? Can you explain it to me so maybe there is something intresting for my pr (#1331)

it's basically the mode where it shows the steam ui for the steam deck, rather than the kde plasma desktop (that runs on x11)

**Comment by Nocccer** [comment] 2022-06-15 22:33
Ah ok. I will get my steam dexk on friday so i can test my self. Else i would just check what is the difference between game mode and desktop mode by checkong the game logs

**Comment by flavioislima** [comment] 2022-07-21 10:44
@Nocccer could you reproduce it?

**Comment by cmalvi** [comment] 2022-07-21 10:49
To run Heroic Games from game mode, these are my steps:

- Create shortcut from Heroic
- Add to steam the game using the shortcut

Note: Sometimes you have to use GE-proton, sometimes wine-GE, it depends

**Comment by Nocccer** [comment] 2022-07-21 11:03
This is the problem with legendary falls back to loacle en_Us and epic username has special character. I didn't find a fix for that. Workaround is to make the epic username ascii compatible.

**Comment by Nocccer** [comment] 2022-07-21 16:43
Locale not detected is fixed via next legendary update. So epic names conform to the system locale should not crash anymore.

**Closed by Nocccer** 2022-07-21 16:43 UTC

**Comment by cmalvi** [comment] 2022-10-11 08:54
Oh sorry, you’re right. I mean the steam deck game mode, also note as gamescope

**Comment by remcomeer89** [comment] 2022-10-14 11:47
Same problem here, If i run Heroic Games Launcher from desktop mode on the steam deck i can start the launcher and the games run fine. If i add the launcher to steam and run it in Gaming mode the launcher wil run but the games give an error Failed to initialize player Failed to initialize graphics. Make sure you have DirectX 11 installed. The game i tried was Fall Guys. This game runs fine from the desktop mode.

**Comment by arielj** [comment] 2022-10-14 12:16
Have you tried adding the game to steam instead of the complete launcher? on the game page > tools > Add to Steam (do this in desktop mode)

**Comment by remcomeer89** [comment] 2022-10-14 12:23
yes, from here the game does not work as it should, or it will run but fails the anti cheat check or fails to launch at all. I think it has something to do with not being able to select Wine-Lutris-wine-7.2-2 in steam this is the one that works on the heroic games launcher

**Comment by arielj** [comment] 2022-10-14 19:54
follow our official guide to setup fall guys https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys

**Comment by Etaash-mathamsetty** [comment] 2022-10-14 20:19
> follow our official guide to setup fall guys [Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys)

oh that's where it is, I was looking for it lol

**Comment by LeonardoMantovani** [comment] 2025-02-03 13:06
I'm facing a similar issue.

I have Heroic as a flatpak (version 2.15.2) and Steam as a flatpak as well (version 1.0.0.81). 

If I add a game from Heroic to Steam it appears in the steam library properly (with `flatpak` as target and `run com.heroicgameslauncher.hgl --no-gui --no-sandbox "heroic://launch/legendary/..."` as launch options. But if I then try to launch the game from steam I get the following error (printed in the terminal if I launch steam via command line, nothing is shown on the GUI):
```
chdir "/var/home/lez"
Game Recording - would start recording game 12260096395435835392, but recording for this game is disabled
Adding process 537 for gameID 12260096395435835392
ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
pid 538 != 537, skipping destruction (fork without exec?)
Game Recording - game stopped [gameid=12260096395435835392]
Removing process 537 for gameID 12260096395435835392
```

Any idea about why is this happening?

> Locale not detected is fixed via next legendary update. So epic names conform to the system locale should not crash anymore.
I do have a special character in my epic username, but from this @Nocccer message above I understand that that problem has been fixed and shouldn't be an issue anymore, right?

**Comment by psygreg** [comment] 2025-06-12 04:41
> I'm facing a similar issue.
> 
> I have Heroic as a flatpak (version 2.15.2) and Steam as a flatpak as well (version 1.0.0.81).
> 
> If I add a game from Heroic to Steam it appears in the steam library properly (with `flatpak` as target and `run com.heroicgameslauncher.hgl --no-gui --no-sandbox "heroic://launch/legendary/..."` as launch options. But if I then try to launch the game from steam I get the following error (printed in the terminal if I launch steam via command line, nothing is shown on the GUI):
> 
> ```
> chdir "/var/home/lez"
> Game Recording - would start recording game 12260096395435835392, but recording for this game is disabled
> Adding process 537 for gameID 12260096395435835392
> ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/var/home/lez/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> pid 538 != 537, skipping destruction (fork without exec?)
> Game Recording - game stopped [gameid=12260096395435835392]
> Removing process 537 for gameID 12260096395435835392
> ```
> 
> Any idea about why is this happening?
> 
> > Locale not detected is fixed via next legendary update. So epic names conform to the system locale should not crash anymore.
> 
> I do have a special character in my epic username, but from this [@Nocccer](https://github.com/Nocccer) message above I understand that that problem has been fixed and shouldn't be an issue anymore, right?

Similar situation here, although with a different error message. I did change target to `flatpak-spawn --host` and added `flatpak` before `run com.heroic...`, since that works for Lutris games. Also, the game will work if Heroic is already running in the background, but it can't 'summon' Heroic as intended. Just running the `flatpak run...` command works fine, although throws several error messages. 

```Game Recording - would start recording game 9774518243359195136, but recording for this game is disabled
Adding process 623 for gameID 9774518243359195136
F: Não será compartilhado “/usr/share/icons” com caixa de proteção: O caminho "/usr" está reservado pelo Flatpak
WARNING: discarding _NET_WM_PID 2560 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 5 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
[12:0612/013808.129626:ERROR:ui/ozone/platform/x11/ozone_platform_x11.cc:250] Missing X server or $DISPLAY
[12:0612/013808.129653:ERROR:ui/aura/env.cc:257] The platform failed to initialize.  Exiting.
/app/bin/heroic-run, linha 6:    12 Falha de segmentação  (imagem do núcleo gravada)zypak-wrapper /app/bin/heroic/heroic "$@"
Game Recording - game stopped [gameid=9774518243359195136]
Removing process 623 for gameID 9774518243359195136
