### ISSUE TITLE
Add support for launching heroic launcher games through steam.

### ISSUE THREAD

**Issue by epicsucks** [Heroic-Games-Launcher/HeroicGamesLauncher#756] opened 2021-11-24 22:14 UTC
**Is your feature request related to a problem? Please describe.**
I have a steam controller. Therefore I need to launch epic games store games (specifically rocket league) through steam. Back on windows I did this using steam grid db manager. Right now I have to use an independent driver like sc-controller. It works, but it's missing features, and is very unstable. I have already tried making a non steam game and in the target section putting `xdg-open heroic://launch/Sugar` I have also tried running a bash script that runs the same command. the first attempt does nothing. the second one launches heroic, but not rocket league.

**Describe the solution you'd like**
Ideally I would like a button that automatically adds a game as a non steam game. That's what I had with steam grid db manager.

**Describe alternatives you've considered**
Alternately I would like a way, even technically complex, that is guaranteed to make the game launch every time.

**Additional context**
I decided to make this a feature request, rather than a bug report, but I think it could go either way. Apologies if it doesn't belong in this category.

**Comment by flavioislima** [comment] 2021-11-26 07:27
Have you tried adding the desktop icon for the game using heroic and then adding it as a non steam game?

This works for me just fine.
You can set up heroic to open minimized as well so it will open the game only.

**Comment by epicsucks** [comment] 2021-11-26 14:04
At this point I've tried
a. import it into steam normally
b. xdg-open command in steam
c. launching a script that runs the xdg-open command (runs heroic but never
appears to launch rl)
d. the gtk-launch command in steam itself
e. the gtk-launch command in a script
In both cases I have verified that the scripts did actually run.
In both cases those same commands outside of being launched through steam
worked perfectly.

**Comment by dragonDScript** [comment] 2021-12-07 19:17
You can add heroic and its games to steam. What's the issue?
![image](https://user-images.githubusercontent.com/46191980/145092041-d9752b5f-7ff8-432c-8076-c0e78a964783.png)

**Comment by AWBuchanan7** [comment] 2021-12-08 05:06
To be clear: if I add heroic games via 'Add a Non-Steam game', the games appear in Steam but no heroic game I've tried will actually launch via Steam. If Heroic is open already, nothing happens. If Heroic is closed nothing happens but sometimes Steam freezes up.

**Comment by flavioislima** [comment] 2021-12-08 08:24
Yes I can confirm the issue, the same thing happened to me.
Weird because this used to work some time ago, I don't know if this is a bug on Steam or not because it works on Lutris for me.
So standalone Shortcuts works fine.
Shortcuts on Lutris works
Shortcuts on Steam doesn't.

another is is to check if other desktop shortcuts (from lutris for instance) works on steam.
And if they work, check the difference in content between Heroic and Lutris shortcuts.

**Comment by lucifertdark** [comment] 2021-12-08 09:25
I don't know if this is the same thing but Steam has a problem with spaces in names when adding non-steam games, I've had steam freeze on me because of this. Steam puts everything before the space in the correct place then adds the rest elsewhere meaning the link will never work.

**Comment by AWBuchanan7** [comment] 2021-12-08 17:58
Unfortunately, I don't think it's related to the spaces, I tried many of the approaches @epicsucks mentioned above and specifically with using a script that approach means no spaces are needed in the 'non-steam' game entry and I still had no luck with it.

@flavioislima For me I have non-steam games added via lutris, itch.io, and a non-steam shortcut for the Daggerfall Unity project that all work.

Example lutris non-steam game entry:

```
Target: "env"
Start in: "./"
Launch options: LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/72
```

And a heroic non-steam game entry:

```
Target: "xdg-open"
Start in: "./"
Launch options: heroic://launch/Peppermint
```

**Comment by redromnon** [comment] 2021-12-10 13:45
Have you tried adding the game as a bash script (that includes the entire launch command)? Works flawlessly for me.
![BashScriptSteam](https://user-images.githubusercontent.com/74495920/145583514-72a1793d-e511-4490-8f69-a9ae5e766d7b.png)
.

**Comment by epicsucks** [comment] 2021-12-18 17:38
Of course, another solution would be to add steam controller support. This,
however, is far too much to ask for such an obscure controller. I would
love it, but I'm not going to ask anybody, because I know I would be
overwhelmed personally.

**Comment by djibux** [comment] 2022-01-08 00:31
I confirm that shortcuts don't work for me in Steam.  It's unfortunate as it would make it possible, with tools like https://github.com/m4dEngi/RemotePlayWhatever, to enable Remote Play Together with Epic Games.

**Comment by flavioislima** [comment] 2022-01-08 00:55
You can use this tool to add heroic games to steam or any other launchers that you want:
https://github.com/redromnon/HeroicBashLauncher

**Comment by djibux** [comment] 2022-01-08 13:37
Thanks.

**Comment by veganjin** [comment] 2022-01-14 09:15
i have been successful using normal add non steam game to steam and launching … but i have to make sure to select proton 6.3-8  and it works flawlessly… GE hasnt been

**Comment by flavioislima** [comment] 2022-03-12 12:41
I will close this one in favor of:
#1089

**Closed by flavioislima** 2022-03-12 12:41 UTC
