### ISSUE TITLE
Importing Steam games into the Heroic Launcher

### ISSUE THREAD

**Issue by Schweppesale** [Heroic-Games-Launcher/HeroicGamesLauncher#4148] opened 2024-12-02 05:16 UTC
### Problem description

The Heroic launcher's reliance on Steam for grouping games together through the creation of shortcuts is less than ideal for users who prefer the appearance of the Heroic Games Launcher.

If there was some way to import these games into Heroic then it would also be possible to associate different types of metadata with each of them including descriptions, images, genres, etc while providing the user with a much cleaner interface.

Playnite for example which serves a similar purpose within the Windows space achieves this by supporting various [plugins](https://playnite.link/addons.html) that allow the user to customize its layout and modify the source of metadata.

It also allows them to categorize and group these games together which is something that is already supported by Heroic.

### Feature description

* implement some method of scanning installed Steam games and importing them into the Heroic Launcher.

### Alternatives

There's been some discussion about adding Linux support to [playnite](https://github.com/JosefNemec/Playnite/issues/59) but as explained by its maintainer this may not be possible within the near future since it would require that the entire front-end be [rewritten](https://github.com/JosefNemec/Playnite/issues/59#issuecomment-1083572073).

**Comment by arielj** [comment] 2024-12-15 21:35
Closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2872

**Closed by arielj** 2024-12-15 21:35 UTC
Labels: feature-request
