### ISSUE TITLE
Unable to launch installed games.

### ISSUE THREAD

**Issue by DuttaAB-dev** [Heroic-Games-Launcher/HeroicGamesLauncher#498] opened 2021-07-01 05:29 UTC
**Describe the bug**
Games installed using the launcher wont run after the initial run. After the initial run, clicking the "play" button says its "playing" for a few seconds, and then again turns back to "play" 

**To Reproduce**

1. Install a game
2. Click on play game
3. See error

**Expected behavior**
The launcher should launch the game

**Desktop (please complete the following information):**

- OS: Pop!_OS 21.04/Fedora 34
-Launcher Version 1.7.2
- Game: GTA V/ TACOMA/ Horizon Chase Turbo
- Wine/Proton version: Proton: 6.3/5.13/5.0, Lutris wine 6.10
- Hardware specs (RAM, CPU, GPU):core 2 duo, 4gb ram, nvidia gt710/ core i5 8th gen, 8 gb ram, nvidia mx 250

**Comment by flavioislima** [comment] 2021-07-01 07:09
I might be wrong but I bet the issue is with your video cards. I'm almost certain that they don't support Vulkan, so they won't play any game on Linux that uses dxvk.
Go to the game page, click on the Settings button then click on Latest log. And upload it here.

**Comment by el-banto** [comment] 2021-07-02 13:56
Both NVIDIA GPUs should support Vulkan 1.2
https://developer.nvidia.com/vulkan-driver

**Comment by flavioislima** [comment] 2021-07-02 14:28
> Both NVIDIA GPUs should support Vulkan 1.2
> https://developer.nvidia.com/vulkan-driver

OK, then start from here:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#game-wont-launch

**Comment by DuttaAB-dev** [comment] 2021-07-02 20:11
> > Both NVIDIA GPUs should support Vulkan 1.2
> > https://developer.nvidia.com/vulkan-driver
> 
> OK, then start from here:
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#game-wont-launch

``` [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching bb406082b69a47208489d3616b22b5c2...
gamemodeauto: 
gamemodeauto: 
esync: up and running.
gamemodeauto: 
gamemodeauto: ```

Here is all that I have in my logs while launching Horizon Chase Turbo while using proton 5.13

**Comment by flavioislima** [comment] 2021-07-02 20:25
> > > Both NVIDIA GPUs should support Vulkan 1.2
> > > https://developer.nvidia.com/vulkan-driver
> > 
> > OK, then start from here:
> > https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#game-wont-launch
> 
> ``` [cli] INFO: Logging in...
> [Core] INFO: Trying to re-use existing login session...
> [cli] INFO: Checking for updates...
> [Core] INFO: Getting authentication token...
> [cli] INFO: Launching bb406082b69a47208489d3616b22b5c2...
> gamemodeauto: 
> gamemodeauto: 
> esync: up and running.
> gamemodeauto: 
> gamemodeauto: 
> ```
> 
> Here is all that I have in my logs while launching Horizon Chase Turbo while using proton 5.13

The game is being launched, we can see by the wine logs. So should be some proton issue. Let's close this issue since its not an heroic issue and we can continue helping you on our discord.

**Closed by flavioislima** 2021-07-02 20:25 UTC
Labels: bug:not-confirmed, issue:investigating

**Comment by DuttaAB-dev** [comment] 2021-07-02 20:30
> > > > Both NVIDIA GPUs should support Vulkan 1.2
> > > > https://developer.nvidia.com/vulkan-driver
> > > 
> > > 
> > > OK, then start from here:
> > > https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#game-wont-launch
> > 
> > 
> > ```
> > [Core] INFO: Trying to re-use existing login session...
> > [cli] INFO: Checking for updates...
> > [Core] INFO: Getting authentication token...
> > [cli] INFO: Launching bb406082b69a47208489d3616b22b5c2...
> > gamemodeauto: 
> > gamemodeauto: 
> > esync: up and running.
> > gamemodeauto: 
> > gamemodeauto: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is all that I have in my logs while launching Horizon Chase Turbo while using proton 5.13
> 
> The game is being launched, we can see by the wine logs. So should be some proton issue. Let's close this issue since its not an heroic issue and we can continue helping you on our discord.

Yeah, I thing this is a proton issue as running both this and tacoma with vanilla wine works while using lutris wine gives an incompatibility error so this might just be a runner issue.
Side note though, when running with proton with the game-mode indicator enabled, the indicator says game mode enabled for a few seconds and then after a few seconds says game mode disabled. This is along with the usual behavour of using proton, that is nothing is launched and the button reverts back to "play"
