### ISSUE TITLE
Empty blue window since latest update

### ISSUE THREAD

**Issue by Jpxe** [Heroic-Games-Launcher/HeroicGamesLauncher#1737] opened 2022-08-19 17:46 UTC
### Describe the bug

I use the Flatpak version on Fedora (Nobara Linux 36) and since the latest update it just shows a blue screen. Everything worked fine in the last version. Screenshot is attached below.

### Add logs
```
[jpx@fedora ~]$ flatpak run com.heroicgameslauncher.hgl
[3:0819/194543.221123:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Filen eller katalogen finns inte
[3:0819/194543.221264:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Filen eller katalogen finns inte
(19:45:43) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
hostname: ogiltig flagga -- "f"
Försök med ”hostname --help” för mer information.
(19:45:43) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:45:43) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:45:43) INFO:    [Backend]:         

Heroic Version: 2.4.0 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Freedesktop.org KERNEL: 5.18.17-201.fsync.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i5-4670K @3.4 GOVERNOR: schedutil
RAM: Total: 15.57 GiB Available: 9.58 GiB
GRAPHICS: GPU0: GM204 [GeForce GTX 980]  VRAM: 32MB DRIVER:  
PROTOCOL: x11

(19:45:43) INFO:    [Gog]:             Getting data about the user
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(19:45:43) WARNING: [Backend]:         Failed to register protocol with OS.
[3:0819/194543.927343:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0819/194543.927398:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0819/194543.927447:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(19:45:44) INFO:    [Gog]:             Saved user data to config
(19:45:44) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(19:45:46) INFO:    [Backend]:         Downloaded Winetricks
```

### Steps to reproduce

1. Open Heroic 

### Expected behavior

To open normaly

### Screenshots

![bild](https://user-images.githubusercontent.com/12818876/185676744-6e59d3e8-a42d-4a31-a3c1-92e0bcf1f05e.png)

### System Information
```
Heroic: v2.4.0

System:
  Host: fedora Kernel: 5.18.17-201.fsync.fc36.x86_64 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.25.4 Distro: Nobara release 36 (Thirty Six)
Machine:
  Type: Desktop System: MSI product: MS-7821 v: 1.0
  Mobo: MSI model: Z87-G45 GAMING (MS-7821) v: 1.0
    BIOS: American Megatrends v: 1.9
    date: 07/21/2014
CPU:
  Info: quad core Intel Core i5-4670K [MCP] speed (MHz): avg: 2105
    min/max: 800/3800
Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 980] driver: nvidia v: 515.65.01
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.3 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080~60Hz
    2: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 980/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.65.01
Network:
  Device-1: Qualcomm Atheros Killer E220x Gigabit Ethernet driver: alx
Drives:
  Local Storage: total: 3.87 TiB used: 169.25 GiB (4.3%)
Info:
  Processes: 586 Uptime: 7m Memory: 15.57 GiB used: 5.75 GiB (37.0%)
  Shell: Bash inxi: 3.3.19
```

**Comment by arielj** [comment] 2022-08-19 19:56
Can you check if there's any error in the frontend? right click the tray icon > debug > it should open dev tools in the front end > click the console tab

**Comment by hjeldin** [comment] 2022-08-20 08:40
Can confirm, the issue is that some elements in getRecentGames are null. 
Here's a simple patch:
```diff --git a/src/helpers/library.ts b/src/helpers/library.ts
index 41cca645..88f4e13c 100644
--- a/src/helpers/library.ts
+++ b/src/helpers/library.ts
@@ -304,6 +304,7 @@ function getRecentGames(libraries: GameInfo[]) {
     (configStore.get('games.recent', []) as Array<RecentGame>) || []
   return (
     recentGames
+      .filter(m => m !== null)
       .map((game) => {
         return libraries.find((info) => info.app_name === game.appName)```

It would be interesting to understand why recent games contain null entries, but still...

**Comment by Jpxe** [comment] 2022-08-20 17:09
@arielj 
```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'title')
    at index.tsx:26:54
    at Array.map (<anonymous>)
    at index.tsx:26:41
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at k (index.tsx:24:16)
    at si (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Nl (react-dom.production.min.js:250:347)
    at Zl (react-dom.production.min.js:250:278)
us @ react-dom.production.min.js:216
scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'title')
    at index.tsx:26:54
    at Array.map (<anonymous>)
    at index.tsx:26:41
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at k (index.tsx:24:16)
    at si (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Nl (react-dom.production.min.js:250:347)
    at Zl (react-dom.production.min.js:250:278)
```

**Comment by Nocccer** [comment] 2022-08-20 18:36
@Jpxe @hjeldin can you try out that appimage. I added @hjeldin fix:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7903589505/artifacts/336208351

**Comment by Jpxe** [comment] 2022-08-20 19:19
@Nocccer works!

**Comment by hjeldin** [comment] 2022-08-20 19:34
Confirmed, it works!

**Comment by C-Desk** [comment] 2022-08-21 03:25
Same issue using flatpak on steam deck. By any chance could the game Rumbleverse going from beta to full release be the null entry issue with the recent games list?

**Comment by Nocccer** [comment] 2022-08-21 14:05
Ok i think i know the problem with recent games. We pass the epic and gog library. If you don't have gog games or epic games it passes a null value or on startup if the game library is big and not loaded yet.

Can you confirm that you don't have for example gog games? Means you don't have a gog account or no game added to your gog account so far. Vice versa for epic.

**Comment by Jpxe** [comment] 2022-08-21 14:58
I have 555 GOG games and 174 Epic games

**Comment by Nocccer** [comment] 2022-08-21 15:14
> I have 555 GOG games and 174 Epic games

Ok but you had another problem with the searchBar. Atleast your error was somewhere else and i fixed that aswell.

**Comment by C-Desk** [comment] 2022-08-21 15:42
I have a few GOG games but did not sign in on Heroic yet as I only needed a few Epic games.

**Comment by gazhay** [comment] 2022-08-23 13:06
Found my way here with the same issue.

Tried the attached appimage a few posts up and the new error I get in the console is 

````
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
    at library.ts:302:42
    at Array.find (<anonymous>)
    at library.ts:302:22
    at Array.map (<anonymous>)
    at y (library.ts:301:38)
    at d (index.tsx:20:40)
    at index.tsx:29:5
    at Fl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
us @ react-dom.production.min.js:216
scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
    at library.ts:302:42
    at Array.find (<anonymous>)
    at library.ts:302:22
    at Array.map (<anonymous>)
    at y (library.ts:301:38)
    at d (index.tsx:20:40)
    at index.tsx:29:5
    at Fl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
    at library.ts:302:42
    at Array.find (<anonymous>)
    at library.ts:302:22
    at Array.map (<anonymous>)
    at y (library.ts:301:38)
    at d (index.tsx:20:40)
    at index.tsx:29:5
    at Fl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
us @ react-dom.production.min.js:216
scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
    at library.ts:302:42
    at Array.find (<anonymous>)
    at library.ts:302:22
    at Array.map (<anonymous>)
    at y (library.ts:301:38)
    at d (index.tsx:20:40)
    at index.tsx:29:5
    at Fl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
````

**Comment by flavioislima** [comment] 2022-08-23 13:26
> Found my way here with the same issue.
> 
> Tried the attached appimage a few posts up and the new error I get in the console is
> 
> ```
> react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
>     at library.ts:302:42
>     at Array.find (<anonymous>)
>     at library.ts:302:22
>     at Array.map (<anonymous>)
>     at y (library.ts:301:38)
>     at d (index.tsx:20:40)
>     at index.tsx:29:5
>     at Fl (react-dom.production.min.js:262:359)
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at Ga (react-dom.production.min.js:122:325)
> us @ react-dom.production.min.js:216
> scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
>     at library.ts:302:42
>     at Array.find (<anonymous>)
>     at library.ts:302:22
>     at Array.map (<anonymous>)
>     at y (library.ts:301:38)
>     at d (index.tsx:20:40)
>     at index.tsx:29:5
>     at Fl (react-dom.production.min.js:262:359)
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at Ga (react-dom.production.min.js:122:325)react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
>     at library.ts:302:42
>     at Array.find (<anonymous>)
>     at library.ts:302:22
>     at Array.map (<anonymous>)
>     at y (library.ts:301:38)
>     at d (index.tsx:20:40)
>     at index.tsx:29:5
>     at Fl (react-dom.production.min.js:262:359)
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at Ga (react-dom.production.min.js:122:325)
> us @ react-dom.production.min.js:216
> scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
>     at library.ts:302:42
>     at Array.find (<anonymous>)
>     at library.ts:302:22
>     at Array.map (<anonymous>)
>     at y (library.ts:301:38)
>     at d (index.tsx:20:40)
>     at index.tsx:29:5
>     at Fl (react-dom.production.min.js:262:359)
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at Ga (react-dom.production.min.js:122:325)
> ```

which game? it is GOG or epic?

**Comment by github12101** [comment] 2022-08-24 13:57
Same on .deb install on Debian Testing system.
```

$ apt-cache policy heroic
heroic:
  Installed: 2.4.0
  Candidate: 2.4.0
  Version table:
 *** 2.4.0 100
        100 /var/lib/dpkg/status
```

Terminal:

```
$ heroic 
(14:55:46) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:55:47) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:55:47) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:55:47) INFO:    [Backend]:         

Heroic Version: 2.4.0 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Debian GNU/Linux KERNEL: 5.18.0-4-amd64 ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 62.72 GiB Available: 56.66 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: x11

(14:55:47) INFO:    [Gog]:             Getting data about the user
APPIMAGE env is not defined, current application is not an AppImage
(14:55:47) WARNING: [Backend]:         Protocol already registered.
[263672:0824/145547.534334:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[263672:0824/145547.534376:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[263672:0824/145547.534402:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(14:55:47) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(14:55:47) INFO:    [Gog]:             Saved user data to config
(14:55:50) INFO:    [Backend]:         Downloaded Winetricks
```

It just hungs like that, nothing is happening.

![image](https://user-images.githubusercontent.com/1646393/186437461-83d8544c-6e9e-488d-9337-29f69b90b113.png)

**Comment by Nocccer** [comment] 2022-08-25 10:55
> ry.ts:302:42

This should be fixed by the PR linked aswell.

**Comment by Nocccer** [comment] 2022-08-25 11:01
New AppImage to try the fix:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7977680122/artifacts/341338451

**Comment by GmoLargey** [comment] 2022-08-25 23:34
noticed this a while back and its same now, the link above is down though, as its marked fixed is there an update to flatpack coming?

**Comment by github12101** [comment] 2022-08-26 03:06
> New AppImage to try the fix: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7977680122/artifacts/341338451

Thanks for fix! Please let us know once .deb is available, I will be happy to test experimental deb, but no AppImage as I already have deb installed so probably running deb and then AppImage on same system is not great idea.

**Comment by github12101** [comment] 2022-09-01 13:11
New release is out. I installed .deb and tried again.
Same problem. Just empty window. Terminal:

```
$ heroic 
(14:10:02) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:10:02) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:10:02) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:10:02) INFO:    [Backend]:         

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Debian GNU/Linux KERNEL: 5.18.0-4-amd64 ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 62.72 GiB Available: 48.62 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: x11

(14:10:03) INFO:    [Gog]:             Getting data about the user
(14:10:03) INFO:    [Gog]:             Refreshing access_token
APPIMAGE env is not defined, current application is not an AppImage
(14:10:03) WARNING: [Backend]:         Protocol already registered.
[3552093:0901/141003.114471:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3552093:0901/141003.114518:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3552093:0901/141003.114546:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(14:10:03) INFO:    [Gog]:             Token refreshed successfully
(14:10:03) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(14:10:03) INFO:    [Backend]:         Checking for new Heroic Updates
(14:10:03) INFO:    [Frontend]:        Refreshing Library
(14:10:03) INFO:    [Legendary]:       Refreshing library...
(14:10:03) INFO:    [Legendary]:       Refreshing Epic Games...
(14:10:03) INFO:    [Gog]:             Getting GOG library
(14:10:03) INFO:    [Gog]:             Saved user data to config
(14:10:04) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:10:04) INFO:    [Gog]:             Number of library pages: 1
(14:10:05) INFO:    [Gog]:             Saved games data
(14:10:05) INFO:    [Backend]:         Downloaded Winetricks
(14:10:06) INFO:    [Legendary]:       Updating game list
(14:10:06) INFO:    [Legendary]:       Game List Updated
(14:10:06) INFO:    [Legendary]:       Checking for game updates.
(14:10:06) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(14:10:07) INFO:    [Legendary]:       Found 1 game(s) to update
(14:10:07) INFO:    [Gog]:             Found 0 game(s) to update
(14:10:07) INFO:    [Frontend]:        Force Update
```

**Comment by github12101** [comment] 2022-09-01 13:15
> New AppImage to try the fix: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7977680122/artifacts/341338451

Why is this closed as completed? Problem still exists in latest version. Please re-open.

**Comment by Nocccer** [comment] 2022-09-01 13:20
Would be a new error then. Can you bring up the dev console via tray icon > debug and send the error log why it fails to render?

**Comment by Jpxe** [comment] 2022-09-01 18:50
I still have the same issue with latest Flatpak.

Here's an error log from when it first happened: https://gist.github.com/Jpxe/db10e3209b16f0fc29a1878f88b74227

Here's when I launched it a second time: https://gist.github.com/Jpxe/11345e738cee7fd19f1133e49be529c1

**Comment by Nocccer** [comment] 2022-09-02 14:31
> I still have the same issue with latest Flatpak.
> 
> Here's an error log from when it first happened: https://gist.github.com/Jpxe/db10e3209b16f0fc29a1878f88b74227
> 
> Here's when I launched it a second time: https://gist.github.com/Jpxe/11345e738cee7fd19f1133e49be529c1

I pushed a fix. If you can get to the settings you could disable to show recent games. Maybe that is a workaround for now.

**Comment by Jpxe** [comment] 2022-09-03 09:58
@Nocccer Seems to work now but I'll keep checking. This might be an unrelated bug but for some reason I can't get Knockout City to show, neither in Flatpak or your AppImage. Should I make a new issue?

**Comment by sifiro** [comment] 2022-09-04 08:28
If you want a quick fix:
delete `$HOME/.var/app/com.heroicgameslauncher.hgl/config/heroic/lib-cache`.
For me, works again after the empty blue screen issue

**Comment by Jpxe** [comment] 2022-09-04 08:52
@sifiro I tried that
Opened it and now it's all blue again...

Also no log this time

![bild](https://user-images.githubusercontent.com/12818876/188305510-74e6cc17-f084-4538-9b59-e93abaf33b2c.png)

**Comment by Jpxe** [comment] 2022-09-04 08:58
Relaunched it, now it had logged out. I logged in and the games where back again. Still can't find Knockout City on Epic

![bild](https://user-images.githubusercontent.com/12818876/188305759-a586f4de-0443-46c8-ae5f-d8f846e28ca9.png)
![bild](https://user-images.githubusercontent.com/12818876/188305772-b734a79d-276e-4977-b673-e5cd603f6978.png)

**Closed** 2022-09-09 16:56 UTC
Labels: bug:confirmed, high priority
