### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by PrzemekSkw** [Heroic-Games-Launcher/HeroicGamesLauncher#331] opened 2021-04-27 12:37 UTC
**Describe the bug**
I see empty window when start Heroic launcher. I install from AUR.

**Screenshots**
![Zrzut ekranu z 2021-04-27 14-34-10](https://user-images.githubusercontent.com/25219988/116242146-ecb8c680-a765-11eb-8273-4d7281d97a12.png)

**Desktop (please complete the following information):**

- OS: EndevourOS [Archlinux]
- Version Gnome 40, 5.11.16-arch1-1

Regards.

**Comment by StoneyFish** [comment] 2021-04-27 13:26
The 1.5.7 deb is working well. The 1.5.8 deb gives me a blank black window on Ubuntu 20.10.  removing 1.5.8 and re-installing 1.5.7 deb again allows the application to open normally - although it did start with the Epic ID setup again, then I can see my games library and installed games show up and the custom configured game install location is unchanged. Games work.

**Comment by adityaruplaha** [comment] 2021-04-27 14:40
Duplicate of #329.

We're aware of the bug and are trying to fix it.

**Closed by adityaruplaha** 2021-04-27 14:40 UTC

**Comment by PrzemekSkw** [comment] 2021-04-28 05:59
Thanks.

**Comment by StoneyFish** [comment] 2021-04-28 06:34
Thanks

**Comment by PrzemekSkw** [comment] 2021-04-28 06:56
It works after todays upgrade. Thanks.

**Comment by adityaruplaha** [comment] 2021-04-28 08:27
Yeah 1.5.9 fixed. Sorry about this, I fucked up real bad.
