### ISSUE TITLE
Can’t login to Gog on heroic launcher on steam deck

### ISSUE THREAD

**Issue by Zortheus88** [Heroic-Games-Launcher/HeroicGamesLauncher#2874] opened 2023-07-20 03:13 UTC
### Describe the bug

Can’t login to gog on heroic launcher on steam deck. I can login to epic no problem. Every time I try to login to gog it just loads for a few seconds and takes me back to the login page. 

### Add logs

```text
(22:56:38) INFO:    [Legendary]:        Refreshing library...
(22:56:38) INFO:    [Legendary]:        Refreshing Epic Games...
(22:56:38) INFO:    [Connection]:       Connectivity: check-online
(22:56:38) INFO:    [Connection]:       Pinging external endpoints
(22:56:38) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:56:38) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:56:38) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:56:38) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:56:38) INFO:    [Legendary]:        Game list updated, got 9 games & DLCs
(22:56:38) WARNING: [Backend]:          Failed to register protocol with OS.
(22:56:38) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(22:56:38) INFO:    [Backend]:          Loading Screen Ready
(22:56:38) INFO:    [Frontend]:         Refreshing undefined Library
(22:56:38) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:56:38) INFO:    [Backend]:          Frontend Ready
(22:56:39) INFO:    [Backend]:          Checking for current version changelog
(22:56:39) INFO:    [Backend]:          

Heroic Version: 2.8.0 Nico Robin
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.2

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.61 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 11.29 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(22:56:39) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(22:56:40) INFO:    [Connection]:       Connectivity: online
(22:56:40) INFO:    [Winetricks]:       Downloading Winetricks
(22:56:40) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:56:43) INFO:    [Backend]:          Starting the Download Queue
(22:57:30) INFO:    [Gog]:              Logging using GOG credentials
(22:57:30) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth --code <redacted>
(22:57:30) ERROR:   [Gog]:              GOG login failed to parse std output from gogdl. stdout:
```

### Steps to reproduce

1. Go to “stores”
2. Click on “gog store” then “log in” and log in now after entering password 
3. Shows it loading 
4. Then goes back to login page. It doesn’t show any error message

### Expected behavior

I expected to be logged in to gog

### Heroic Version

Latest Stable

### System Information

- steam deck steam OS

**Comment by microfx** [comment] 2023-07-26 12:09
Same for me ... but says wrong password. Tried to type it in 10x now... weird.

**Comment by microfx** [comment] 2023-07-26 16:48
It worked now for me - you have to find the button from heroic again and then retry On 26 Jul 2023, at 18:04, desht ***@***.***> wrote:﻿
Same deal here.  Password's definitely right, I can log into gog.com via browser no problem.  But if I try via heroic launcher, I get:
(17:00:25) INFO:    [Gog]:              Logging using GOG credentials
(17:00:25) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/des/.config/heroic/gog_store/auth.json auth --code <redacted>
(17:00:25) ERROR:   [Gog]:              GOG login failed to parse std output from gogdl. stdout: 

and that's all.
No errors in the GUI, just pops back to the login screen.
Broken on both 2.8.0 and 2.9.0 versions of the launcher.

**Comment by imLinguin** [comment] 2023-07-26 19:15
Could you provide gogdl logs from 
`~/.var/app/com.heroicgameslauncher.hgl/config/heroic/logs`? Try to reproduce the issue and get the newest one

**Comment by Zortheus88** [comment] 2023-07-26 19:49
I got it to work on my steam deck earlier this week.  After figuring out the heroic launcher for me worked on my pc but not the steam deck for whatever reason I did a factory reset and now I can use GOG on the steam deck.

**Comment by desht** [comment] 2023-07-27 07:22
> you have to find the button from heroic again and then retry 

What button?

```
[27/07/2023, 08:18:49] /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/des/.config/heroic/gog_store/auth.json --version
[22746] Error loading Python lib '/tmp/_MEIPHbd3W/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIPHbd3W/libpython3.9.so.1.0)
[27/07/2023, 08:19:31] /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/des/.config/heroic/gog_store/auth.json auth --code <redacted>
[22947] Error loading Python lib '/tmp/_MEIXkNwSs/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIXkNwSs/libpython3.9.so.1.0)
```

Ah.  It needs a newer version of glibc than I have.  Oh well.

**Comment by imLinguin** [comment] 2023-07-27 07:26
Try flatpak release

**Comment by microfx** [comment] 2023-07-27 09:41
The login buttons from Manage Account tab - it worked 2nd time. On 27 Jul 2023, at 09:27, Paweł Lidwin ***@***.***> wrote:﻿
Try flatpak release

**Comment by arielj** [comment] 2023-12-16 03:04
Is this still happening with Heroic 2.11.0?

**Comment by arielj** [comment] 2023-12-31 04:05
Closing since there's no answers. We can reopen if the issue reappears.

**Closed by arielj** 2023-12-31 04:05 UTC
Labels: bug:unconfirmed

**Comment by kulvind3r** [comment] 2024-01-05 04:16
This is still happening in Heroic Portable 2.11.0 on windows.

**Comment by imLinguin** [comment] 2024-01-31 14:54
GOG had server issues, everything is resolved now @Crashdummyy

**Comment by RichSPK** [comment] 2024-04-13 22:40
I'm also unable to log into the GOG store via HGL.  I get no error; it just drops me back to the account management page.
Note that I just uninstalled the Flatpak and installed the deb.  (I had been having some trouble with an older version of HGL after not using it for several months.)
From the Heroic log:
(18:13:47) INFO:    [Gog]:              Logging using GOG credentials
(18:13:47) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/rklein/.config/heroic/gogdlConfig /home/rklein/Downloads/gogdl-Linux/gogdl --auth-config-path /home/rklein/.config/heroic/gog_store/auth.json auth --code <redacted>
(18:13:48) ERROR:   [Gog]:              GOG login failed to parse std output from gogdl. stdout: 
And from the GOG log:
[4/13/2024, 6:08:56 PM] GOGDL_CONFIG_PATH=/home/rklein/.config/heroic/gogdlConfig /home/rklein/Downloads/gogdl-Linux/gogdl --auth-config-path /home/rklein/.config/heroic/gog_store/auth.json auth --code <redacted>

usage: gogdl [-h] [--version]

             {download,repair,update,import,info,launch,save-sync,save-clear}

             ...

gogdl: error: argument command: invalid choice: '/home/rklein/.config/heroic/gog_store/auth.json' (choose from 'download', 'repair', 'update', 'import', 'info', 'launch', 'save-sync', 'save-clear')


[2024-04-13T22_04_29-heroic.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/14968856/2024-04-13T22_04_29-heroic.log)

[2024-04-13T22_04_29-gogdl.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/14968857/2024-04-13T22_04_29-gogdl.log)

**Comment by imLinguin** [comment] 2024-04-14 10:33
You seem to have a gogdl executable override set in heroic settings, please remove it and try again

**Comment by RichSPK** [comment] 2024-04-14 12:35
Weird.  That must have been left over from the Flatpak install.

To remove that, I opened HGL, went to Settings, Advanced, and then deleted the text under "Choose an Alternative GOGDL Binary to use".  That fixed my problem and I was then able to log into my GOG account.

**Comment by TrillTrappin** [comment] 2024-05-24 13:37
I just had the same issue as OP. I got around the issue by going to the "Manage Accounts" tab on the left hand menu on my Steam Deck OLED in the Desktop Mode, and added my GOG account that way, instead of clicking the store button and trying to log in the route.
