### ISSUE TITLE
Ubisoft integration?

### ISSUE THREAD

**Issue by Felistopus** [Heroic-Games-Launcher/HeroicGamesLauncher#1860] opened 2022-10-02 15:15 UTC
### Feature description

When is Ubisoft Connect store integration?, and will it exist anytime soon?

**Comment by arielj** [comment] 2022-10-02 15:59
Duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1768.

If it's done it will be done when somebody codes that, there's no way to estimate that.

**Closed by arielj** 2022-10-02 15:59 UTC
