### ISSUE TITLE
List steam games also to launch

### ISSUE THREAD

**Issue by niksingh710** [Heroic-Games-Launcher/HeroicGamesLauncher#3138] opened 2023-10-16 09:24 UTC
### Problem description

I love heroic launcher and I like to have all my ganes at one place
It would be nice if I can launch my steam games using heroic 

### Feature description

Steams games listed in heroic library and launched

**Comment by arielj** [comment] 2023-11-05 15:41
Closing as a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2872

**Closed by arielj** 2023-11-05 15:41 UTC
Labels: feature-request
