### ISSUE TITLE
EAC Runtime not present after fresh install

### ISSUE THREAD

**Issue by mimbrero** [Heroic-Games-Launcher/HeroicGamesLauncher#3139] opened 2023-10-16 10:55 UTC
### Describe the bug

After installing Heroic and downloading a game that requires the EAC runtime (Fall Guys in my case), the EAC runtime option is checked, despite the runtime is not installed. This leads to the game telling that EAC is not initialised and the user thinking that the runtime is in theory installed and working.

### Add logs

```text
No logs related to this issue.
```

### Steps to reproduce

1. Uninstall Heroic Games Launcher
2. Delete all data from Heroic Games Launcher
3. Install again Heroic Games Launcher
4. [Install Fall Guys](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys)
5. EAC is checked but actually not installed
6. Uncheck the option and check it again, the runtime starts to download.

### Expected behavior

EAC runtime must install automatically with any game that requires it, or the option must be unchecked by default, to force the user to check it and install the runtime.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Fedora Linux 38 (Workstation edition)

**Comment by arielj** [comment] 2023-10-16 12:09
@Etaash-mathamsetty could this be caused by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3035 ?

**Comment by Etaash-mathamsetty** [comment] 2023-10-16 13:26
> @Etaash-mathamsetty could this be caused by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3035 ?
> 
> looks like we are just defaulting to enabled for launching the game but we are not triggering the command to download the runtimes?

That's definitely possible

**Comment by arielj** [comment] 2023-12-31 04:37
I understand this is fixed now, closing. We can reopen if it's not fixed.

**Closed by arielj** 2023-12-31 04:37 UTC
Labels: bug:unconfirmed
