### ISSUE TITLE
Wrong shop and no possibility to get the correct one back

### ISSUE THREAD

**Issue by Zykino** [Heroic-Games-Launcher/HeroicGamesLauncher#3252] opened 2023-11-21 21:19 UTC
### Describe the bug

I have EGS when I click on shops "* shop Epic" AND when I click on "* shop GOG".

I can confirm that those are 2 different pages: when I visit a game on one of them and another in the second, switching between the tab switch between the games.

### Add logs

```text
(22:02:59) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:02:59) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:02:59) INFO:    [Connection]:       Connectivity: check-online
(22:02:59) INFO:    [Connection]:       Pinging external endpoints
(22:02:59) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(22:02:59) WARNING: [Backend]:          Failed to register protocol with OS.
(22:02:59) INFO:    [Connection]:       Connectivity: online
(22:02:59) INFO:    [Gog]:              Checking if login is valid
(22:02:59) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:02:59) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:03:00) INFO:    [Backend]:          Loading Screen Ready
(22:03:00) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:03:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(22:03:00) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(22:03:00) INFO:    [Frontend]:         Refreshing undefined Library
(22:03:00) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:03:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:03:00) INFO:    [Legendary]:        Refreshing library...
(22:03:00) INFO:    [Legendary]:        Refreshing Epic Games...
(22:03:00) INFO:    [Legendary]:        Game list updated, got 136 games & DLCs
(22:03:00) INFO:    [Gog]:              Getting GOG library
(22:03:00) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:03:00) INFO:    [Backend]:          Frontend Ready
(22:03:00) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
Memory: 33.56 GB (used: 7.89 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti]
    IDs: D=1b82 V=10de SD=8620 SV=1043
    Driver: nvidia
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(22:03:00) INFO:    [Backend]:          Checking for current version changelog
(22:03:00) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(22:03:00) INFO:    [Gog]:              Saved username to config file
(22:03:01) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:03:02) INFO:    [Winetricks]:       Downloading Winetricks
(22:03:02) INFO:    [Gog]:              Saved games data
(22:03:02) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:03:04) INFO:    [Gog]:              Found 0 game(s) to update
(22:03:04) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/zykino/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(22:03:04) INFO:    [WineDownloader]:   Updating wine versions info
(22:03:04) INFO:    [WineDownloader]:   Fetching upstream information...
(22:03:05) INFO:    [Backend]:          Starting the Download Queue
(22:03:06) INFO:    [WineDownloader]:   wine versions updated
(22:03:06) INFO:    [Legendary]:        Found 0 games to update
(22:03:06) INFO:    [Frontend]:         Force Update
```

### Steps to reproduce

I don’t really know how I got there. I switched shops a bit and went into the library/parameters pages to test the new page remembering from last update.

I don’t have an amazon prime account connected but I have EGS and GoG. I think I clicked on all of them (and prime is very slow to load _and_ have a popup to ask me to connect into heroic not the website).

### Expected behavior

EGS not leaking into GOG.

I would also love a way to go back to the home page of the shops: I like that now heroic remember on which shop I was last when restarting it… but I don’t really care it remember on which page exactly (at least after a reboot).

Having a right click -> go to home shop page could be a good workaround.
Also an option to not remember the page after a shutdown.
Or maybe have a button on the shop’s page to go to their home page directly, so I can click on that while peoples clicking on the name keep their history?

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/3809938/72a99098-b4f9-43b5-b789-4ffce42c1d38)

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/3809938/1bec6d04-95f9-42b8-a282-aa2681a2921d)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Heroic: 2.10.0
- OS: Linux zykino-pop-os 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux

**Comment by arielj** [comment] 2023-11-21 21:26
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3200

will be fixed in the next release

**Closed by arielj** 2023-11-21 21:26 UTC
Labels: bug:unconfirmed
